/* ── DATA ──
   Source: data/persian_vocabulary.json (top 1000 Persian words by frequency)
   Schema: { id, r (transliteration), m (German meaning), t (pos/topic), n (Farsi script) }
*/

const TOPICS = [
  { id: 'verb', name: 'Verben', icon: '⚡' },
  { id: 'noun', name: 'Nomen', icon: '📦' },
  { id: 'adjective', name: 'Adjektive', icon: '🎨' },
  { id: 'adverb', name: 'Adverbien', icon: '⏩' },
  { id: 'preposition', name: 'Präpositionen', icon: '🔗' },
  { id: 'pronoun', name: 'Pronomen', icon: '👤' },
  { id: 'conjunction', name: 'Konjunktionen', icon: '➕' },
  { id: 'quantifier', name: 'Quantoren', icon: '🔢' },
  { id: 'proper noun', name: 'Eigennamen', icon: '🏷️' },
];

const VOCAB = [
  { id:    1, r: 'vav/va', m: 'und', t: 'conjunction', n: 'و' },
  { id:    2, r: 'budan', m: 'sein', t: 'verb', n: 'بودن' },
  { id:    3, r: 'az', m: 'von, aus', t: 'preposition', n: 'از' },
  { id:    4, r: 'be', m: 'zu, nach', t: 'preposition', n: 'به' },
  { id:    5, r: 'ke', m: 'dass, welcher', t: 'conjunction', n: 'که' },
  { id:    6, r: 'in', m: 'dieser', t: 'pronoun', n: 'این' },
  { id:    7, r: 'dar', m: 'in', t: 'preposition', n: 'در' },
  { id:    8, r: 'ba', m: 'mit', t: 'preposition', n: 'با' },
  { id:    9, r: 'shodan', m: 'werden', t: 'verb', n: 'شدن' },
  { id:   10, r: 'baraye', m: 'für', t: 'preposition', n: 'برای' },
  { id:   11, r: 'khod', m: 'selbst, eigen', t: 'pronoun', n: 'خود' },
  { id:   12, r: 'yek', m: 'ein, eins', t: 'noun', n: 'یک' },
  { id:   13, r: 'an', m: 'jener, das', t: 'pronoun', n: 'آن' },
  { id:   14, r: 'khastan', m: 'wollen', t: 'verb', n: 'خواستن' },
  { id:   15, r: 'ta', m: 'bis', t: 'preposition', n: 'تا' },
  { id:   16, r: 'dashtan', m: 'haben', t: 'verb', n: 'داشتن' },
  { id:   17, r: 'kardan', m: 'machen, tun', t: 'verb', n: 'کردن' },
  { id:   18, r: 'kard', m: 'machte, tat', t: 'verb', n: 'کرد' },
  { id:   19, r: 'bayestan', m: 'müssen', t: 'verb', n: 'بایستن' },
  { id:   20, r: 'avval', m: 'erst, erster', t: 'adjective', n: 'اول' },
  { id:   21, r: 'bar', m: 'auf, über', t: 'preposition', n: 'بر' },
  { id:   22, r: 'sal', m: 'Jahr', t: 'noun', n: 'سال' },
  { id:   23, r: 'tavanestan', m: 'können', t: 'verb', n: 'توانستن' },
  { id:   24, r: 'residan', m: 'ankommen, erreichen', t: 'verb', n: 'رسیدن' },
  { id:   25, r: 'pas', m: 'dann, also', t: 'conjunction', n: 'پس' },
  { id:   26, r: 'har', m: 'jeder', t: 'quantifier', n: 'هر' },
  { id:   27, r: 'kar', m: 'Arbeit', t: 'noun', n: 'کار' },
  { id:   28, r: 'bish', m: 'mehr', t: 'adverb', n: 'بیش' },
  { id:   29, r: 'digar', m: 'anderer', t: 'adjective', n: 'دیگر' },
  { id:   30, r: 'ruz', m: 'Tag', t: 'noun', n: 'روز' },
  { id:   31, r: 'amma', m: 'aber', t: 'conjunction', n: 'اما' },
  { id:   32, r: 'ma', m: 'wir', t: 'pronoun', n: 'ما' },
  { id:   33, r: 'keshvar', m: 'Land', t: 'noun', n: 'کشور' },
  { id:   34, r: 'gereftan', m: 'nehmen, ergreifen', t: 'verb', n: 'گرفتن' },
  { id:   35, r: 'pish', m: 'vor, früher', t: 'adjective', n: 'پیش' },
  { id:   36, r: 'ham', m: 'auch, beide', t: 'conjunction', n: 'هم' },
  { id:   37, r: 'goftan', m: 'sagen', t: 'verb', n: 'گفتن' },
  { id:   38, r: 'bozorg', m: 'groß', t: 'adjective', n: 'بزرگ' },
  { id:   39, r: 'do', m: 'zwei', t: 'noun', n: 'دو' },
  { id:   40, r: 'shahr', m: 'Stadt', t: 'noun', n: 'شهر' },
  { id:   41, r: 'ya', m: 'oder', t: 'conjunction', n: 'یا' },
  { id:   42, r: 'dadan', m: 'geben', t: 'verb', n: 'دادن' },
  { id:   43, r: 'iran', m: 'Iran', t: 'proper noun', n: 'ایران' },
  { id:   44, r: 'niz', m: 'auch', t: 'conjunction', n: 'نیز' },
  { id:   45, r: 'miyan', m: 'zwischen', t: 'noun', n: 'میان' },
  { id:   46, r: 'surat', m: 'Gesicht', t: 'noun', n: 'صورت' },
  { id:   47, r: 'rah', m: 'Weg, Straße', t: 'noun', n: 'راه' },
  { id:   48, r: 'dashte', m: 'gehabt', t: 'verb', n: 'داشته' },
  { id:   49, r: 'konad', m: 'macht, tut', t: 'verb', n: 'کند' },
  { id:   50, r: 'dade', m: 'gegeben', t: 'verb', n: 'داده' },
  { id:   51, r: 'besyar', m: 'sehr', t: 'adverb', n: 'بسیار' },
  { id:   52, r: 'ghabl', m: 'vor, vorher', t: 'adjective', n: 'قبل' },
  { id:   53, r: 'moddat', m: 'Zeitraum, Dauer', t: 'noun', n: 'مدت' },
  { id:   54, r: 'u', m: 'er, sie', t: 'pronoun', n: 'او' },
  { id:   55, r: 'nazar', m: 'Meinung', t: 'noun', n: 'نظر' },
  { id:   56, r: 'mardom', m: 'Menschen, Volk', t: 'noun', n: 'مردم' },
  { id:   57, r: 'tanha', m: 'nur, allein', t: 'adverb', n: 'تنها' },
  { id:   58, r: 'hame', m: 'alle', t: 'pronoun', n: 'همه' },
  { id:   59, r: 'mohem', m: 'wichtig', t: 'adjective', n: 'مهم' },
  { id:   60, r: 'kam', m: 'wenig, niedrig', t: 'adjective', n: 'کم' },
  { id:   61, r: 'nazdik', m: 'nah, nächste', t: 'adjective', n: 'نزدیک' },
  { id:   62, r: 'onvan', m: 'Titel', t: 'noun', n: 'عنوان' },
  { id:   63, r: 'mowred', m: 'Fall, Bezug', t: 'noun', n: 'مورد' },
  { id:   64, r: 'beyn', m: 'zwischen', t: 'preposition', n: 'بین' },
  { id:   65, r: 'tamam', m: 'ganz, alle', t: 'adjective', n: 'تمام' },
  { id:   66, r: 'dast', m: 'Hand', t: 'noun', n: 'دست' },
  { id:   67, r: 'chand', m: 'mehrere', t: 'noun', n: 'چند' },
  { id:   68, r: 'gharar', m: 'Vereinbarung', t: 'noun', n: 'قرار' },
  { id:   69, r: 'hamin', m: 'eben dieser', t: 'pronoun', n: 'همین' },
  { id:   70, r: 'goruh', m: 'Gruppe', t: 'noun', n: 'گروه' },
  { id:   71, r: 'barname', m: 'Programm', t: 'noun', n: 'برنامه' },
  { id:   72, r: 'bakhsh', m: 'Abschnitt, Teil', t: 'noun', n: 'بخش' },
  { id:   73, r: 'voyud', m: 'Existenz', t: 'noun', n: 'وجود' },
  { id:   74, r: 'mas\'ale', m: 'Problem, Frage', t: 'noun', n: 'مسئله' },
  { id:   75, r: 'tavayyoh', m: 'Aufmerksamkeit', t: 'noun', n: 'توجه' },
  { id:   76, r: 'amr', m: 'Angelegenheit', t: 'noun', n: 'امر' },
  { id:   77, r: 'agar', m: 'wenn, falls', t: 'conjunction', n: 'اگر' },
  { id:   78, r: 'gozashte', m: 'Vergangenheit', t: 'noun', n: 'گذشته' },
  { id:   79, r: 'mah', m: 'Monat, Mond', t: 'noun', n: 'ماه' },
  { id:   80, r: 'towr', m: 'Art, Weise', t: 'noun', n: 'طور' },
  { id:   81, r: 'bedune', m: 'ohne', t: 'preposition', n: 'بدون' },
  { id:   82, r: 'ru', m: 'auf, Gesicht', t: 'preposition', n: 'رو' },
  { id:   83, r: 'zaman', m: 'Zeit', t: 'noun', n: 'زمان' },
  { id:   84, r: 'hich', m: 'kein, nichts', t: 'quantifier', n: 'هیچ' },
  { id:   85, r: 'moshkel', m: 'Problem, Schwierigkeit', t: 'noun', n: 'مشکل' },
  { id:   86, r: 'eslami', m: 'islamisch', t: 'adjective', n: 'اسلامی' },
  { id:   87, r: 'danestan', m: 'wissen', t: 'verb', n: 'دانستن' },
  { id:   88, r: 'ra\'is', m: 'Leiter, Chef', t: 'noun', n: 'رئیس' },
  { id:   89, r: 'behtar', m: 'besser', t: 'adjective', n: 'بهتر' },
  { id:   90, r: 'dowlat', m: 'Regierung', t: 'noun', n: 'دولت' },
  { id:   91, r: 'yomle', m: 'Satz, Gesamt', t: 'noun', n: 'جمله' },
  { id:   92, r: 'natiye', m: 'Ergebnis', t: 'noun', n: 'نتیجه' },
  { id:   93, r: 'amadan', m: 'kommen', t: 'verb', n: 'آمدن' },
  { id:   94, r: 'su', m: 'Seite, Richtung', t: 'noun', n: 'سو' },
  { id:   95, r: 'ya\'ni', m: 'nämlich, das heißt', t: 'adverb', n: 'یعنی' },
  { id:   96, r: 'bar', m: 'Mal, Last', t: 'noun', n: 'بار' },
  { id:   97, r: 'mantaghe', m: 'Gebiet, Region', t: 'noun', n: 'منطقه' },
  { id:   98, r: 'nafar', m: 'Person', t: 'noun', n: 'نفر' },
  { id:   99, r: 'yaftan', m: 'finden', t: 'verb', n: 'یافتن' },
  { id:  100, r: 'mokhtalef', m: 'verschieden', t: 'adjective', n: 'مختلف' },
  { id:  101, r: 'bala', m: 'oben, hoch', t: 'adjective', n: 'بالا' },
  { id:  102, r: 'man', m: 'ich', t: 'pronoun', n: 'من' },
  { id:  103, r: 'siyasi', m: 'politisch', t: 'adjective', n: 'سیاسی' },
  { id:  104, r: 'yahan', m: 'Welt', t: 'noun', n: 'جهان' },
  { id:  105, r: 'rabete', m: 'Beziehung', t: 'noun', n: 'رابطه' },
  { id:  106, r: 'shart', m: 'Bedingung', t: 'noun', n: 'شرط' },
  { id:  107, r: 'amrika', m: 'Amerika', t: 'proper noun', n: 'آمریکا' },
  { id:  108, r: 'yadid', m: 'neu', t: 'adjective', n: 'جدید' },
  { id:  109, r: 'ali', m: 'Ali', t: 'proper noun', n: 'علی' },
  { id:  110, r: 'che', m: 'was', t: 'pronoun', n: 'چه' },
  { id:  111, r: 'asas', m: 'Grundlage, Basis', t: 'noun', n: 'اساس' },
  { id:  112, r: 'avardan', m: 'bringen', t: 'verb', n: 'آوردن' },
  { id:  113, r: 'hal', m: 'Zustand, Lage', t: 'noun', n: 'حال' },
  { id:  114, r: 'vared', m: 'eintreten', t: 'adjective', n: 'وارد' },
  { id:  115, r: 'neshan dadan', m: 'zeigen', t: 'verb', n: 'نشان دادن' },
  { id:  116, r: 'vey', m: 'er, sie', t: 'pronoun', n: 'وی' },
  { id:  117, r: 'zamine', m: 'Hintergrund, Bereich', t: 'noun', n: 'زمینه' },
  { id:  118, r: 'ba\'d', m: 'danach, dann', t: 'conjunction', n: 'بعد' },
  { id:  119, r: 'sazman', m: 'Organisation', t: 'noun', n: 'سازمان' },
  { id:  120, r: 'fard', m: 'Einzelperson', t: 'noun', n: 'فرد' },
  { id:  121, r: 'tim', m: 'Team', t: 'noun', n: 'تیم' },
  { id:  122, r: 'yavan', m: 'jung', t: 'adjective', n: 'جوان' },
  { id:  123, r: 'melli', m: 'national', t: 'adjective', n: 'ملی' },
  { id:  124, r: 'shura', m: 'Rat', t: 'noun', n: 'شورا' },
  { id:  125, r: 'albatte', m: 'natürlich, selbstverständlich', t: 'adverb', n: 'البته' },
  { id:  126, r: 'dovvom', m: 'zweiter', t: 'adjective', n: 'دوم' },
  { id:  127, r: 'dalil', m: 'Grund, Ursache', t: 'noun', n: 'دلیل' },
  { id:  128, r: 'raftan', m: 'gehen', t: 'verb', n: 'رفتن' },
  { id:  129, r: 'naghsh', m: 'Rolle', t: 'noun', n: 'نقش' },
  { id:  130, r: 'nam', m: 'Name', t: 'noun', n: 'نام' },
  { id:  131, r: 'vali', m: 'aber', t: 'conjunction', n: 'ولی' },
  { id:  132, r: 'dowre', m: 'Periode, Zeitraum', t: 'noun', n: 'دوره' },
  { id:  133, r: 'vazir', m: 'Minister', t: 'noun', n: 'وزیر' },
  { id:  134, r: 'estefade', m: 'Nutzung, Verwendung', t: 'noun', n: 'استفاده' },
  { id:  135, r: 'agha', m: 'Herr', t: 'noun', n: 'آقا' },
  { id:  136, r: 'harekat', m: 'Bewegung', t: 'noun', n: 'حرکت' },
  { id:  137, r: 'gharar gereftan', m: 'sich befinden', t: 'verb', n: 'قرار گرفتن' },
  { id:  138, r: 'sherkat', m: 'Unternehmen, Firma', t: 'noun', n: 'شرکت' },
  { id:  139, r: 'tarh', m: 'Plan, Entwurf', t: 'noun', n: 'طرح' },
  { id:  140, r: 'tehran', m: 'Teheran', t: 'proper noun', n: 'تهران' },
  { id:  141, r: 'barkhi', m: 'manche, einige', t: 'pronoun', n: 'برخی' },
  { id:  142, r: 'se', m: 'drei', t: 'noun', n: 'سه' },
  { id:  143, r: 'darhal', m: 'gerade dabei', t: 'conjunction', n: 'در حال' },
  { id:  144, r: 'hodud', m: 'Grenzen, Bereich', t: 'noun', n: 'حدود' },
  { id:  145, r: 'iyad', m: 'Schöpfung, Entstehung', t: 'noun', n: 'ایجاد' },
  { id:  146, r: 'kas', m: 'Person, jemand', t: 'noun', n: 'کس' },
  { id:  147, r: 'bordan', m: 'mitnehmen', t: 'verb', n: 'بردن' },
  { id:  148, r: 'shoma', m: 'Sie, ihr', t: 'pronoun', n: 'شما' },
  { id:  149, r: 'eghtesadi', m: 'wirtschaftlich', t: 'adjective', n: 'اقتصادی' },
  { id:  150, r: 'hezar', m: 'tausend', t: 'noun', n: 'هزار' },
  { id:  151, r: 'hozur', m: 'Anwesenheit', t: 'noun', n: 'حضور' },
  { id:  152, r: 'niru', m: 'Kraft, Energie', t: 'noun', n: 'نیرو' },
  { id:  153, r: 'ozv', m: 'Mitglied', t: 'noun', n: 'عضو' },
  { id:  154, r: 'fa\'aliyat', m: 'Aktivität', t: 'noun', n: 'فعالیت' },
  { id:  155, r: 'tan', m: 'Körper, Tonne', t: 'noun', n: 'تن' },
  { id:  156, r: 'eshare', m: 'Hinweis, Andeutung', t: 'noun', n: 'اشاره' },
  { id:  157, r: 'chun', m: 'wie, weil', t: 'conjunction', n: 'چون' },
  { id:  158, r: 'hazer', m: 'anwesend, bereit', t: 'adjective', n: 'حاضر' },
  { id:  159, r: 'darsad', m: 'Prozent', t: 'noun', n: 'درصد' },
  { id:  160, r: 'hatta', m: 'sogar', t: 'adverb', n: 'حتی' },
  { id:  161, r: 'mohammad', m: 'Mohammad', t: 'proper noun', n: 'محمد' },
  { id:  162, r: 'voyud dashtan', m: 'existieren', t: 'verb', n: 'وجود داشتن' },
  { id:  163, r: 'payan', m: 'Ende', t: 'noun', n: 'پایان' },
  { id:  164, r: 'hamchenin', m: 'außerdem, ebenfalls', t: 'conjunction', n: 'همچنین' },
  { id:  165, r: 'ghanun', m: 'Gesetz', t: 'noun', n: 'قانون' },
  { id:  166, r: 'ya', m: 'Platz, Ort', t: 'noun', n: 'جا' },
  { id:  167, r: 'momken', m: 'möglich', t: 'adjective', n: 'ممکن' },
  { id:  168, r: 'hadaf', m: 'Ziel', t: 'noun', n: 'هدف' },
  { id:  169, r: 'anyam dadan', m: 'ausführen, erledigen', t: 'verb', n: 'انجام دادن' },
  { id:  170, r: 'bozorgi', m: 'Größe', t: 'noun', n: 'بزرگی' },
  { id:  171, r: 'yame\'e', m: 'Gesellschaft', t: 'noun', n: 'جامعه' },
  { id:  172, r: 'hagh', m: 'Recht', t: 'noun', n: 'حق' },
  { id:  173, r: 'asar', m: 'Wirkung, Einfluss', t: 'noun', n: 'اثر' },
  { id:  174, r: 'bahs', m: 'Diskussion', t: 'noun', n: 'بحث' },
  { id:  175, r: 'arzesh', m: 'Wert', t: 'noun', n: 'ارزش' },
  { id:  176, r: 'mowzu\'', m: 'Thema, Gegenstand', t: 'noun', n: 'موضوع' },
  { id:  177, r: 'taraf', m: 'Seite, Richtung', t: 'noun', n: 'طرف' },
  { id:  178, r: 'na/noh', m: 'nein, neun', t: 'adverb', n: 'نه' },
  { id:  179, r: 'ab', m: 'Wasser', t: 'noun', n: 'آب' },
  { id:  180, r: 'ayande', m: 'Zukunft', t: 'noun', n: 'آینده' },
  { id:  181, r: 'now\'', m: 'Art, Typ', t: 'noun', n: 'نوع' },
  { id:  182, r: 'magham', m: 'Rang, Beamter', t: 'noun', n: 'مقام' },
  { id:  183, r: 'ziyadi', m: 'übermäßig', t: 'adjective', n: 'زیادی' },
  { id:  184, r: 'yahat', m: 'Richtung, Grund', t: 'noun', n: 'جهت' },
  { id:  185, r: 'eyra', m: 'Durchführung, Umsetzung', t: 'noun', n: 'اجرا' },
  { id:  186, r: 'asli', m: 'hauptsächlich', t: 'adjective', n: 'اصلی' },
  { id:  187, r: 'mayles', m: 'Parlament', t: 'noun', n: 'مجلس' },
  { id:  188, r: 'akhar', m: 'letzte, final', t: 'adjective', n: 'آخر' },
  { id:  189, r: 'amal', m: 'Handlung', t: 'noun', n: 'عمل' },
  { id:  190, r: 'zendegi', m: 'Leben', t: 'noun', n: 'زندگی' },
  { id:  191, r: 'chenin', m: 'solch', t: 'adverb', n: 'چنین' },
  { id:  192, r: 'resandan', m: 'liefern, übermitteln', t: 'verb', n: 'رساندن' },
  { id:  193, r: 'nezam', m: 'System, Ordnung', t: 'noun', n: 'نظام' },
  { id:  194, r: 'gozashtan', m: 'legen, lassen', t: 'verb', n: 'گذاشتن' },
  { id:  195, r: 'shekl', m: 'Form, Gestalt', t: 'noun', n: 'شکل' },
  { id:  196, r: 'nesbat', m: 'Verhältnis, Beziehung', t: 'noun', n: 'نسبت' },
  { id:  197, r: 'donya', m: 'Welt', t: 'noun', n: 'دنیا' },
  { id:  198, r: 'khareyi', m: 'ausländisch', t: 'adjective', n: 'خارجی' },
  { id:  199, r: 'hamrah', m: 'zusammen', t: 'adjective', n: 'همراه' },
  { id:  200, r: 'ketab', m: 'Buch', t: 'noun', n: 'کتاب' },
  { id:  201, r: 'emruz', m: 'heute', t: 'adverb', n: 'امروز' },
  { id:  202, r: 'didan', m: 'sehen', t: 'verb', n: 'دیدن' },
  { id:  203, r: 'yahani', m: 'global, weltweit', t: 'adjective', n: 'جهانی' },
  { id:  204, r: 'towse\'e', m: 'Entwicklung', t: 'noun', n: 'توسعه' },
  { id:  205, r: 'vizhe', m: 'besonders, speziell', t: 'adjective', n: 'ویژه' },
  { id:  206, r: 'anyam', m: 'Ausführung, Durchführung', t: 'noun', n: 'انجام' },
  { id:  207, r: 'markaz', m: 'Zentrum', t: 'noun', n: 'مرکز' },
  { id:  208, r: 'e\'lam', m: 'Ankündigung', t: 'noun', n: 'اعلام' },
  { id:  209, r: 'ettela\'', m: 'Information', t: 'noun', n: 'اطلاع' },
  { id:  210, r: 'dakhel', m: 'innen, innerhalb', t: 'noun', n: 'داخل' },
  { id:  211, r: 'pardakhtan', m: 'bezahlen, sich befassen', t: 'verb', n: 'پرداختن' },
  { id:  212, r: 'kamelan', m: 'vollständig', t: 'adverb', n: 'کاملاً' },
  { id:  213, r: 'gofte', m: 'Aussage', t: 'noun', n: 'گفته' },
  { id:  214, r: 'zan', m: 'Frau, Ehefrau', t: 'noun', n: 'زن' },
  { id:  215, r: 'gozaresh', m: 'Bericht', t: 'noun', n: 'گزارش' },
  { id:  216, r: 'sar', m: 'Kopf, Geheimnis', t: 'noun', n: 'سر' },
  { id:  217, r: 'dast dadan', m: 'Händeschütteln, verlieren', t: 'verb', n: 'دست دادن' },
  { id:  218, r: 'hanuz', m: 'noch, immer noch', t: 'adverb', n: 'هنوز' },
  { id:  219, r: 'yomhuri', m: 'Republik', t: 'noun', n: 'جمهوری' },
  { id:  220, r: 'taghyir', m: 'Veränderung', t: 'noun', n: 'تغییر' },
  { id:  221, r: 'te\'dad', m: 'Anzahl', t: 'noun', n: 'تعداد' },
  { id:  222, r: 'milyun', m: 'Million', t: 'noun', n: 'میلیون' },
  { id:  223, r: 'siyasat', m: 'Politik', t: 'noun', n: 'سیاست' },
  { id:  224, r: 'barresi', m: 'Überprüfung', t: 'noun', n: 'بررسی' },
  { id:  225, r: 'eghdam', m: 'Maßnahme', t: 'noun', n: 'اقدام' },
  { id:  226, r: 'afzayesh', m: 'Zunahme, Anstieg', t: 'noun', n: 'افزایش' },
  { id:  227, r: 'barabar', m: 'gleich, gegenüber', t: 'adjective', n: 'برابر' },
  { id:  228, r: 'darbare', m: 'über, bezüglich', t: 'preposition', n: 'درباره' },
  { id:  229, r: 'gune', m: 'Art, Spezies', t: 'noun', n: 'گونه' },
  { id:  230, r: 'sevvom', m: 'dritter', t: 'adjective', n: 'سوم' },
  { id:  231, r: 'khedmat', m: 'Dienst', t: 'noun', n: 'خدمت' },
  { id:  232, r: 'khabar', m: 'Nachricht', t: 'noun', n: 'خبر' },
  { id:  233, r: 'irani', m: 'iranisch', t: 'adjective', n: 'ایرانی' },
  { id:  234, r: 'kamel', m: 'vollständig', t: 'adjective', n: 'کامل' },
  { id:  235, r: 'azad', m: 'frei', t: 'adjective', n: 'آزاد' },
  { id:  236, r: 'manba\'', m: 'Quelle', t: 'noun', n: 'منبع' },
  { id:  237, r: 'khatt', m: 'Linie', t: 'noun', n: 'خط' },
  { id:  238, r: 'ghodrat', m: 'Macht, Stärke', t: 'noun', n: 'قدرت' },
  { id:  239, r: 'niyaz', m: 'Bedarf, Bedürfnis', t: 'noun', n: 'نیاز' },
  { id:  240, r: 'mas\'ul', m: 'verantwortlich', t: 'adjective', n: 'مسئول' },
  { id:  241, r: 'namayande', m: 'Vertreter', t: 'noun', n: 'نماینده' },
  { id:  242, r: 'sa\'at', m: 'Stunde, Uhr', t: 'noun', n: 'ساعت' },
  { id:  243, r: 'zamin', m: 'Boden, Erde', t: 'noun', n: 'زمین' },
  { id:  244, r: 'mellat', m: 'Nation', t: 'noun', n: 'ملت' },
  { id:  245, r: 'mizan', m: 'Rate, Maß', t: 'noun', n: 'میزان' },
  { id:  246, r: 'taht', m: 'unter', t: 'preposition', n: 'تحت' },
  { id:  247, r: 'ekhtiyar', m: 'Autorität, Befugnis', t: 'noun', n: 'اختیار' },
  { id:  248, r: 'nokhost', m: 'zuerst, zunächst', t: 'adverb', n: 'نخست' },
  { id:  249, r: 'era\'e', m: 'Präsentation', t: 'noun', n: 'ارائه' },
  { id:  250, r: 'ba\'es', m: 'Ursache', t: 'noun', n: 'باعث' },
  { id:  251, r: 'roshd', m: 'Wachstum', t: 'noun', n: 'رشد' },
  { id:  252, r: 'dombal', m: 'verfolgen', t: 'noun', n: 'دنبال' },
  { id:  253, r: 'entekhab', m: 'Auswahl, Wahl', t: 'noun', n: 'انتخاب' },
  { id:  254, r: 'goftogu', m: 'Gespräch', t: 'noun', n: 'گفت‌وگو' },
  { id:  255, r: 'movaffagh', m: 'erfolgreich', t: 'adjective', n: 'موفق' },
  { id:  256, r: 'ruzname', m: 'Zeitung', t: 'noun', n: 'روزنامه' },
  { id:  257, r: 'gozashtan', m: 'vergehen, passieren', t: 'verb', n: 'گذشتن' },
  { id:  258, r: 'tey', m: 'während', t: 'preposition', n: 'طی' },
  { id:  259, r: 'khater', m: 'Gedanke, Grund', t: 'noun', n: 'خاطر' },
  { id:  260, r: 'samt', m: 'Seite, Position', t: 'noun', n: 'سمت' },
  { id:  261, r: 'amel', m: 'Faktor, Agent', t: 'noun', n: 'عامل' },
  { id:  262, r: 'ta\'sir', m: 'Einfluss, Wirkung', t: 'noun', n: 'تأثیر' },
  { id:  263, r: 'yang', m: 'Krieg', t: 'noun', n: 'جنگ' },
  { id:  264, r: 'sakht', m: 'Konstruktion, Struktur', t: 'noun', n: 'ساخت' },
  { id:  265, r: 'tarigh', m: 'Weg, Methode', t: 'noun', n: 'طریق' },
  { id:  266, r: 'kahesh', m: 'Rückgang, Abnahme', t: 'noun', n: 'کاهش' },
  { id:  267, r: 'akhir', m: 'jüngst, kürzlich', t: 'adjective', n: 'اخیر' },
  { id:  268, r: 'kharey', m: 'außen, extern', t: 'noun', n: 'خارج' },
  { id:  269, r: 'hafte', m: 'Woche', t: 'noun', n: 'هفته' },
  { id:  270, r: 'aghaz', m: 'Beginn, Anfang', t: 'noun', n: 'آغاز' },
  { id:  271, r: 'marhale', m: 'Phase, Stufe', t: 'noun', n: 'مرحله' },
  { id:  272, r: 'haman', m: 'eben jener', t: 'pronoun', n: 'همان' },
  { id:  273, r: 'san\'at', m: 'Industrie', t: 'noun', n: 'صنعت' },
  { id:  274, r: 'tashkil', m: 'Gründung, Bildung', t: 'noun', n: 'تشکیل' },
  { id:  275, r: 'hamkari', m: 'Zusammenarbeit', t: 'noun', n: 'همکاری' },
  { id:  276, r: 'eslam', m: 'Islam', t: 'noun', n: 'اسلام' },
  { id:  277, r: 'afzudan', m: 'hinzufügen', t: 'verb', n: 'افزودن' },
  { id:  278, r: 'hasan', m: 'Hasan, Tugend', t: 'noun', n: 'حسن' },
  { id:  279, r: 'yafte', m: 'gefunden, Ergebnis', t: 'noun', n: 'یافته' },
  { id:  280, r: 'khandan', m: 'lesen', t: 'verb', n: 'خواندن' },
  { id:  281, r: 'gheyr', m: 'anderer', t: 'noun', n: 'غیر' },
  { id:  282, r: 'khanevade', m: 'Familie', t: 'noun', n: 'خانواده' },
  { id:  283, r: 'dowr', m: 'Periode, weit', t: 'adjective', n: 'دور' },
  { id:  284, r: 'noghte', m: 'Punkt', t: 'noun', n: 'نقطه' },
  { id:  285, r: 'bazi', m: 'Spiel', t: 'noun', n: 'بازی' },
  { id:  286, r: 'towlid', m: 'Produktion', t: 'noun', n: 'تولید' },
  { id:  287, r: 'bargozar', m: 'abgehalten', t: 'adjective', n: 'برگزار' },
  { id:  288, r: 'peyda kardan', m: 'finden', t: 'verb', n: 'پیدا کردن' },
  { id:  289, r: 'vezarat', m: 'Ministerium', t: 'noun', n: 'وزارت' },
  { id:  290, r: 'dide', m: 'Auge, gesehen', t: 'noun', n: 'دیده' },
  { id:  291, r: 'balke', m: 'sondern', t: 'conjunction', n: 'بلکه' },
  { id:  292, r: 'asl', m: 'Prinzip, Grundsatz', t: 'noun', n: 'اصل' },
  { id:  293, r: 'komak', m: 'Hilfe', t: 'noun', n: 'کمک' },
  { id:  294, r: 'ghabel', m: 'fähig', t: 'adjective', n: 'قابل' },
  { id:  295, r: 'tavassot', m: 'durch, mittels', t: 'preposition', n: 'توسط' },
  { id:  296, r: 'zir', m: 'unter', t: 'preposition', n: 'زیر' },
  { id:  297, r: 'manand', m: 'wie, ähnlich wie', t: 'adverb', n: 'مانند' },
  { id:  298, r: 'aknun', m: 'jetzt', t: 'adverb', n: 'اکنون' },
  { id:  299, r: 'ahammiyyat', m: 'Wichtigkeit', t: 'noun', n: 'اهمیت' },
  { id:  300, r: 'andishe', m: 'Gedanke, Idee', t: 'noun', n: 'اندیشه' },
  { id:  301, r: 'ostan', m: 'Provinz', t: 'noun', n: 'استان' },
  { id:  302, r: 'defa\'', m: 'Verteidigung', t: 'noun', n: 'دفاع' },
  { id:  303, r: 'name', m: 'Brief', t: 'noun', n: 'نامه' },
  { id:  304, r: 'ensan', m: 'Mensch', t: 'noun', n: 'انسان' },
  { id:  305, r: 'nemudan', m: 'zeigen, tun', t: 'verb', n: 'نمودن' },
  { id:  306, r: 'omumi', m: 'öffentlich', t: 'adjective', n: 'عمومی' },
  { id:  307, r: 'yeddi', m: 'ernst', t: 'adjective', n: 'جدی' },
  { id:  308, r: 'didar', m: 'Besuch', t: 'noun', n: 'دیدار' },
  { id:  309, r: 'sayer', m: 'andere', t: 'noun', n: 'سایر' },
  { id:  310, r: 'zadan', m: 'schlagen, treffen', t: 'verb', n: 'زدن' },
  { id:  311, r: 'forsat', m: 'Gelegenheit, Chance', t: 'noun', n: 'فرصت' },
  { id:  312, r: 'daneshgah', m: 'Universität', t: 'noun', n: 'دانشگاه' },
  { id:  313, r: 'gharar dadan', m: 'stellen, platzieren', t: 'verb', n: 'قرار دادن' },
  { id:  314, r: 'ta\'kid', m: 'Betonung, Nachdruck', t: 'noun', n: 'تأکید' },
  { id:  315, r: 'neveshtan', m: 'schreiben', t: 'verb', n: 'نوشتن' },
  { id:  316, r: 'sakhtan', m: 'bauen, errichten', t: 'verb', n: 'ساختن' },
  { id:  317, r: 'tartib', m: 'Reihenfolge, Ordnung', t: 'noun', n: 'ترتیب' },
  { id:  318, r: 'faghat', m: 'nur', t: 'adverb', n: 'فقط' },
  { id:  319, r: 'ellat', m: 'Ursache, Grund', t: 'noun', n: 'علت' },
  { id:  320, r: 'dakheli', m: 'intern', t: 'adjective', n: 'داخلی' },
  { id:  321, r: 'azadi', m: 'Freiheit', t: 'noun', n: 'آزادی' },
  { id:  322, r: 'vaz\'iyyat', m: 'Situation, Lage', t: 'noun', n: 'وضعیت' },
  { id:  323, r: 'aya', m: 'ob', t: 'conjunction', n: 'آیا' },
  { id:  324, r: 'yarayan', m: 'Fluss, Strömung', t: 'noun', n: 'جریان' },
  { id:  325, r: 'talash', m: 'Bemühung, Anstrengung', t: 'noun', n: 'تلاش' },
  { id:  326, r: 'lazem', m: 'notwendig', t: 'adjective', n: 'لازم' },
  { id:  327, r: 'hemayat', m: 'Schutz, Unterstützung', t: 'noun', n: 'حمایت' },
  { id:  328, r: 'chiz', m: 'Ding, Sache', t: 'noun', n: 'چیز' },
  { id:  329, r: 'edame', m: 'Fortsetzung', t: 'noun', n: 'ادامه' },
  { id:  330, r: 'dolar', m: 'Dollar', t: 'noun', n: 'دلار' },
  { id:  331, r: 'gharar dashtan', m: 'sich befinden', t: 'verb', n: 'قرار داشتن' },
  { id:  332, r: 'tarikh', m: 'Geschichte, Datum', t: 'noun', n: 'تاریخ' },
  { id:  333, r: 'elmi', m: 'wissenschaftlich', t: 'adjective', n: 'علمی' },
  { id:  334, r: 'sath', m: 'Niveau, Ebene', t: 'noun', n: 'سطح' },
  { id:  335, r: 'eytema\'i', m: 'sozial', t: 'adjective', n: 'اجتماعی' },
  { id:  336, r: 'ostad', m: 'Professor', t: 'noun', n: 'استاد' },
  { id:  337, r: 'entekhabat', m: 'Wahlen', t: 'noun', n: 'انتخابات' },
  { id:  338, r: 'markazi', m: 'zentral', t: 'adjective', n: 'مرکزی' },
  { id:  339, r: 'tasvir', m: 'Bild', t: 'noun', n: 'تصویر' },
  { id:  340, r: 'matrah', m: 'diskutiert, besprochen', t: 'adjective', n: 'مطرح' },
  { id:  341, r: 'ensani', m: 'menschlich', t: 'adjective', n: 'انسانی' },
  { id:  342, r: 'khass', m: 'spezifisch, besonders', t: 'adjective', n: 'خاص' },
  { id:  343, r: 'moghabel', m: 'gegenüber', t: 'preposition', n: 'مقابل' },
  { id:  344, r: 'safar', m: 'Reise', t: 'noun', n: 'سفر' },
  { id:  345, r: 'moshakhkhas', m: 'bestimmt, spezifisch', t: 'adjective', n: 'مشخص' },
  { id:  346, r: 'farhang', m: 'Kultur', t: 'noun', n: 'فرهنگ' },
  { id:  347, r: 'estefade kardan', m: 'benutzen, verwenden', t: 'verb', n: 'استفاده کردن' },
  { id:  348, r: 'enghelab', m: 'Revolution', t: 'noun', n: 'انقلاب' },
  { id:  349, r: 'yam\'', m: 'Summe, Addition', t: 'noun', n: 'جمع' },
  { id:  350, r: 'pishnehad', m: 'Vorschlag', t: 'noun', n: 'پیشنهاد' },
  { id:  351, r: 'made', m: 'weiblich, Materie', t: 'noun', n: 'ماده' },
  { id:  352, r: 'ma\'na', m: 'Bedeutung', t: 'noun', n: 'معنا' },
  { id:  353, r: 'kenar', m: 'neben, bei', t: 'preposition', n: 'کنار' },
  { id:  354, r: 'ra\'y', m: 'Stimme, Wahl', t: 'noun', n: 'رأی' },
  { id:  355, r: 'kolli', m: 'gesamt, allgemein', t: 'adjective', n: 'کلی' },
  { id:  356, r: 'haghighat', m: 'Wahrheit', t: 'noun', n: 'حقیقت' },
  { id:  357, r: 'ta\'min', m: 'Sicherheit', t: 'noun', n: 'تأمین' },
  { id:  358, r: 'khane', m: 'Haus', t: 'noun', n: 'خانه' },
  { id:  359, r: 'yam\'iyyat', m: 'Bevölkerung', t: 'noun', n: 'جمعیت' },
  { id:  360, r: 'din', m: 'Religion', t: 'noun', n: 'دین' },
  { id:  361, r: 'emkan', m: 'Möglichkeit', t: 'noun', n: 'امکان' },
  { id:  362, r: 'elm', m: 'Wissenschaft', t: 'noun', n: 'علم' },
  { id:  363, r: 'entezar', m: 'Warten', t: 'noun', n: 'انتظار' },
  { id:  364, r: 'kutah', m: 'kurz', t: 'adjective', n: 'کوتاه' },
  { id:  365, r: 'bazar', m: 'Markt, Basar', t: 'noun', n: 'بازار' },
  { id:  366, r: 'kol', m: 'ganz, gesamt', t: 'noun', n: 'کل' },
  { id:  367, r: 'meydan', m: 'Platz, Feld', t: 'noun', n: 'میدان' },
  { id:  368, r: 'farhangi', m: 'kulturell, bildend', t: 'adjective', n: 'فرهنگی' },
  { id:  369, r: 'kharey shodan', m: 'verlassen, herausgehen', t: 'verb', n: 'خارج شدن' },
  { id:  370, r: 'sheddat', m: 'Intensität', t: 'noun', n: 'شدت' },
  { id:  371, r: 'hoghugh', m: 'Rechte, Gehalt', t: 'noun', n: 'حقوق' },
  { id:  372, r: 'gol', m: 'Blume, Tor', t: 'noun', n: 'گل' },
  { id:  373, r: 'reshte', m: 'Fachgebiet, Nudeln', t: 'noun', n: 'رشته' },
  { id:  374, r: 'yalase', m: 'Sitzung, Treffen', t: 'noun', n: 'جلسه' },
  { id:  375, r: 'doktor', m: 'Doktor, Arzt', t: 'noun', n: 'دکتر' },
  { id:  376, r: 'so\'al', m: 'Frage', t: 'noun', n: 'سؤال' },
  { id:  377, r: 'faza', m: 'Raum, Weltraum', t: 'noun', n: 'فضا' },
  { id:  378, r: 'film', m: 'Film', t: 'noun', n: 'فیلم' },
  { id:  379, r: 'manzur', m: 'Absicht, Zweck', t: 'noun', n: 'منظور' },
  { id:  380, r: 'daftar', m: 'Büro', t: 'noun', n: 'دفتر' },
  { id:  381, r: 'to', m: 'du, in', t: 'pronoun', n: 'تو' },
  { id:  382, r: 'hey\'at', m: 'Gremium, Ausschuss', t: 'noun', n: 'هیئت' },
  { id:  383, r: 'zaban', m: 'Sprache, Zunge', t: 'noun', n: 'زبان' },
  { id:  384, r: 'mosabeghe', m: 'Wettbewerb', t: 'noun', n: 'مسابقه' },
  { id:  385, r: 'howze', m: 'Bezirk, Bereich', t: 'noun', n: 'حوزه' },
  { id:  386, r: 'chera', m: 'warum', t: 'adverb', n: 'چرا' },
  { id:  387, r: 'kheyli', m: 'sehr', t: 'adverb', n: 'خیلی' },
  { id:  388, r: 'daghighe', m: 'Minute', t: 'noun', n: 'دقیقه' },
  { id:  389, r: 'faranse', m: 'Frankreich, Französisch', t: 'proper noun', n: 'فرانسه' },
  { id:  390, r: 'bayan', m: 'Ausdruck', t: 'noun', n: 'بیان' },
  { id:  391, r: 'vahed', m: 'Einheit', t: 'noun', n: 'واحد' },
  { id:  392, r: 'kari', m: 'aktiv, arbeitend', t: 'adjective', n: 'کاری' },
  { id:  393, r: 'marg', m: 'Tod', t: 'noun', n: 'مرگ' },
  { id:  394, r: 'sokhan', m: 'Rede, Sprache', t: 'noun', n: 'سخن' },
  { id:  395, r: 'edame dadan', m: 'fortsetzen', t: 'verb', n: 'ادامه دادن' },
  { id:  396, r: 'zamani', m: 'zeitlich', t: 'adjective', n: 'زمانی' },
  { id:  397, r: 'ertebat', m: 'Verbindung, Kontakt', t: 'noun', n: 'ارتباط' },
  { id:  398, r: 'movafegh', m: 'zustimmend', t: 'adjective', n: 'موافق' },
  { id:  399, r: 'shahid', m: 'Märtyrer', t: 'noun', n: 'شهید' },
  { id:  400, r: 'shahed', m: 'Zeuge', t: 'noun', n: 'شاهد' },
  { id:  401, r: 'hadd', m: 'Grenze, Limit', t: 'noun', n: 'حد' },
  { id:  402, r: 'omid', m: 'Hoffnung', t: 'noun', n: 'امید' },
  { id:  403, r: 'ravesh', m: 'Methode, Weise', t: 'noun', n: 'روش' },
  { id:  404, r: 'amniyat', m: 'Sicherheit', t: 'noun', n: 'امنیت' },
  { id:  405, r: 'gharar budan', m: 'sollen, vorgesehen sein', t: 'verb', n: 'قرار بودن' },
  { id:  406, r: 'naft', m: 'Öl, Petroleum', t: 'noun', n: 'نفت' },
  { id:  407, r: 'dowran', m: 'Periode, Umlauf', t: 'noun', n: 'دوران' },
  { id:  408, r: 'chap', m: 'Druck', t: 'noun', n: 'چاپ' },
  { id:  409, r: 'shabake', m: 'Netzwerk', t: 'noun', n: 'شبکه' },
  { id:  410, r: 'vaght', m: 'Zeit', t: 'noun', n: 'وقت' },
  { id:  411, r: 'vaghti', m: 'wenn, als', t: 'conjunction', n: 'وقتی' },
  { id:  412, r: 'hezb', m: 'Partei', t: 'noun', n: 'حزب' },
  { id:  413, r: 'mane\'', m: 'Hindernis', t: 'noun', n: 'مانع' },
  { id:  414, r: 'fasl', m: 'Jahreszeit, Kapitel', t: 'noun', n: 'فصل' },
  { id:  415, r: 'neshan', m: 'Zeichen', t: 'noun', n: 'نشان' },
  { id:  416, r: 'monaseb', m: 'geeignet, angemessen', t: 'adjective', n: 'مناسب' },
  { id:  417, r: 'shab', m: 'Nacht', t: 'noun', n: 'شب' },
  { id:  418, r: 'ravand', m: 'Prozess, Verlauf', t: 'noun', n: 'روند' },
  { id:  419, r: 'madrese', m: 'Schule', t: 'noun', n: 'مدرسه' },
  { id:  420, r: 'hakem', m: 'Herrscher', t: 'noun', n: 'حاکم' },
  { id:  421, r: 'amade', m: 'bereit', t: 'adjective', n: 'آماده' },
  { id:  422, r: 'pul', m: 'Geld', t: 'noun', n: 'پول' },
  { id:  423, r: 'pasokh', m: 'Antwort', t: 'noun', n: 'پاسخ' },
  { id:  424, r: 'ishan', m: 'sie (höflich)', t: 'pronoun', n: 'ایشان' },
  { id:  425, r: 'milyard', m: 'Milliarde', t: 'noun', n: 'میلیارد' },
  { id:  426, r: 'masir', m: 'Route, Strecke', t: 'noun', n: 'مسیر' },
  { id:  427, r: 'vaghe\'iyyat', m: 'Realität, Wirklichkeit', t: 'noun', n: 'واقعیت' },
  { id:  428, r: 'mowyud', m: 'verfügbar, Lebewesen', t: 'adjective', n: 'موجود' },
  { id:  429, r: 'feshar', m: 'Druck', t: 'noun', n: 'فشار' },
  { id:  430, r: 'dastur', m: 'Anweisung, Befehl', t: 'noun', n: 'دستور' },
  { id:  431, r: 'eslah', m: 'Korrektur', t: 'noun', n: 'اصلاح' },
  { id:  432, r: 'kuchak', m: 'klein', t: 'adjective', n: 'کوچک' },
  { id:  433, r: 'afghanestan', m: 'Afghanistan', t: 'proper noun', n: 'افغانستان' },
  { id:  434, r: 'peyda', m: 'finden', t: 'adjective', n: 'پیدا' },
  { id:  435, r: 'tulani', m: 'lang', t: 'adjective', n: 'طولانی' },
  { id:  436, r: 'sa\'y', m: 'versuchen', t: 'noun', n: 'سعی' },
  { id:  437, r: 'shoru\'', m: 'Beginn, Start', t: 'noun', n: 'شروع' },
  { id:  438, r: 'chahar', m: 'vier', t: 'noun', n: 'چهار' },
  { id:  439, r: 'pardakht', m: 'Zahlung', t: 'noun', n: 'پرداخت' },
  { id:  440, r: 'tul', m: 'Länge', t: 'noun', n: 'طول' },
  { id:  441, r: 'mo\'taghed', m: 'überzeugt', t: 'adjective', n: 'معتقد' },
  { id:  442, r: 'hefz', m: 'Bewahrung', t: 'noun', n: 'حفظ' },
  { id:  443, r: 'chaharom', m: 'vierter', t: 'adjective', n: 'چهارم' },
  { id:  444, r: 'moshtarak', m: 'gemeinsam, Abonnent', t: 'adjective', n: 'مشترک' },
  { id:  445, r: 'khubi', m: 'Güte', t: 'noun', n: 'خوبی' },
  { id:  446, r: 'ziyad', m: 'viel', t: 'adverb', n: 'زیاد' },
  { id:  447, r: 'hadese', m: 'Unfall, Vorfall', t: 'noun', n: 'حادثه' },
  { id:  448, r: 'mahal', m: 'Ort, Stelle', t: 'noun', n: 'محل' },
  { id:  449, r: 'mostaghim', m: 'direkt', t: 'adjective', n: 'مستقیم' },
  { id:  450, r: 'orupa', m: 'Europa', t: 'proper noun', n: 'اروپا' },
  { id:  451, r: 'arse', m: 'Gebiet, Arena', t: 'noun', n: 'عرصه' },
  { id:  452, r: 'amrikayi', m: 'amerikanisch', t: 'adjective', n: 'آمریکایی' },
  { id:  453, r: 'mali', m: 'finanziell', t: 'adjective', n: 'مالی' },
  { id:  454, r: 'yoz', m: 'außer', t: 'conjunction', n: 'جز' },
  { id:  455, r: 'taze', m: 'frisch, neu', t: 'adjective', n: 'تازه' },
  { id:  456, r: 'sakhte', m: 'hergestellt', t: 'adjective', n: 'ساخته' },
  { id:  457, r: 'maghale', m: 'Artikel', t: 'noun', n: 'مقاله' },
  { id:  458, r: 'chin', m: 'China', t: 'proper noun', n: 'چین' },
  { id:  459, r: 'mard', m: 'Mann', t: 'noun', n: 'مرد' },
  { id:  460, r: 'emam', m: 'Imam', t: 'noun', n: 'امام' },
  { id:  461, r: 'vaghe\'i', m: 'real, wirklich', t: 'adjective', n: 'واقعی' },
  { id:  462, r: 'anyam shodan', m: 'erledigt werden', t: 'verb', n: 'انجام شدن' },
  { id:  463, r: 'vaz\'', m: 'Situation, Zustand', t: 'noun', n: 'وضع' },
  { id:  464, r: 'dastgah', m: 'Maschine, System', t: 'noun', n: 'دستگاه' },
  { id:  465, r: 'sistem', m: 'System', t: 'noun', n: 'سیستم' },
  { id:  466, r: 'dini', m: 'religiös', t: 'adjective', n: 'دینی' },
  { id:  467, r: 'kudak', m: 'Kind', t: 'noun', n: 'کودک' },
  { id:  468, r: 'ebteda', m: 'Anfang, Beginn', t: 'adverb', n: 'ابتدا' },
  { id:  469, r: 'khast', m: 'Wunsch, wollte', t: 'verb', n: 'خواست' },
  { id:  470, r: 'dowlati', m: 'staatlich, regierungsseitig', t: 'adjective', n: 'دولتی' },
  { id:  471, r: 'rasmi', m: 'offiziell', t: 'adjective', n: 'رسمی' },
  { id:  472, r: 'hazine', m: 'Kosten', t: 'noun', n: 'هزینه' },
  { id:  473, r: 'bank', m: 'Bank', t: 'noun', n: 'بانک' },
  { id:  474, r: 'hava', m: 'Luft, Wetter', t: 'noun', n: 'هوا' },
  { id:  475, r: 'fekr', m: 'Gedanke', t: 'noun', n: 'فکر' },
  { id:  476, r: 'shambe', m: 'Samstag', t: 'noun', n: 'شنبه' },
  { id:  477, r: 'enteghal', m: 'Transfer, Übertragung', t: 'noun', n: 'انتقال' },
  { id:  478, r: 'engelisi', m: 'Englisch', t: 'adjective', n: 'انگلیسی' },
  { id:  479, r: 'tahghigh', m: 'Forschung', t: 'noun', n: 'تحقیق' },
  { id:  480, r: 'pey', m: 'Grundlage', t: 'noun', n: 'پی' },
  { id:  481, r: 'dah', m: 'zehn, Ortschaft', t: 'noun', n: 'ده' },
  { id:  482, r: 'muyeb', m: 'Ursache, Grund', t: 'noun', n: 'موجب' },
  { id:  483, r: 'sangin', m: 'schwer', t: 'adjective', n: 'سنگین' },
  { id:  484, r: 'edare', m: 'Büro, Verwaltung', t: 'noun', n: 'اداره' },
  { id:  485, r: 'khatar', m: 'Gefahr, Risiko', t: 'noun', n: 'خطر' },
  { id:  486, r: 'nezami', m: 'militärisch', t: 'adjective', n: 'نظامی' },
  { id:  487, r: 'naghl', m: 'Transport, Erzählung', t: 'noun', n: 'نقل' },
  { id:  488, r: 'shadid', m: 'schwer, heftig', t: 'adjective', n: 'شدید' },
  { id:  489, r: 'marbut', m: 'verwandt, zugehörig', t: 'adjective', n: 'مربوط' },
  { id:  490, r: 'futbal', m: 'Fußball', t: 'noun', n: 'فوتبال' },
  { id:  491, r: 'vaghe\'', m: 'gelegen, befindlich', t: 'adjective', n: 'واقع' },
  { id:  492, r: 'kafi', m: 'ausreichend, genug', t: 'adjective', n: 'کافی' },
  { id:  493, r: 'amuzesh', m: 'Unterricht, Ausbildung', t: 'noun', n: 'آموزش' },
  { id:  494, r: 'shayastan', m: 'möglich sein', t: 'verb', n: 'شایستن' },
  { id:  495, r: 'kontrol', m: 'Kontrolle', t: 'noun', n: 'کنترل' },
  { id:  496, r: 'dust', m: 'Freund', t: 'noun', n: 'دوست' },
  { id:  497, r: 'taknun', m: 'bisher, noch', t: 'adverb', n: 'تاکنون' },
  { id:  498, r: 'entekhab kardan', m: 'wählen', t: 'verb', n: 'انتخاب کردن' },
  { id:  499, r: 'dahe', m: 'Jahrzehnt', t: 'noun', n: 'دهه' },
  { id:  500, r: 'saheb', m: 'Besitzer, Herr', t: 'noun', n: 'صاحب' },
  { id:  501, r: 'neshast', m: 'Sitzung, saß', t: 'noun', n: 'نشست' },
  { id:  502, r: 'negah', m: 'Blick, Schauen', t: 'noun', n: 'نگاه' },
  { id:  503, r: 'mo\'aven', m: 'Stellvertreter', t: 'noun', n: 'معاون' },
  { id:  504, r: 'khosus', m: 'Bezug, Hinsicht', t: 'noun', n: 'خصوص' },
  { id:  505, r: 'mandan', m: 'bleiben', t: 'verb', n: 'ماندن' },
  { id:  506, r: 'bargh', m: 'Strom, Blitz', t: 'noun', n: 'برق' },
  { id:  507, r: 'mobareze', m: 'Kampf, Widerstand', t: 'noun', n: 'مبارزه' },
  { id:  508, r: 'mo\'assese', m: 'Gründung, Institution', t: 'noun', n: 'مؤسسه' },
  { id:  509, r: 'nemune', m: 'Muster, Beispiel', t: 'noun', n: 'نمونه' },
  { id:  510, r: 'khub', m: 'gut', t: 'adjective', n: 'خوب' },
  { id:  511, r: 'asr', m: 'Nachmittag, Zeitalter', t: 'noun', n: 'عصر' },
  { id:  512, r: 'pany', m: 'fünf', t: 'noun', n: 'پنج' },
  { id:  513, r: 'hamishe', m: 'immer', t: 'adverb', n: 'همیشه' },
  { id:  514, r: 'baz', m: 'offen, wieder', t: 'adverb', n: 'باز' },
  { id:  515, r: 'movaffaghiyat', m: 'Erfolg', t: 'noun', n: 'موفقیت' },
  { id:  516, r: 'anche', m: 'dasjenige was', t: 'pronoun', n: 'آنچه' },
  { id:  517, r: 'masraf', m: 'Verbrauch, Konsum', t: 'noun', n: 'مصرف' },
  { id:  518, r: 'eragh', m: 'Irak', t: 'proper noun', n: 'عراق' },
  { id:  519, r: 'kasb', m: 'Erwerb, Geschäft', t: 'noun', n: 'کسب' },
  { id:  520, r: 'amar', m: 'Statistik', t: 'noun', n: 'آمار' },
  { id:  521, r: 'daneshyu', m: 'Student', t: 'noun', n: 'دانشجو' },
  { id:  522, r: 'neveshte', m: 'Schrift, Geschriebenes', t: 'noun', n: 'نوشته' },
  { id:  523, r: 'riyasat', m: 'Präsidentschaft', t: 'noun', n: 'ریاست' },
  { id:  524, r: 'rahbar', m: 'Anführer, Führer', t: 'noun', n: 'رهبر' },
  { id:  525, r: 'dara', m: 'besitzend, habend', t: 'adjective', n: 'دارا' },
  { id:  526, r: 'tasmim', m: 'Entscheidung', t: 'noun', n: 'تصمیم' },
  { id:  527, r: 'farzand', m: 'Kind, Nachkomme', t: 'noun', n: 'فرزند' },
  { id:  528, r: 'tayrobe', m: 'Erfahrung', t: 'noun', n: 'تجربه' },
  { id:  529, r: 'asiya', m: 'Asien', t: 'proper noun', n: 'آسیا' },
  { id:  530, r: 'gheymat', m: 'Preis', t: 'noun', n: 'قیمت' },
  { id:  531, r: 'rokh', m: 'Gesicht', t: 'noun', n: 'رخ' },
  { id:  532, r: 'tahavvol', m: 'Entwicklung, Wandel', t: 'noun', n: 'تحول' },
  { id:  533, r: 'reghabat', m: 'Wettbewerb', t: 'noun', n: 'رقابت' },
  { id:  534, r: 'hamle', m: 'Angriff', t: 'noun', n: 'حمله' },
  { id:  535, r: 'shomar', m: 'Anzahl, Zahl', t: 'noun', n: 'شمار' },
  { id:  536, r: 'fasele', m: 'Abstand, Entfernung', t: 'noun', n: 'فاصله' },
  { id:  537, r: 'eghtesad', m: 'Wirtschaft', t: 'noun', n: 'اقتصاد' },
  { id:  538, r: 'hokumat', m: 'Regierung', t: 'noun', n: 'حکومت' },
  { id:  539, r: 'naghshe', m: 'Karte, Plan', t: 'noun', n: 'نقشه' },
  { id:  540, r: 'hamvare', m: 'stets, immer', t: 'adverb', n: 'همواره' },
  { id:  541, r: 'gharb', m: 'Westen', t: 'noun', n: 'غرب' },
  { id:  542, r: 'gostaresh', m: 'Ausbreitung', t: 'noun', n: 'گسترش' },
  { id:  543, r: 'hall', m: 'Lösung', t: 'noun', n: 'حل' },
  { id:  544, r: 'rowshan', m: 'hell, eingeschaltet', t: 'adjective', n: 'روشن' },
  { id:  545, r: 'gam', m: 'Schritt', t: 'noun', n: 'گام' },
  { id:  546, r: 'khoda', m: 'Gott', t: 'noun', n: 'خدا' },
  { id:  547, r: 'ehsas', m: 'Gefühl', t: 'noun', n: 'احساس' },
  { id:  548, r: 'sale', m: 'Jahre alt', t: 'noun', n: 'ساله' },
  { id:  549, r: 'gharardad', m: 'Vertrag', t: 'noun', n: 'قرارداد' },
  { id:  550, r: 'marz', m: 'Grenze', t: 'noun', n: 'مرز' },
  { id:  551, r: 'khak', m: 'Erde, Staub', t: 'noun', n: 'خاک' },
  { id:  552, r: 'yom\'e', m: 'Freitag', t: 'noun', n: 'جمعه' },
  { id:  553, r: 'amaliyat', m: 'Kampagne, Einsatz', t: 'noun', n: 'عملیات' },
  { id:  554, r: 'saranyam', m: 'schließlich, endlich', t: 'adverb', n: 'سرانجام' },
  { id:  555, r: 'moarrefi', m: 'Vorstellung, Einführung', t: 'noun', n: 'معرفی' },
  { id:  556, r: 'sabab', m: 'Ursache, Grund', t: 'noun', n: 'سبب' },
  { id:  557, r: 'ohde', m: 'Verantwortung', t: 'noun', n: 'عهده' },
  { id:  558, r: 'zira', m: 'weil', t: 'conjunction', n: 'زیرا' },
  { id:  559, r: 'zemn', m: 'innerhalb, während', t: 'preposition', n: 'ضمن' },
  { id:  560, r: 'sahne', m: 'Bühne, Szene', t: 'noun', n: 'صحنه' },
  { id:  561, r: 'khareye', m: 'ausländisch', t: 'adjective', n: 'خارجه' },
  { id:  562, r: 'seda', m: 'Stimme, Ton', t: 'noun', n: 'صدا' },
  { id:  563, r: 'ba\'zi', m: 'manche, einige', t: 'pronoun', n: 'بعضی' },
  { id:  564, r: 'marasem', m: 'Zeremonie', t: 'noun', n: 'مراسم' },
  { id:  565, r: 'daryaft', m: 'Empfang, Erhalt', t: 'noun', n: 'دریافت' },
  { id:  566, r: 'khun', m: 'Blut', t: 'noun', n: 'خون' },
  { id:  567, r: 'moghaddame', m: 'Einleitung, Vorwort', t: 'noun', n: 'مقدمه' },
  { id:  568, r: 'rusiye', m: 'Russland', t: 'proper noun', n: 'روسیه' },
  { id:  569, r: 'esteghlal', m: 'Unabhängigkeit', t: 'noun', n: 'استقلال' },
  { id:  570, r: 'mesl', m: 'wie, Sprichwort', t: 'adverb', n: 'مثل' },
  { id:  571, r: 'sakht', m: 'hart, schwer', t: 'adjective', n: 'سخت' },
  { id:  572, r: 'bargozari', m: 'Abhaltung', t: 'noun', n: 'برگزاری' },
  { id:  573, r: 'daste', m: 'Bündel, Gruppe', t: 'noun', n: 'دسته' },
  { id:  574, r: 'atash', m: 'Feuer', t: 'noun', n: 'آتش' },
  { id:  575, r: 'sor\'at', m: 'Geschwindigkeit', t: 'noun', n: 'سرعت' },
  { id:  576, r: 'beynolmelali', m: 'international', t: 'adjective', n: 'بین‌المللی' },
  { id:  577, r: 'mosharekat', m: 'Partnerschaft, Beteiligung', t: 'noun', n: 'مشارکت' },
  { id:  578, r: 'vazife', m: 'Pflicht, Aufgabe', t: 'noun', n: 'وظیفه' },
  { id:  579, r: 'fa\'al', m: 'aktiv', t: 'adjective', n: 'فعال' },
  { id:  580, r: 'ragham', m: 'Ziffer, Zahl', t: 'noun', n: 'رقم' },
  { id:  581, r: 'nime', m: 'Hälfte', t: 'noun', n: 'نیمه' },
  { id:  582, r: 'shomal', m: 'Norden', t: 'noun', n: 'شمال' },
  { id:  583, r: 'yad', m: 'Erinnerung', t: 'noun', n: 'یاد' },
  { id:  584, r: 'bahar', m: 'Frühling', t: 'noun', n: 'بهار' },
  { id:  585, r: 'bardashtan', m: 'aufheben, wegnehmen', t: 'verb', n: 'برداشتن' },
  { id:  586, r: 'sari\'', m: 'schnell', t: 'adjective', n: 'سریع' },
  { id:  587, r: 'chehre', m: 'Gesicht', t: 'noun', n: 'چهره' },
  { id:  588, r: 'mahsul', m: 'Produkt', t: 'noun', n: 'محصول' },
  { id:  589, r: 'tarikhi', m: 'historisch', t: 'adjective', n: 'تاریخی' },
  { id:  590, r: 'chashm', m: 'Auge', t: 'noun', n: 'چشم' },
  { id:  591, r: 'band', m: 'Schnur, Absatz', t: 'noun', n: 'بند' },
  { id:  592, r: 'mokhalef', m: 'entgegen, ablehnend', t: 'adjective', n: 'مخالف' },
  { id:  593, r: 'bist', m: 'zwanzig', t: 'noun', n: 'بیست' },
  { id:  594, r: 'alman', m: 'Deutschland', t: 'proper noun', n: 'آلمان' },
  { id:  595, r: 'taghviyat', m: 'Stärkung', t: 'noun', n: 'تقویت' },
  { id:  596, r: 'ehtemal', m: 'Wahrscheinlichkeit', t: 'noun', n: 'احتمال' },
  { id:  597, r: 'ta\'yin', m: 'Bestimmung', t: 'noun', n: 'تعیین' },
  { id:  598, r: 'polis', m: 'Polizei', t: 'noun', n: 'پلیس' },
  { id:  599, r: 'forush', m: 'Verkauf', t: 'noun', n: 'فروش' },
  { id:  600, r: 'resane', m: 'Medium, Medien', t: 'noun', n: 'رسانه' },
  { id:  601, r: 'yonub', m: 'Süden', t: 'noun', n: 'جنوب' },
  { id:  602, r: 'tahiyye', m: 'Vorbereitung', t: 'noun', n: 'تهیه' },
  { id:  603, r: 'bimari', m: 'Krankheit', t: 'noun', n: 'بیماری' },
  { id:  604, r: 'gardidan', m: 'sich drehen, werden', t: 'verb', n: 'گردیدن' },
  { id:  605, r: 'sarf', m: 'Ausgaben, rein', t: 'noun', n: 'صرف' },
  { id:  606, r: 'maymu\'e', m: 'Sammlung', t: 'noun', n: 'مجموعه' },
  { id:  607, r: 'namayesh', m: 'Ausstellung, Vorführung', t: 'noun', n: 'نمایش' },
  { id:  608, r: 'asasi', m: 'grundlegend', t: 'adjective', n: 'اساسی' },
  { id:  609, r: 'ghabli', m: 'vorherig', t: 'adjective', n: 'قبلی' },
  { id:  610, r: 'paye', m: 'Basis, Grundlage', t: 'noun', n: 'پایه' },
  { id:  611, r: 'engelis', m: 'England, Großbritannien', t: 'proper noun', n: 'انگلیس' },
  { id:  612, r: 'mowghe\'iyyat', m: 'Situation, Position', t: 'noun', n: 'موقعیت' },
  { id:  613, r: 'mehr', m: 'Sonne, Zuneigung', t: 'noun', n: 'مهر' },
  { id:  614, r: 'amal kardan', m: 'handeln, ausführen', t: 'verb', n: 'عمل کردن' },
  { id:  615, r: 'yaygah', m: 'Position, Stellung', t: 'noun', n: 'جایگاه' },
  { id:  616, r: 'e\'teghad', m: 'Glaube, Überzeugung', t: 'noun', n: 'اعتقاد' },
  { id:  617, r: 'she\'r', m: 'Poesie, Gedicht', t: 'noun', n: 'شعر' },
  { id:  618, r: 'now', m: 'neu', t: 'adjective', n: 'نو' },
  { id:  619, r: 'ehteram', m: 'Respekt, Achtung', t: 'noun', n: 'احترام' },
  { id:  620, r: 'metr', m: 'Meter', t: 'noun', n: 'متر' },
  { id:  621, r: 'torkiye', m: 'Türkei', t: 'proper noun', n: 'ترکیه' },
  { id:  622, r: 'piruzi', m: 'Sieg', t: 'noun', n: 'پیروزی' },
  { id:  623, r: 'ekhtelaf', m: 'Unterschied', t: 'noun', n: 'اختلاف' },
  { id:  624, r: 'mahsub', m: 'gerechnet, betrachtet', t: 'adjective', n: 'محسوب' },
  { id:  625, r: 'darya', m: 'Meer', t: 'noun', n: 'دریا' },
  { id:  626, r: 'hazrat', m: 'Heiligkeit', t: 'noun', n: 'حضرت' },
  { id:  627, r: 'bana', m: 'Gebäude', t: 'noun', n: 'بنا' },
  { id:  628, r: 'pa', m: 'Fuß, Bein', t: 'noun', n: 'پا' },
  { id:  629, r: 'khabarnegar', m: 'Reporter, Journalist', t: 'noun', n: 'خبرنگار' },
  { id:  630, r: 'gharbi', m: 'westlich', t: 'adjective', n: 'غربی' },
  { id:  631, r: 'chandin', m: 'mehrere', t: 'noun', n: 'چندین' },
  { id:  632, r: 'vorud', m: 'Eingang, Einreise', t: 'noun', n: 'ورود' },
  { id:  633, r: 'yan', m: 'Leben, Seele', t: 'noun', n: 'جان' },
  { id:  634, r: 'parvaz', m: 'Flug', t: 'noun', n: 'پرواز' },
  { id:  635, r: 'aleyh', m: 'gegen', t: 'preposition', n: 'علیه' },
  { id:  636, r: 'pishraft', m: 'Fortschritt', t: 'noun', n: 'پیشرفت' },
  { id:  637, r: 'ebraz', m: 'Ausdruck', t: 'noun', n: 'ابراز' },
  { id:  638, r: 'tavan', m: 'Fähigkeit, Können', t: 'noun', n: 'توان' },
  { id:  639, r: 'halat', m: 'Zustand, Verfassung', t: 'noun', n: 'حالت' },
  { id:  640, r: 'faraham', m: 'verfügbar, bereit', t: 'noun', n: 'فراهم' },
  { id:  641, r: 'barkhord', m: 'Zusammenstoß, Kollision', t: 'noun', n: 'برخورد' },
  { id:  642, r: 'raftar', m: 'Verhalten', t: 'noun', n: 'رفتار' },
  { id:  643, r: 'nokte', m: 'Punkt, Hinweis', t: 'noun', n: 'نکته' },
  { id:  644, r: 'yelowgiri', m: 'Verhinderung, Prävention', t: 'noun', n: 'جلوگیری' },
  { id:  645, r: 'sabegh', m: 'ehemals, früher', t: 'adjective', n: 'سابق' },
  { id:  646, r: 'guya', m: 'anscheinend, klar', t: 'adverb', n: 'گویا' },
  { id:  647, r: 'mottaham', m: 'Beschuldigter, Angeklagter', t: 'noun', n: 'متهم' },
  { id:  648, r: 'ta\'sis', m: 'Gründung', t: 'noun', n: 'تأسیس' },
  { id:  649, r: 'sal budan', m: 'Jahre sein', t: 'verb', n: 'سال بودن' },
  { id:  650, r: 'tahaghghogh', m: 'Verwirklichung', t: 'noun', n: 'تحقق' },
  { id:  651, r: 'ghanuni', m: 'legal, gesetzlich', t: 'adjective', n: 'قانونی' },
  { id:  652, r: 'edde\'a', m: 'Behauptung', t: 'noun', n: 'ادعا' },
  { id:  653, r: 'didgah', m: 'Standpunkt, Sichtweise', t: 'noun', n: 'دیدگاه' },
  { id:  654, r: 'makan', m: 'Ort, Platz', t: 'noun', n: 'مکان' },
  { id:  655, r: 'matlab', m: 'Thema, Inhalt', t: 'noun', n: 'مطلب' },
  { id:  656, r: 'emsal', m: 'dieses Jahr', t: 'adverb', n: 'امسال' },
  { id:  657, r: 'daramad', m: 'Einkommen', t: 'noun', n: 'درآمد' },
  { id:  658, r: 'gashtan', m: 'sich drehen, streifen', t: 'verb', n: 'گشتن' },
  { id:  659, r: 'hamchun', m: 'wie, ähnlich', t: 'adverb', n: 'همچون' },
  { id:  660, r: 'eyn', m: 'dasselbe, Original', t: 'noun', n: 'عین' },
  { id:  661, r: 'karshenas', m: 'Experte, Fachmann', t: 'noun', n: 'کارشناس' },
  { id:  662, r: 'honar', m: 'Kunst', t: 'noun', n: 'هنر' },
  { id:  663, r: 'hamchenan', m: 'weiterhin, ebenso', t: 'adverb', n: 'همچنان' },
  { id:  664, r: 'shamel', m: 'einschließlich', t: 'adjective', n: 'شامل' },
  { id:  665, r: 'rusta', m: 'Dorf', t: 'noun', n: 'روستا' },
  { id:  666, r: 'rahbari', m: 'Führung', t: 'noun', n: 'رهبری' },
  { id:  667, r: 'zarfiyat', m: 'Kapazität', t: 'noun', n: 'ظرفیت' },
  { id:  668, r: 'nezarat', m: 'Aufsicht, Kontrolle', t: 'noun', n: 'نظارت' },
  { id:  669, r: 'tabi\'i', m: 'natürlich', t: 'adjective', n: 'طبیعی' },
  { id:  670, r: 'aghaz shodan', m: 'beginnen', t: 'verb', n: 'آغاز شدن' },
  { id:  671, r: 'san\'ati', m: 'industriell', t: 'adjective', n: 'صنعتی' },
  { id:  672, r: 'hengam', m: 'Zeit, Moment', t: 'noun', n: 'هنگام' },
  { id:  673, r: 'mosbat', m: 'positiv', t: 'adjective', n: 'مثبت' },
  { id:  674, r: 'yekdigar', m: 'einander', t: 'pronoun', n: 'یکدیگر' },
  { id:  675, r: 'porozhe', m: 'Projekt', t: 'noun', n: 'پروژه' },
  { id:  676, r: 'khalaf', m: 'entgegen, gegen', t: 'conjunction', n: 'خلاف' },
  { id:  677, r: 'sheykh', m: 'Scheich', t: 'noun', n: 'شیخ' },
  { id:  678, r: 'senn', m: 'Alter', t: 'noun', n: 'سن' },
  { id:  679, r: 'hokm', m: 'Urteil, Befehl', t: 'noun', n: 'حکم' },
  { id:  680, r: 'tasvib', m: 'Genehmigung, Billigung', t: 'noun', n: 'تصویب' },
  { id:  681, r: 'shakhsiyyat', m: 'Persönlichkeit, Charakter', t: 'noun', n: 'شخصیت' },
  { id:  682, r: 'kodam', m: 'welcher', t: 'noun', n: 'کدام' },
  { id:  683, r: 'sarzamin', m: 'Land, Gebiet', t: 'noun', n: 'سرزمین' },
  { id:  684, r: 'mosalman', m: 'muslimisch', t: 'adjective', n: 'مسلمان' },
  { id:  685, r: 'saz', m: 'Instrument', t: 'noun', n: 'ساز' },
  { id:  686, r: 'khordan', m: 'essen', t: 'verb', n: 'خوردن' },
  { id:  687, r: 'mas\'uliyyat', m: 'Verantwortung', t: 'noun', n: 'مسئولیت' },
  { id:  688, r: 'yam', m: 'Becher, Pokal', t: 'noun', n: 'جام' },
  { id:  689, r: 'paziroftan', m: 'akzeptieren', t: 'verb', n: 'پذیرفتن' },
  { id:  690, r: 'obur', m: 'Durchgang, Überquerung', t: 'noun', n: 'عبور' },
  { id:  691, r: 'seyyed', m: 'Nachkomme des Propheten', t: 'noun', n: 'سید' },
  { id:  692, r: 'payam', m: 'Nachricht, Botschaft', t: 'noun', n: 'پیام' },
  { id:  693, r: 'khosusi', m: 'privat', t: 'adjective', n: 'خصوصی' },
  { id:  694, r: 'haddeaghal', m: 'mindestens, Minimum', t: 'adverb', n: 'حداقل' },
  { id:  695, r: 'harche', m: 'was auch immer', t: 'adverb', n: 'هرچه' },
  { id:  696, r: 'vabaste', m: 'abhängig', t: 'adjective', n: 'وابسته' },
  { id:  697, r: 'da\'vat', m: 'Einladung', t: 'noun', n: 'دعوت' },
  { id:  698, r: 'tark', m: 'verlassen, Türke', t: 'noun', n: 'ترک' },
  { id:  699, r: 'konferans', m: 'Konferenz', t: 'noun', n: 'کنفرانس' },
  { id:  700, r: 'namayeshgah', m: 'Ausstellung', t: 'noun', n: 'نمایشگاه' },
  { id:  701, r: 'tekrar', m: 'Wiederholung', t: 'noun', n: 'تکرار' },
  { id:  702, r: 'baste', m: 'Paket, geschlossen', t: 'noun', n: 'بسته' },
  { id:  703, r: 'amalkard', m: 'Leistung, Betrieb', t: 'noun', n: 'عملکرد' },
  { id:  704, r: 'rishe', m: 'Wurzel', t: 'noun', n: 'ریشه' },
  { id:  705, r: 'shenakhtan', m: 'kennen, erkennen', t: 'verb', n: 'شناختن' },
  { id:  706, r: 'sarmaye', m: 'Kapital', t: 'noun', n: 'سرمایه' },
  { id:  707, r: 'gah', m: 'manchmal, Zeitpunkt', t: 'adverb', n: 'گاه' },
  { id:  708, r: 'modir', m: 'Manager, Direktor', t: 'noun', n: 'مدیر' },
  { id:  709, r: 'sahm', m: 'Anteil, Los', t: 'noun', n: 'سهم' },
  { id:  710, r: 'sarnevesht', m: 'Schicksal', t: 'noun', n: 'سرنوشت' },
  { id:  711, r: 'komite', m: 'Komitee', t: 'noun', n: 'کمیته' },
  { id:  712, r: 'hend', m: 'Indien', t: 'proper noun', n: 'هند' },
  { id:  713, r: 'e\'lam kardan', m: 'ankündigen', t: 'verb', n: 'اعلام کردن' },
  { id:  714, r: 'bakhshidan', m: 'vergeben, schenken', t: 'verb', n: 'بخشیدن' },
  { id:  715, r: 'modiriyyat', m: 'Management, Verwaltung', t: 'noun', n: 'مدیریت' },
  { id:  716, r: 'edde', m: 'Anzahl', t: 'noun', n: 'عده' },
  { id:  717, r: 'mote\'assefane', m: 'leider, bedauerlicherweise', t: 'adverb', n: 'متأسفانه' },
  { id:  718, r: 'hesab', m: 'Konto, Rechnung', t: 'noun', n: 'حساب' },
  { id:  719, r: 'fekr kardan', m: 'denken', t: 'verb', n: 'فکر کردن' },
  { id:  720, r: 'surati', m: 'rosa, eine Form', t: 'adjective', n: 'صورتی' },
  { id:  721, r: 'kala', m: 'Waren, Güter', t: 'noun', n: 'کالا' },
  { id:  722, r: 'tebgh', m: 'gemäß, laut', t: 'preposition', n: 'طبق' },
  { id:  723, r: 'molaheze', m: 'Beobachtung', t: 'noun', n: 'ملاحظه' },
  { id:  724, r: 'faravan', m: 'reichlich, viel', t: 'adverb', n: 'فراوان' },
  { id:  725, r: 'pichide', m: 'komplex, kompliziert', t: 'adjective', n: 'پیچیده' },
  { id:  726, r: 'ezhar', m: 'Aussage, Erklärung', t: 'noun', n: 'اظهار' },
  { id:  727, r: 'neyat', m: 'Rettung', t: 'noun', n: 'نجات' },
  { id:  728, r: 'gaz', m: 'Gas', t: 'noun', n: 'گاز' },
  { id:  729, r: 'shive', m: 'Methode, Stil', t: 'noun', n: 'شیوه' },
  { id:  730, r: 'abbas', m: 'Abbas', t: 'proper noun', n: 'عباس' },
  { id:  731, r: 'ali', m: 'hoch, ausgezeichnet', t: 'adjective', n: 'عالی' },
  { id:  732, r: 'ba\'di', m: 'nächster', t: 'adjective', n: 'بعدی' },
  { id:  733, r: 'zendan', m: 'Gefängnis', t: 'noun', n: 'زندان' },
  { id:  734, r: 'moshahede', m: 'Beobachtung', t: 'noun', n: 'مشاهده' },
  { id:  735, r: 'dadgah', m: 'Gericht', t: 'noun', n: 'دادگاه' },
  { id:  736, r: 'mo\'arrefi kardan', m: 'vorstellen', t: 'verb', n: 'معرفی کردن' },
  { id:  737, r: 'nerkh', m: 'Rate, Tarif', t: 'noun', n: 'نرخ' },
  { id:  738, r: 'konande', m: 'Ausführende, Täter', t: 'noun', n: 'کننده' },
  { id:  739, r: 'zarurat', m: 'Notwendigkeit', t: 'noun', n: 'ضرورت' },
  { id:  740, r: 'shesh', m: 'sechs, Lunge', t: 'noun', n: 'شش' },
  { id:  741, r: 'maybur', m: 'gezwungen', t: 'adjective', n: 'مجبور' },
  { id:  742, r: 'aks', m: 'Foto, Bild', t: 'noun', n: 'عکس' },
  { id:  743, r: 'tardid', m: 'Zögern, Zweifel', t: 'noun', n: 'تردید' },
  { id:  744, r: 'khabari', m: 'Nachrichten-', t: 'adjective', n: 'خبری' },
  { id:  745, r: 'behbud', m: 'Verbesserung', t: 'noun', n: 'بهبود' },
  { id:  746, r: 'neshane', m: 'Zeichen, Hinweis', t: 'noun', n: 'نشانه' },
  { id:  747, r: 'rezhim', m: 'Regime', t: 'noun', n: 'رژیم' },
  { id:  748, r: 'owy', m: 'Höhepunkt, Gipfel', t: 'noun', n: 'اوج' },
  { id:  749, r: 'manfa\'at', m: 'Gewinn, Nutzen', t: 'noun', n: 'منفعت' },
  { id:  750, r: 'monyar', m: 'führend zu', t: 'adjective', n: 'منجر' },
  { id:  751, r: 'nahad', m: 'Institution', t: 'noun', n: 'نهاد' },
  { id:  752, r: 'keshandan', m: 'ziehen, schleppen', t: 'verb', n: 'کشاندن' },
  { id:  753, r: 'sabeghe', m: 'Präzedenzfall', t: 'noun', n: 'سابقه' },
  { id:  754, r: 'sepas', m: 'dann, danach', t: 'conjunction', n: 'سپس' },
  { id:  755, r: 'nim', m: 'halb', t: 'noun', n: 'نیم' },
  { id:  756, r: 'darkhast', m: 'Anfrage, Antrag', t: 'noun', n: 'درخواست' },
  { id:  757, r: 'radd', m: 'Ablehnung, Spur', t: 'noun', n: 'رد' },
  { id:  758, r: 'manzel', m: 'Haus, Wohnung', t: 'noun', n: 'منزل' },
  { id:  759, r: 'parvande', m: 'Akte, Dossier', t: 'noun', n: 'پرونده' },
  { id:  760, r: 'hala', m: 'jetzt, gerade', t: 'adverb', n: 'حالا' },
  { id:  761, r: 'konuni', m: 'gegenwärtig, aktuell', t: 'adjective', n: 'کنونی' },
  { id:  762, r: 'vazn', m: 'Gewicht', t: 'noun', n: 'وزن' },
  { id:  763, r: 'tuman', m: 'Toman (Währung)', t: 'noun', n: 'تومان' },
  { id:  764, r: 'adam', m: 'Fehlen, Mangel', t: 'noun', n: 'عدم' },
  { id:  765, r: 'ettefagh oftadan', m: 'passieren, stattfinden', t: 'verb', n: 'اتفاق افتادن' },
  { id:  766, r: 'budye', m: 'Budget', t: 'noun', n: 'بودجه' },
  { id:  767, r: 'ekhtesas', m: 'Zuteilung, Zuweisung', t: 'noun', n: 'اختصاص' },
  { id:  768, r: 'mota\'added', m: 'zahlreich, mehrfach', t: 'adjective', n: 'متعدد' },
  { id:  769, r: 'si', m: 'dreißig', t: 'noun', n: 'سی' },
  { id:  770, r: 'ahl', m: 'einheimisch, zugehörig', t: 'noun', n: 'اهل' },
  { id:  771, r: 'hedayat', m: 'Führung, Leitung', t: 'noun', n: 'هدایت' },
  { id:  772, r: 'sanad', m: 'Dokument, Urkunde', t: 'noun', n: 'سند' },
  { id:  773, r: 'sad', m: 'hundert', t: 'noun', n: 'صد' },
  { id:  774, r: 'neshastan', m: 'sitzen', t: 'verb', n: 'نشستن' },
  { id:  775, r: 'anya', m: 'dort', t: 'adverb', n: 'آنجا' },
  { id:  776, r: 'taslim', m: 'Kapitulation, Übergabe', t: 'noun', n: 'تسلیم' },
  { id:  777, r: 'taghriban', m: 'ungefähr, etwa', t: 'adverb', n: 'تقریباً' },
  { id:  778, r: 'vared shodan', m: 'eintreten, betreten', t: 'verb', n: 'وارد شدن' },
  { id:  779, r: 'tarrahi', m: 'Design, Gestaltung', t: 'noun', n: 'طراحی' },
  { id:  780, r: 'danesh', m: 'Wissen', t: 'noun', n: 'دانش' },
  { id:  781, r: 'alave', m: 'Zusatz, Ergänzung', t: 'noun', n: 'علاوه' },
  { id:  782, r: 'rahi', m: 'unterwegs nach, ein Weg', t: 'adjective', n: 'راهی' },
  { id:  783, r: 'enerzhi', m: 'Energie', t: 'noun', n: 'انرژی' },
  { id:  784, r: 'ghaleb', m: 'Modell, Rahmen', t: 'noun', n: 'قالب' },
  { id:  785, r: 'yomhur', m: 'Republik', t: 'noun', n: 'جمهور' },
  { id:  786, r: 'keshidan', m: 'ziehen, zeichnen', t: 'verb', n: 'کشیدن' },
  { id:  787, r: 'bavar', m: 'Glaube, Überzeugung', t: 'noun', n: 'باور' },
  { id:  788, r: 'masyed', m: 'Moschee', t: 'noun', n: 'مسجد' },
  { id:  789, r: 'doshman', m: 'Feind', t: 'noun', n: 'دشمن' },
  { id:  790, r: 'payin', m: 'unten, nach unten', t: 'adverb', n: 'پایین' },
  { id:  791, r: 'nashi', m: 'resultierend', t: 'adjective', n: 'ناشی' },
  { id:  792, r: 'ruberu', m: 'gegenüber', t: 'adjective', n: 'روبرو' },
  { id:  793, r: 'daghigh', m: 'genau, präzise', t: 'adjective', n: 'دقیق' },
  { id:  794, r: 'pakhsh', m: 'Verteilung, Sendung', t: 'noun', n: 'پخش' },
  { id:  795, r: 'mahmud', m: 'Mahmoud', t: 'proper noun', n: 'محمود' },
  { id:  796, r: 'khiyaban', m: 'Straße', t: 'noun', n: 'خیابان' },
  { id:  797, r: 'sakhteman', m: 'Gebäude', t: 'noun', n: 'ساختمان' },
  { id:  798, r: 'mohaghghegh', m: 'Gelehrter, ermittelt', t: 'noun', n: 'محقق' },
  { id:  799, r: 'saken', m: 'Bewohner, ansässig', t: 'adjective', n: 'ساکن' },
  { id:  800, r: 'shakhs', m: 'Person', t: 'noun', n: 'شخص' },
  { id:  801, r: 'komisiyon', m: 'Kommission', t: 'noun', n: 'کمیسیون' },
  { id:  802, r: 'khaste', m: 'Forderung', t: 'noun', n: 'خواسته' },
  { id:  803, r: 'tabdil', m: 'Umwandlung, Konvertierung', t: 'noun', n: 'تبدیل' },
  { id:  804, r: 'emtiyaz', m: 'Punkt, Privileg', t: 'noun', n: 'امتیاز' },
  { id:  805, r: 'lahaz', m: 'Hinsicht, Perspektive', t: 'noun', n: 'لحاظ' },
  { id:  806, r: 'shargh', m: 'Osten', t: 'noun', n: 'شرق' },
  { id:  807, r: 'vasile', m: 'Mittel, Werkzeug', t: 'noun', n: 'وسیله' },
  { id:  808, r: 'nasl', m: 'Generation', t: 'noun', n: 'نسل' },
  { id:  809, r: 'ghesmat', m: 'Abschnitt, Teil', t: 'noun', n: 'قسمت' },
  { id:  810, r: 'sarasar', m: 'überall, durch und durch', t: 'noun', n: 'سراسر' },
  { id:  811, r: 'e\'tebar', m: 'Kredit, Gültigkeit', t: 'noun', n: 'اعتبار' },
  { id:  812, r: 'gostarde', m: 'weitverbreitet', t: 'adjective', n: 'گسترده' },
  { id:  813, r: 'dobare', m: 'wieder, erneut', t: 'adverb', n: 'دوباره' },
  { id:  814, r: 'yadde', m: 'Straße, Weg', t: 'noun', n: 'جاده' },
  { id:  815, r: 'fars', m: 'Fars', t: 'proper noun', n: 'فارس' },
  { id:  816, r: 'salegi', m: 'Jahre alt', t: 'noun', n: 'سالگی' },
  { id:  817, r: 'eshtebah', m: 'Fehler, Irrtum', t: 'noun', n: 'اشتباه' },
  { id:  818, r: 'chegune', m: 'wie, auf welche Weise', t: 'adverb', n: 'چگونه' },
  { id:  819, r: 'koshte', m: 'getötet, kultiviert', t: 'adjective', n: 'کشته' },
  { id:  820, r: 'motafavet', m: 'unterschiedlich, verschieden', t: 'adjective', n: 'متفاوت' },
  { id:  821, r: 'inya', m: 'hier', t: 'adverb', n: 'اینجا' },
  { id:  822, r: 'barkhordar budan', m: 'besitzen, haben', t: 'verb', n: 'برخوردار بودن' },
  { id:  823, r: 'keshti', m: 'Schiff, Ringen', t: 'noun', n: 'کشتی' },
  { id:  824, r: 'yonubi', m: 'südlich', t: 'adjective', n: 'جنوبی' },
  { id:  825, r: 'boruz', m: 'Erscheinen, Auftreten', t: 'noun', n: 'بروز' },
  { id:  826, r: 'keshavarzi', m: 'Landwirtschaft', t: 'noun', n: 'کشاورزی' },
  { id:  827, r: 'enteghad', m: 'Kritik', t: 'noun', n: 'انتقاد' },
  { id:  828, r: 'shenakhte', m: 'bekannt', t: 'adjective', n: 'شناخته' },
  { id:  829, r: 'ta\'rif', m: 'Definition, Beschreibung', t: 'noun', n: 'تعریف' },
  { id:  830, r: 'bazikon', m: 'Spieler', t: 'noun', n: 'بازیکن' },
  { id:  831, r: 'post', m: 'Post, Stelle', t: 'noun', n: 'پست' },
  { id:  832, r: 'zendegi kardan', m: 'leben', t: 'verb', n: 'زندگی کردن' },
  { id:  833, r: 'baghi', m: 'verbleibend, übrig', t: 'adjective', n: 'باقی' },
  { id:  834, r: 'hoseyn', m: 'Hossein', t: 'proper noun', n: 'حسین' },
  { id:  835, r: 'yam\'i', m: 'kollektiv, gemeinschaftlich', t: 'adjective', n: 'جمعی' },
  { id:  836, r: 'moghayese', m: 'Vergleich', t: 'noun', n: 'مقایسه' },
  { id:  837, r: 'zamini', m: 'Land-, irdisch', t: 'adjective', n: 'زمینی' },
  { id:  838, r: 'eyaze dadan', m: 'erlauben, gestatten', t: 'verb', n: 'اجازه دادن' },
  { id:  839, r: 'paziresh', m: 'Empfang, Aufnahme', t: 'noun', n: 'پذیرش' },
  { id:  840, r: 'darman', m: 'Behandlung', t: 'noun', n: 'درمان' },
  { id:  841, r: 'kar kardan', m: 'arbeiten', t: 'verb', n: 'کار کردن' },
  { id:  842, r: 'yalb', m: 'Anziehung', t: 'noun', n: 'جلب' },
  { id:  843, r: 'mahrum', m: 'benachteiligt, gesperrt', t: 'adjective', n: 'محروم' },
  { id:  844, r: 'saderat', m: 'Exporte', t: 'noun', n: 'صادرات' },
  { id:  845, r: 'pakestan', m: 'Pakistan', t: 'proper noun', n: 'پاکستان' },
  { id:  846, r: 'ghazayi', m: 'Justiz-', t: 'adjective', n: 'قضایی' },
  { id:  847, r: 'pezeshki', m: 'medizinisch', t: 'adjective', n: 'پزشکی' },
  { id:  848, r: 'alem', m: 'Gelehrter, Welt', t: 'noun', n: 'عالم' },
  { id:  849, r: 'amuzeshi', m: 'pädagogisch, lehrend', t: 'adjective', n: 'آموزشی' },
  { id:  850, r: 'oftadan', m: 'fallen', t: 'verb', n: 'افتادن' },
  { id:  851, r: 'bardasht', m: 'Ernte, Abhebung, Verständnis', t: 'noun', n: 'برداشت' },
  { id:  852, r: 'nevisande', m: 'Schriftsteller, Autor', t: 'noun', n: 'نویسنده' },
  { id:  853, r: 'haft', m: 'sieben', t: 'noun', n: 'هفت' },
  { id:  854, r: 'teyarat', m: 'Handel', t: 'noun', n: 'تجارت' },
  { id:  855, r: 'kharid', m: 'Kauf', t: 'noun', n: 'خرید' },
  { id:  856, r: 'suriye', m: 'Syrien', t: 'proper noun', n: 'سوریه' },
  { id:  857, r: 'dochar', m: 'betroffen von', t: 'adjective', n: 'دچار' },
  { id:  858, r: 'fardi', m: 'individuell, persönlich', t: 'adjective', n: 'فردی' },
  { id:  859, r: 'dokhtar', m: 'Mädchen, Tochter', t: 'noun', n: 'دختر' },
  { id:  860, r: 'nahayi', m: 'endgültig, abschließend', t: 'adjective', n: 'نهایی' },
  { id:  861, r: 'komak kardan', m: 'helfen', t: 'verb', n: 'کمک کردن' },
  { id:  862, r: 'ahmad', m: 'Ahmad', t: 'proper noun', n: 'احمد' },
  { id:  863, r: 'ersal', m: 'Versand, Sendung', t: 'noun', n: 'ارسال' },
  { id:  864, r: 'abzar', m: 'Werkzeug, Hilfsmittel', t: 'noun', n: 'ابزار' },
  { id:  865, r: 'harchand', m: 'jedoch, obwohl', t: 'conjunction', n: 'هرچند' },
  { id:  866, r: 'banabarin', m: 'deshalb, daher', t: 'conjunction', n: 'بنابراین' },
  { id:  867, r: 'zhapon', m: 'Japan', t: 'proper noun', n: 'ژاپن' },
  { id:  868, r: 'harf', m: 'Buchstabe, Gespräch', t: 'noun', n: 'حرف' },
  { id:  869, r: 'dastan', m: 'Geschichte, Erzählung', t: 'noun', n: 'داستان' },
  { id:  870, r: 'khanom', m: 'Dame, Frau', t: 'noun', n: 'خانم' },
  { id:  871, r: 'ghorbani', m: 'Opfer', t: 'noun', n: 'قربانی' },
  { id:  872, r: 'ma\'dan', m: 'Bergwerk, Mine', t: 'noun', n: 'معدن' },
  { id:  873, r: 'mosafer', m: 'Reisende, Passagier', t: 'noun', n: 'مسافر' },
  { id:  874, r: 'ghovve', m: 'Stärke, Kraft', t: 'noun', n: 'قوه' },
  { id:  875, r: 'ziba', m: 'schön', t: 'adjective', n: 'زیبا' },
  { id:  876, r: 'mashghul', m: 'beschäftigt', t: 'adjective', n: 'مشغول' },
  { id:  877, r: 'hasel', m: 'Ergebnis, Ertrag', t: 'noun', n: 'حاصل' },
  { id:  878, r: 'ettefagh', m: 'Ereignis, Vorfall', t: 'noun', n: 'اتفاق' },
  { id:  879, r: 'andaze', m: 'Größe, Ausmaß', t: 'noun', n: 'اندازه' },
  { id:  880, r: 'varzeshi', m: 'sportlich', t: 'adjective', n: 'ورزشی' },
  { id:  881, r: 'baes shodan', m: 'verursachen', t: 'verb', n: 'باعث شدن' },
  { id:  882, r: 'eyaze', m: 'Erlaubnis', t: 'noun', n: 'اجازه' },
  { id:  883, r: 'pedar', m: 'Vater', t: 'noun', n: 'پدر' },
  { id:  884, r: 'bazgasht', m: 'Rückkehr', t: 'noun', n: 'بازگشت' },
  { id:  885, r: 'par', m: 'Feder, voll', t: 'adjective', n: 'پر' },
  { id:  886, r: 'motale\'e', m: 'Studie, Lektüre', t: 'noun', n: 'مطالعه' },
  { id:  887, r: 'artesh', m: 'Armee, Streitkräfte', t: 'noun', n: 'ارتش' },
  { id:  888, r: 'za\'f', m: 'Schwäche', t: 'noun', n: 'ضعف' },
  { id:  889, r: 'eftekhar', m: 'Ehre, Stolz', t: 'noun', n: 'افتخار' },
  { id:  890, r: 'amadegi', m: 'Bereitschaft, Kindergarten', t: 'noun', n: 'آمادگی' },
  { id:  891, r: 'namzad', m: 'Kandidat', t: 'noun', n: 'نامزد' },
  { id:  892, r: 'vizhegi', m: 'Merkmal, Eigenschaft', t: 'noun', n: 'ویژگی' },
  { id:  893, r: 'televiziyon', m: 'Fernsehen', t: 'noun', n: 'تلویزیون' },
  { id:  894, r: 'shi\'e', m: 'schiitisch', t: 'adjective', n: 'شیعه' },
  { id:  895, r: 'khastar', m: 'Antragsteller, begehrend', t: 'noun', n: 'خواستار' },
  { id:  896, r: 'mazhabi', m: 'religiös', t: 'adjective', n: 'مذهبی' },
  { id:  897, r: 'miladi', m: 'n. Chr., nach Christus', t: 'adjective', n: 'میلادی' },
  { id:  898, r: 'monasebat', m: 'Angemessenheit, Gelegenheit', t: 'noun', n: 'مناسبت' },
  { id:  899, r: 'mohtaram', m: 'ehrwürdig, geachtet', t: 'adjective', n: 'محترم' },
  { id:  900, r: 'karkhane', m: 'Fabrik', t: 'noun', n: 'کارخانه' },
  { id:  901, r: 'movafeghat', m: 'Zustimmung, Einverständnis', t: 'noun', n: 'موافقت' },
  { id:  902, r: 'maymu\'', m: 'Gesamtsumme', t: 'noun', n: 'مجموع' },
  { id:  903, r: 'koshtan', m: 'töten', t: 'verb', n: 'کشتن' },
  { id:  904, r: 'mahalli', m: 'lokal, örtlich', t: 'adjective', n: 'محلی' },
  { id:  905, r: 'adi', m: 'normal, gewöhnlich', t: 'adjective', n: 'عادی' },
  { id:  906, r: 'ettehadiye', m: 'Gewerkschaft, Union', t: 'noun', n: 'اتحادیه' },
  { id:  907, r: 'ghadimi', m: 'alt, altmodisch', t: 'adjective', n: 'قدیمی' },
  { id:  908, r: 'vahdat', m: 'Einheit, Einigkeit', t: 'noun', n: 'وحدت' },
  { id:  909, r: 'bohran', m: 'Krise', t: 'noun', n: 'بحران' },
  { id:  910, r: 'del', m: 'Herz', t: 'noun', n: 'دل' },
  { id:  911, r: 'farmande', m: 'Kommandant', t: 'noun', n: 'فرمانده' },
  { id:  912, r: 'sonnat', m: 'Tradition', t: 'noun', n: 'سنت' },
  { id:  913, r: 'esra\'il', m: 'Israel', t: 'proper noun', n: 'اسرائیل' },
  { id:  914, r: 'orupayi', m: 'europäisch', t: 'adjective', n: 'اروپایی' },
  { id:  915, r: 'mande', m: 'abgestanden, Restbetrag', t: 'adjective', n: 'مانده' },
  { id:  916, r: 'edalat', m: 'Gerechtigkeit', t: 'noun', n: 'عدالت' },
  { id:  917, r: 'sarmayegozari', m: 'Investition', t: 'noun', n: 'سرمایه‌گذاری' },
  { id:  918, r: 'sobh', m: 'Morgen', t: 'noun', n: 'صبح' },
  { id:  919, r: 'sokhanrani', m: 'Rede, Vortrag', t: 'noun', n: 'سخنرانی' },
  { id:  920, r: 'bashgah', m: 'Klub, Verein', t: 'noun', n: 'باشگاه' },
  { id:  921, r: 'kashf', m: 'Entdeckung', t: 'noun', n: 'کشف' },
  { id:  922, r: 'tabdil shodan', m: 'umwandeln', t: 'verb', n: 'تبدیل شدن' },
  { id:  923, r: 'ghahremani', m: 'Heldentum, Meisterschaft', t: 'noun', n: 'قهرمانی' },
  { id:  924, r: 'yashnvare', m: 'Festival', t: 'noun', n: 'جشنواره' },
  { id:  925, r: 'sud', m: 'Gewinn, Profit', t: 'noun', n: 'سود' },
  { id:  926, r: 'shomali', m: 'nördlich', t: 'adjective', n: 'شمالی' },
  { id:  927, r: 'tahdid', m: 'Drohung', t: 'noun', n: 'تهدید' },
  { id:  928, r: 'sade', m: 'einfach, schlicht', t: 'adjective', n: 'ساده' },
  { id:  929, r: 'ghader', m: 'fähig, imstande', t: 'adjective', n: 'قادر' },
  { id:  930, r: 'madar', m: 'Mutter', t: 'noun', n: 'مادر' },
  { id:  931, r: 'farar', m: 'Flucht', t: 'noun', n: 'فرار' },
  { id:  932, r: 'zende', m: 'lebendig, lebend', t: 'adjective', n: 'زنده' },
  { id:  933, r: 'ghatl', m: 'Tötung, Mord', t: 'noun', n: 'قتل' },
  { id:  934, r: 'salem', m: 'gesund', t: 'adjective', n: 'سالم' },
  { id:  935, r: 'sabt', m: 'Registrierung', t: 'noun', n: 'ثبت' },
  { id:  936, r: 'shahrvand', m: 'Bürger', t: 'noun', n: 'شهروند' },
  { id:  937, r: 'solh', m: 'Frieden', t: 'noun', n: 'صلح' },
  { id:  938, r: 'tala', m: 'Gold', t: 'noun', n: 'طلا' },
  { id:  939, r: 'havayi', m: 'Luft-, Flug-', t: 'adjective', n: 'هوایی' },
  { id:  940, r: 'diruz', m: 'gestern', t: 'adverb', n: 'دیروز' },
  { id:  941, r: 'sa\'y kardan', m: 'versuchen', t: 'verb', n: 'سعی کردن' },
  { id:  942, r: 'arab', m: 'Araber', t: 'noun', n: 'عرب' },
  { id:  943, r: 'yari', m: 'fließend, laufend, aktuell', t: 'adjective', n: 'جاری' },
  { id:  944, r: 'hoviyyat', m: 'Identität', t: 'noun', n: 'هویت' },
  { id:  945, r: 'badan', m: 'Körper', t: 'noun', n: 'بدن' },
  { id:  946, r: 'selah', m: 'Waffe', t: 'noun', n: 'سلاح' },
  { id:  947, r: 'daneshmand', m: 'Wissenschaftler, Forscher', t: 'noun', n: 'دانشمند' },
  { id:  948, r: 'bedin', m: 'zu diesem, so viel', t: 'adverb', n: 'بدین' },
  { id:  949, r: 'manfi', m: 'negativ', t: 'adjective', n: 'منفی' },
  { id:  950, r: 'darun', m: 'innen, innerhalb', t: 'preposition', n: 'درون' },
  { id:  951, r: 'rang', m: 'Farbe', t: 'noun', n: 'رنگ' },
  { id:  952, r: 'faransavi', m: 'Französisch', t: 'adjective', n: 'فرانسوی' },
  { id:  953, r: 'keyfiyyat', m: 'Qualität', t: 'noun', n: 'کیفیت' },
  { id:  954, r: 'eyrayi', m: 'ausführend, exekutiv', t: 'adjective', n: 'اجرایی' },
  { id:  955, r: 'khoshunat', m: 'Gewalt', t: 'noun', n: 'خشونت' },
  { id:  956, r: 'mabni', m: 'basierend', t: 'adjective', n: 'مبنی' },
  { id:  957, r: 'shomare', m: 'Nummer, Zahl', t: 'noun', n: 'شماره' },
  { id:  958, r: 'posht', m: 'Rücken, hinter', t: 'noun', n: 'پشت' },
  { id:  959, r: 'amali', m: 'praktisch', t: 'adjective', n: 'عملی' },
  { id:  960, r: 'mozakerat', m: 'Verhandlungen', t: 'noun', n: 'مذاکرات' },
  { id:  961, r: 'varzesh', m: 'Sport', t: 'noun', n: 'ورزش' },
  { id:  962, r: 'yaleb', m: 'interessant, attraktiv', t: 'adjective', n: 'جالب' },
  { id:  963, r: 'mowze\'', m: 'Position, Standpunkt', t: 'noun', n: 'موضع' },
  { id:  964, r: 'ezafe', m: 'Zusatz, Ergänzung', t: 'adjective', n: 'اضافه' },
  { id:  965, r: 'dastgir', m: 'verhaftet', t: 'adjective', n: 'دستگیر' },
  { id:  966, r: 'motevayyeh', m: 'bewusst, bemerkt', t: 'adjective', n: 'متوجه' },
  { id:  967, r: 'farmudan', m: 'befehlen, geruhen', t: 'verb', n: 'فرمودن' },
  { id:  968, r: 'ebarat', m: 'Ausdruck, Phrase', t: 'noun', n: 'عبارت' },
  { id:  969, r: 'arzyabi', m: 'Bewertung, Einschätzung', t: 'noun', n: 'ارزیابی' },
  { id:  970, r: 'tasavvor', m: 'Vorstellung, Fantasie', t: 'noun', n: 'تصور' },
  { id:  971, r: 'sha\'er', m: 'Dichter', t: 'noun', n: 'شاعر' },
  { id:  972, r: 'e\'temad', m: 'Vertrauen', t: 'noun', n: 'اعتماد' },
  { id:  973, r: 'aramesh', m: 'Ruhe, Gelassenheit', t: 'noun', n: 'آرامش' },
  { id:  974, r: 'naf\'', m: 'Gewinn, Vorteil', t: 'noun', n: 'نفع' },
  { id:  975, r: 'faghr', m: 'Armut', t: 'noun', n: 'فقر' },
  { id:  976, r: 'hamkar', m: 'Kollege, Mitarbeiter', t: 'noun', n: 'همکار' },
  { id:  977, r: 'owlavviyat', m: 'Priorität', t: 'noun', n: 'اولویت' },
  { id:  978, r: 'motekhasses', m: 'Experte, Spezialist', t: 'noun', n: 'متخصص' },
  { id:  979, r: 'sandugh', m: 'Fonds, Kiste', t: 'noun', n: 'صندوق' },
  { id:  980, r: 'moshabeh', m: 'ähnlich', t: 'adjective', n: 'مشابه' },
  { id:  981, r: 'farsi', m: 'Persisch, Farsi', t: 'adjective', n: 'فارسی' },
  { id:  982, r: 'nazdiki', m: 'Nähe', t: 'noun', n: 'نزدیکی' },
  { id:  983, r: 'rezayat', m: 'Zufriedenheit', t: 'noun', n: 'رضایت' },
  { id:  984, r: 'negarani', m: 'Sorge, Besorgnis', t: 'noun', n: 'نگرانی' },
  { id:  985, r: 'mo\'asser', m: 'wirksam, effektiv', t: 'adjective', n: 'مؤثر' },
  { id:  986, r: 'baryeste', m: 'herausragend, hervorragend', t: 'adjective', n: 'برجسته' },
  { id:  987, r: 'gharn', m: 'Jahrhundert', t: 'noun', n: 'قرن' },
  { id:  988, r: 'residegi', m: 'Untersuchung', t: 'noun', n: 'رسیدگی' },
  { id:  989, r: 'riyal', m: 'Rial (Währung)', t: 'noun', n: 'ریال' },
  { id:  990, r: 'tasmim gereftan', m: 'entscheiden', t: 'verb', n: 'تصمیم گرفتن' },
  { id:  991, r: 'avvaliyye', m: 'primär, ursprünglich', t: 'adjective', n: 'اولیه' },
  { id:  992, r: 'fanni', m: 'technisch', t: 'adjective', n: 'فنی' },
  { id:  993, r: 'khodrow', m: 'Auto, Fahrzeug', t: 'noun', n: 'خودرو' },
  { id:  994, r: 'arz', m: 'Breite, Aussage', t: 'noun', n: 'عرض' },
  { id:  995, r: 'meghdar', m: 'Menge, Betrag', t: 'noun', n: 'مقدار' },
  { id:  996, r: 'omde', m: 'hauptsächlich, überwiegend', t: 'adjective', n: 'عمده' },
  { id:  997, r: 'ghowl', m: 'Versprechen, Aussage', t: 'noun', n: 'قول' },
  { id:  998, r: 'seporde', m: 'anvertraut, Einlage', t: 'noun', n: 'سپرده' },
  { id:  999, r: 'teyari', m: 'kommerziell, geschäftlich', t: 'adjective', n: 'تجاری' },
  { id: 1000, r: 'italiya', m: 'Italien', t: 'proper noun', n: 'ایتالیا' },
];

const GRAMMAR = [
  {
    title: 'Wortstellung: Subjekt – Objekt – Verb (SOV)',
    rule: 'Anders als im Deutschen (SVO/V2) steht das Verb im Farsi am ENDE. Das ist die größte strukturelle Umstellung für Deutsche.',
    examples: [
      { r: 'Man âb mikhâram.',    m: 'Ich Wasser trinke. (= Ich trinke Wasser.)' },
      { r: 'Ali ketâb mikhânad.', m: 'Ali Buch liest. (= Ali liest ein Buch.)' },
      { r: 'Mâ Irân miravim.',    m: 'Wir Iran gehen. (= Wir fahren in den Iran.)' },
    ]
  },
  {
    title: 'Das Verb „sein" — budan (Präsens)',
    rule: 'Das Kopulaverb wird als Suffix an das Subjekt oder Prädikat angehängt. Anders als dt. „sein" sind es keine eigenständigen Wörter.',
    examples: [
      { r: 'Man khubam.',        m: 'Ich gut-bin. (= Mir geht es gut.)' },
      { r: 'To khubi.',          m: 'Du gut-bist. (= Dir geht es gut.)' },
      { r: 'U doktor ast.',      m: 'Er/Sie Arzt ist. (= Er/Sie ist Arzt.)' },
      { r: 'Mâ Âlemân hastim.', m: 'Wir Deutschland sind. (= Wir kommen aus Deutschland.)' },
    ]
  },
  {
    title: 'Kein grammatisches Geschlecht — super Neuigkeit!',
    rule: 'Farsi hat KEIN grammatisches Geschlecht. Kein der/die/das! Das Wort „u" bedeutet sowohl er als auch sie. Adjektive verändern ihre Form nie.',
    examples: [
      { r: 'U doktor ast.',         m: '"Er/Sie ist Arzt" — ein Wort für beides!' },
      { r: 'U khâne-ash bozorg ast.', m: 'Sein/Ihr Haus ist groß.' },
    ]
  },
  {
    title: 'Die Ezâfe: Nomen und Adjektive verknüpfen',
    rule: 'Farsi verbindet Nomen mit Adjektiven oder anderen Nomen durch „-e" (oder „-ye"). Das Adjektiv steht NACH dem Nomen — umgekehrt wie im Deutschen!',
    examples: [
      { r: 'ketâb-e bozorg', m: 'Buch-[von] groß = das große Buch' },
      { r: 'pedar-e man',    m: 'Vater-[von] mir = mein Vater' },
      { r: 'chây-e sard',    m: 'Tee-[von] kalt = kalter Tee' },
    ]
  },
  {
    title: 'Präsens-Verben: das Präfix mi-',
    rule: 'Die meisten Präsensverben erhalten das Präfix „mi-". Der Stamm kommt vom Infinitiv (ohne „-dan" oder „-tan"). Dann folgt eine Personalendung.',
    examples: [
      { r: 'raftan → miravad',   m: 'gehen → er/sie geht' },
      { r: 'khândan → mikhânad', m: 'lesen → er/sie liest' },
      { r: 'Man mikonam.',       m: 'Ich mache / Ich tue.' },
    ]
  },
  {
    title: 'Zahlen 1–10 (kein Plural nötig!)',
    rule: 'Zahlen stehen VOR dem Nomen — wie im Deutschen. Aber anders als im Deutschen braucht man nach einer Zahl keine Pluralendung.',
    examples: [
      { r: 'yek, do, se, chahâr, panj',    m: '1, 2, 3, 4, 5' },
      { r: 'shesh, haft, hasht, noh, dah', m: '6, 7, 8, 9, 10' },
      { r: 'se ketâb',                     m: 'drei Buch (= drei Bücher — kein Plural!)' },
    ]
  },
  {
    title: 'Neue Konsonanten für Deutsche',
    rule: 'Drei Laute brauchen besondere Aufmerksamkeit: „kh" (wie „ch" in Bach), „gh" (stimmhaftes kh, wie das französische R), und „â" (langes offenes A wie in „Vater").',
    examples: [
      { r: 'kh — khâne',  m: '"kh" = wie Bach/ach, Haus' },
      { r: 'gh — gheyr',  m: '"gh" = stimmhafter Guttural, "außer"' },
      { r: 'â — âb',      m: '"â" = langes offenes A, Wasser' },
    ]
  },
];

const EXERCISES = [
  { q: 'Man ___ (Mir geht es gut — Suffix an "khub" anhängen).',    ans: 'khubam',   hint: 'Personalsuffix für "ich" ist -am' },
  { q: 'Ali ketâb ___ (Ali liest — mi- an khândan-Stamm).',         ans: 'mikhânad', hint: '"khândan"-Stamm = khân' },
  { q: 'Pedar-___ man = mein Vater (die Ezâfe).',                    ans: 'e',        hint: 'Kurzer Bindevokal' },
  { q: '___ doktor ast. (Sie ist Ärztin.)',                           ans: 'U',        hint: '"U" = er UND sie im Farsi' },
  { q: 'Se ___ (= drei Bücher — kein Plural!).',                     ans: 'ketâb',    hint: 'Nach Zahlen keine Veränderung nötig' },
  { q: 'Man âb ___. (Ich trinke Wasser — Verb am Ende.)',            ans: 'mikhâram', hint: '"khordan" = essen/trinken' },
  { q: 'Chây-e ___ = kalter Tee (Adjektiv nach dem Nomen).',         ans: 'sard',     hint: '"sard" = kalt' },
  { q: '___ miravid? (Wohin gehst du? — Fragewort)',                 ans: 'Kojâ',     hint: '"Kojâ" = wo / wohin' },
];

const PHRASES = {
  'Notfall-Basics': [
    { r: 'Komak!',                             d: 'Hilfe!' },
    { r: 'Englisi balad hasti?',               d: 'Sprechen Sie Englisch?' },
    { r: 'Nemifahmam.',                        d: 'Ich verstehe nicht.' },
    { r: 'Lotfan âhesteh tar sohbat konid.',  d: 'Bitte sprechen Sie langsamer.' },
    { r: 'Esm-e man ... ast.',                 d: 'Mein Name ist ...' },
    { r: 'Az Âlemân hastam.',                  d: 'Ich komme aus Deutschland.' },
  ],
  'Im Restaurant': [
    { r: 'Menoo dârid?',         d: 'Haben Sie eine Speisekarte?' },
    { r: 'In che ghazâiyi ast?', d: 'Was ist das für ein Gericht?' },
    { r: 'Hisâb lotfan.',        d: 'Die Rechnung bitte.' },
    { r: 'Khoshmazeh bud!',      d: 'Es war köstlich!' },
    { r: 'Bê gosht lotfan.',     d: 'Ohne Fleisch bitte.' },
  ],
  'Unterwegs': [
    { r: 'Be ... mikhâham beram.',  d: 'Ich möchte nach ... fahren.' },
    { r: 'In âdres kojâst?',        d: 'Wo ist diese Adresse?' },
    { r: 'Che mowqi bâz ast?',      d: 'Wann öffnet es?' },
    { r: 'Chand daqiqe râh ast?',   d: 'Wie viele Minuten zu Fuß?' },
    { r: 'Lotfan motevaghef shid.', d: 'Bitte hier anhalten. (Taxi)' },
  ],
  'Einkaufen': [
    { r: 'In cheghadr ast?',  d: 'Wie viel kostet das?' },
    { r: 'Gerân ast.',        d: 'Das ist teuer.' },
    { r: 'Arzântar dârid?',   d: 'Haben Sie etwas Günstigeres?' },
    { r: 'Mikhâram.',         d: 'Ich nehme es.' },
  ],
  'Zahlen & Zeit': [
    { r: 'Sâat chand ast?',   d: 'Wie viel Uhr ist es?' },
    { r: 'Emruz chand ast?',  d: 'Welches Datum ist heute?' },
    { r: 'Fardâ / Diruz',     d: 'Morgen / Gestern' },
    { r: 'Sobh / Asr / Shab', d: 'Morgen / Nachmittag / Nacht' },
  ],
};
