/* ── DATA ──
   Source of truth: data/vocab.json
   To load dynamically, serve the app via a local HTTP server and replace this
   file with: const { topics: TOPICS, vocab: VOCAB } = await fetch('../data/vocab.json').then(r => r.json());
*/

const TOPICS = [
  { id: 'greetings', name: 'Grüßen',   icon: '👋' },
  { id: 'food',      name: 'Essen',    icon: '🍽️' },
  { id: 'travel',    name: 'Reisen',   icon: '✈️' },
  { id: 'daily',     name: 'Alltag',   icon: '🏠' },
  { id: 'numbers',   name: 'Zahlen',   icon: '🔢' },
  { id: 'colors',    name: 'Farben',   icon: '🎨' },
  { id: 'time',      name: 'Zeit',     icon: '🕐' },
  { id: 'body',      name: 'Körper',   icon: '🧍' },
  { id: 'home',      name: 'Zuhause',  icon: '🛋️' },
  { id: 'verbs',     name: 'Verben',   icon: '⚡' },
  { id: 'feelings',  name: 'Gefühle',  icon: '💬' },
  { id: 'nature',    name: 'Natur',    icon: '🌿' },
];

const VOCAB = [
  { id:  1, r: 'salâm',               m: 'Hallo',                       t: 'greetings', n: 'Informell, zu jeder Tageszeit verwendbar' },
  { id:  2, r: 'khodâhâfez',          m: 'Auf Wiedersehen',             t: 'greetings', n: 'Wörtl. "Gott-Beschützer"' },
  { id:  3, r: 'mersi / mamnun',      m: 'Danke',                       t: 'greetings', n: '"Mersi" ist aus dem Französischen entlehnt, sehr verbreitet' },
  { id:  4, r: 'khâhesh mikonam',     m: 'Bitte / Gern geschehen',      t: 'greetings', n: 'Auch als "bitte" beim Bitten verwendet' },
  { id:  5, r: 'bebakhshid',          m: 'Entschuldigung / Verzeihung', t: 'greetings', n: 'Zum Aufmerksamkeit erregen oder entschuldigen' },
  { id:  6, r: 'bale / na',           m: 'Ja / Nein',                   t: 'greetings', n: '"Are" wird umgangssprachlich auch für ja verwendet' },
  { id:  7, r: 'esme shomâ chist?',   m: 'Wie heißen Sie?',             t: 'greetings', n: 'Formal; "esme to chiye?" ist informell' },
  { id:  8, r: 'hâle shomâ chetore?', m: 'Wie geht es Ihnen?',         t: 'greetings', n: 'Formelle Version' },

  { id:  9, r: 'nân',                 m: 'Brot',                        t: 'food',      n: 'Grundnahrungsmittel — Fladenbrot heißt "nâne lavâsh"' },
  { id: 10, r: 'âb',                  m: 'Wasser',                      t: 'food',      n: 'Indoeuropäische Wurzel — wie Latein "aqua"' },
  { id: 11, r: 'chây',                m: 'Tee',                         t: 'food',      n: 'Zentrales Element der iranischen Kultur' },
  { id: 12, r: 'berenj',              m: 'Reis',                        t: 'food',      n: '' },
  { id: 13, r: 'morgh',               m: 'Hähnchen',                    t: 'food',      n: '' },
  { id: 14, r: 'mive',                m: 'Obst',                        t: 'food',      n: '' },
  { id: 15, r: 'sabzi',               m: 'Gemüse / Kräuter',           t: 'food',      n: 'Bedeutet auch "grün"' },
  { id: 16, r: 'ghazâ',               m: 'Essen / Mahlzeit',            t: 'food',      n: '' },

  { id: 17, r: 'in cheghadr ast?',    m: 'Wie viel kostet das?',        t: 'travel',    n: 'Unverzichtbar beim Einkaufen' },
  { id: 18, r: 'kojâst?',             m: 'Wo ist das?',                 t: 'travel',    n: '"Dastshui kojâst?" = Wo ist die Toilette?' },
  { id: 19, r: 'taxi',                m: 'Taxi',                        t: 'travel',    n: 'Dasselbe Wort ins Farsi entlehnt' },
  { id: 20, r: 'hotel',               m: 'Hotel',                       t: 'travel',    n: 'Dasselbe Wort' },
  { id: 21, r: 'bâzâr',               m: 'Markt / Basar',               t: 'travel',    n: 'Persisches Wort ins Deutsche entlehnt!' },
  { id: 22, r: 'râst / chap',         m: 'rechts / links',              t: 'travel',    n: '' },
  { id: 23, r: 'doktor',              m: 'Arzt',                        t: 'travel',    n: '' },

  { id: 24, r: 'dâneshgâh',           m: 'Universität',                 t: 'daily',     n: '' },
  { id: 25, r: 'khâne',               m: 'Haus / Zuhause',              t: 'daily',     n: '' },
  { id: 26, r: 'kâr',                 m: 'Arbeit / Beruf',              t: 'daily',     n: '' },
  { id: 27, r: 'pedar / mâdar',       m: 'Vater / Mutter',              t: 'daily',     n: 'Urverwandt mit deutschem Vater/Mutter!' },
  { id: 28, r: 'dokhtar / pesar',     m: 'Tochter / Sohn',              t: 'daily',     n: '"dokhtar" ähnelt "Tochter" — urverwandt! "Dokhtar" bedeutet auch "Mädchen"' },
  { id: 29, r: 'ketâb',               m: 'Buch',                        t: 'daily',     n: '' },
  { id: 30, r: 'telefon',             m: 'Telefon',                     t: 'daily',     n: '' },

  { id: 31, r: 'dorud',               m: 'Guten Tag',                   t: 'greetings', n: 'Formeller Gruß, wie "Grüß Gott"' },
  { id: 32, r: 'shab bekheyr',        m: 'Gute Nacht',                  t: 'greetings', n: 'Wörtl. "gute Nacht haben"' },
  { id: 33, r: 'sobh bekheyr',        m: 'Guten Morgen',                t: 'greetings', n: '' },
  { id: 34, r: 'khosh âmadid',        m: 'Willkommen',                  t: 'greetings', n: 'Wörtl. "ihr seid gut gekommen"' },
  { id: 35, r: 'movâfegham',          m: 'Einverstanden / OK',          t: 'greetings', n: '' },
  { id: 36, r: 'lotfan',              m: 'Bitte',                       t: 'greetings', n: 'Beim Bitten um etwas, steht oft am Satzende' },

  { id: 37, r: 'shir',                m: 'Milch',                       t: 'food',      n: '' },
  { id: 38, r: 'gusht',               m: 'Fleisch',                     t: 'food',      n: '' },
  { id: 39, r: 'mâhi',                m: 'Fisch',                       t: 'food',      n: '' },
  { id: 40, r: 'tokhm morgh',         m: 'Ei',                          t: 'food',      n: 'Wörtl. "Hühnerei"' },
  { id: 41, r: 'sib',                 m: 'Apfel',                       t: 'food',      n: '' },
  { id: 42, r: 'moz',                 m: 'Banane',                      t: 'food',      n: '' },
  { id: 43, r: 'porteghal',           m: 'Orange',                      t: 'food',      n: 'Wörtl. "Portugal" — Portugiesen brachten Orangen nach Persien' },
  { id: 44, r: 'namak',               m: 'Salz',                        t: 'food',      n: '' },
  { id: 45, r: 'shekar',              m: 'Zucker',                      t: 'food',      n: '"Zucker" kommt aus dem Persischen! šakar → Zucker' },
  { id: 46, r: 'roghan',              m: 'Öl / Butter',                 t: 'food',      n: '' },
  { id: 47, r: 'âbmive',              m: 'Saft',                        t: 'food',      n: 'Wörtl. "Wasserobst"' },
  { id: 48, r: 'âsh',                 m: 'Suppe / Eintopf',             t: 'food',      n: 'Typisch iranische dicke Gemüsesuppe' },
  { id: 49, r: 'qahve',               m: 'Kaffee',                      t: 'food',      n: '' },
  { id: 50, r: 'pesteh',              m: 'Pistazien',                   t: 'food',      n: 'Persien ist die Heimat der Pistazie!' },
  { id: 51, r: 'khorma',              m: 'Datteln',                     t: 'food',      n: '' },
  { id: 52, r: 'angur',               m: 'Weintraube',                  t: 'food',      n: '' },
  { id: 53, r: 'halim',               m: 'Haferbrei mit Fleisch',       t: 'food',      n: 'Traditionelles persisches Frühstücksgericht' },

  { id: 54, r: 'foroudgâh',           m: 'Flughafen',                   t: 'travel',    n: '' },
  { id: 55, r: 'istgâh',              m: 'Haltestelle / Bahnhof',       t: 'travel',    n: '' },
  { id: 56, r: 'otobos',              m: 'Bus',                         t: 'travel',    n: '' },
  { id: 57, r: 'metro',               m: 'U-Bahn',                      t: 'travel',    n: 'Teheran hat ein umfangreiches U-Bahn-Netz' },
  { id: 58, r: 'bilit',               m: 'Ticket / Fahrkarte',          t: 'travel',    n: '' },
  { id: 59, r: 'naghshe',             m: 'Karte / Stadtplan',           t: 'travel',    n: '' },
  { id: 60, r: 'shahr',               m: 'Stadt',                       t: 'travel',    n: '' },
  { id: 61, r: 'keshvar',             m: 'Land',                        t: 'travel',    n: '' },
  { id: 62, r: 'sefârat',             m: 'Botschaft',                   t: 'travel',    n: '' },
  { id: 63, r: 'bimârestân',          m: 'Krankenhaus',                 t: 'travel',    n: '' },
  { id: 64, r: 'dârukhâne',           m: 'Apotheke',                    t: 'travel',    n: '' },
  { id: 65, r: 'polis',               m: 'Polizei',                     t: 'travel',    n: '' },
  { id: 66, r: 'sâhel',               m: 'Strand / Küste',              t: 'travel',    n: '' },

  { id: 67, r: 'madrasse',            m: 'Schule',                      t: 'daily',     n: '' },
  { id: 68, r: 'moallem',             m: 'Lehrer / Lehrerin',           t: 'daily',     n: '' },
  { id: 69, r: 'hamsar',              m: 'Ehemann / Ehefrau',           t: 'daily',     n: 'Geschlechtsneutrales Wort für Ehepartner' },
  { id: 70, r: 'barâdar / khâhar',    m: 'Bruder / Schwester',          t: 'daily',     n: '"barâdar" ist urverwandt mit dt. "Bruder"!' },
  { id: 71, r: 'dust',                m: 'Freund',                      t: 'daily',     n: '"dust dâshtan" = mögen / lieben' },
  { id: 72, r: 'hamsâye',             m: 'Nachbar',                     t: 'daily',     n: '' },
  { id: 73, r: 'bank',                m: 'Bank',                        t: 'daily',     n: '' },
  { id: 74, r: 'daftar',              m: 'Büro / Schreibtisch',         t: 'daily',     n: '' },
  { id: 75, r: 'mâshin',              m: 'Auto',                        t: 'daily',     n: 'Aus dem Französischen "machine"' },
  { id: 76, r: 'bache',               m: 'Kind',                        t: 'daily',     n: '' },
  { id: 77, r: 'pul',                 m: 'Geld',                        t: 'daily',     n: '' },
  { id: 78, r: 'jâde',                m: 'Straße / Weg',                t: 'daily',     n: '' },
  { id: 79, r: 'rang',                m: 'Farbe',                       t: 'daily',     n: '' },

  { id: 80, r: 'yek',                 m: 'eins',                        t: 'numbers',   n: '' },
  { id: 81, r: 'do',                  m: 'zwei',                        t: 'numbers',   n: 'Urverwandt mit dt. "zwei" / lat. "duo"' },
  { id: 82, r: 'se',                  m: 'drei',                        t: 'numbers',   n: 'Urverwandt mit dt. "drei" / lat. "tres"' },
  { id: 83, r: 'chahâr',              m: 'vier',                        t: 'numbers',   n: '' },
  { id: 84, r: 'panj',                m: 'fünf',                        t: 'numbers',   n: 'Urverwandt mit dt. "fünf" über PIE *pénkʷe' },
  { id: 85, r: 'shesh',               m: 'sechs',                       t: 'numbers',   n: '' },
  { id: 86, r: 'haft',                m: 'sieben',                      t: 'numbers',   n: 'Urverwandt mit dt. "sieben" über PIE *septḿ̥' },
  { id: 87, r: 'hasht',               m: 'acht',                        t: 'numbers',   n: 'Urverwandt mit dt. "acht"!' },
  { id: 88, r: 'noh',                 m: 'neun',                        t: 'numbers',   n: 'Urverwandt mit dt. "neun"!' },
  { id: 89, r: 'dah',                 m: 'zehn',                        t: 'numbers',   n: 'Urverwandt mit dt. "zehn" / lat. "decem"' },
  { id: 90, r: 'bist',                m: 'zwanzig',                     t: 'numbers',   n: '' },
  { id: 91, r: 'sad',                 m: 'hundert',                     t: 'numbers',   n: '' },
  { id: 92, r: 'hezâr',               m: 'tausend',                     t: 'numbers',   n: '' },
  { id: 93, r: 'aval',                m: 'erst- / Erster',              t: 'numbers',   n: 'Aus dem Arabischen' },
  { id: 94, r: 'dovvom',              m: 'zweit- / Zweiter',            t: 'numbers',   n: '' },
  { id: 95, r: 'chand?',              m: 'wie viele? / wie viel?',      t: 'numbers',   n: '"chand tâ?" = wie viele Stück?' },

  { id:  96, r: 'sefid',              m: 'weiß',                        t: 'colors',    n: '' },
  { id:  97, r: 'siyâh',              m: 'schwarz',                     t: 'colors',    n: '' },
  { id:  98, r: 'ghermez',            m: 'rot',                         t: 'colors',    n: '' },
  { id:  99, r: 'âbi',                m: 'blau',                        t: 'colors',    n: 'Von "âb" (Wasser) — wasserfarben' },
  { id: 100, r: 'sabz',               m: 'grün',                        t: 'colors',    n: 'Dasselbe Wort wie "sabzi" (Gemüse/Kräuter)' },
  { id: 101, r: 'zard',               m: 'gelb',                        t: 'colors',    n: '' },
  { id: 102, r: 'nârenji',            m: 'orange',                      t: 'colors',    n: 'Von "nâranj" (Bitterorange) — gab der Farbe Orange den Namen!' },
  { id: 103, r: 'banafshe',           m: 'lila / violett',              t: 'colors',    n: 'Auch das Wort für Veilchen' },
  { id: 104, r: 'qahveyi',            m: 'braun',                       t: 'colors',    n: 'Von "qahve" (Kaffee) — kaffeefarben' },
  { id: 105, r: 'khâkestari',         m: 'grau',                        t: 'colors',    n: 'Wörtl. "aschefarben" (khâk = Erde/Asche)' },

  { id: 106, r: 'emruz',              m: 'heute',                       t: 'time',      n: '' },
  { id: 107, r: 'fardâ',              m: 'morgen',                      t: 'time',      n: '' },
  { id: 108, r: 'diruz',              m: 'gestern',                     t: 'time',      n: '' },
  { id: 109, r: 'hafteh',             m: 'Woche',                       t: 'time',      n: '' },
  { id: 110, r: 'mâh',                m: 'Monat / Mond',                t: 'time',      n: 'Ein Wort für beides, wie im Deutschen früher "Mond"' },
  { id: 111, r: 'sâl',                m: 'Jahr',                        t: 'time',      n: '' },
  { id: 112, r: 'sâat',               m: 'Uhr / Stunde',                t: 'time',      n: '"Sâat chand ast?" = Wie viel Uhr ist es?' },
  { id: 113, r: 'daqiqe',             m: 'Minute',                      t: 'time',      n: '' },
  { id: 114, r: 'sobh',               m: 'Morgen / Vormittag',          t: 'time',      n: '' },
  { id: 115, r: 'zohr',               m: 'Mittag',                      t: 'time',      n: '' },
  { id: 116, r: 'asr',                m: 'Nachmittag',                  t: 'time',      n: '' },
  { id: 117, r: 'shab',               m: 'Nacht / Abend',               t: 'time',      n: '' },
  { id: 118, r: 'hâlâ',               m: 'jetzt',                       t: 'time',      n: '' },
  { id: 119, r: 'zud',                m: 'früh / schnell',              t: 'time',      n: '' },
  { id: 120, r: 'dir',                m: 'spät',                        t: 'time',      n: '' },
  { id: 121, r: 'dishab',             m: 'gestern Nacht',               t: 'time',      n: '' },
  { id: 122, r: 'emshab',             m: 'heute Nacht',                 t: 'time',      n: '' },

  { id: 123, r: 'sar',                m: 'Kopf',                        t: 'body',      n: '' },
  { id: 124, r: 'cheshm',             m: 'Auge',                        t: 'body',      n: '' },
  { id: 125, r: 'gush',               m: 'Ohr',                         t: 'body',      n: '' },
  { id: 126, r: 'bini',               m: 'Nase',                        t: 'body',      n: '' },
  { id: 127, r: 'dahan',              m: 'Mund',                        t: 'body',      n: '' },
  { id: 128, r: 'dast',               m: 'Hand',                        t: 'body',      n: '' },
  { id: 129, r: 'pâ',                 m: 'Fuß / Bein',                  t: 'body',      n: 'Urverwandt mit lat. "pes/pedis" und dt. "Fuß" über PIE' },
  { id: 130, r: 'shekam',             m: 'Bauch / Magen',               t: 'body',      n: '' },
  { id: 131, r: 'qalb',               m: 'Herz',                        t: 'body',      n: 'Aus dem Arabischen — auch in "Kaliber" steckt diese Wurzel' },
  { id: 132, r: 'posht',              m: 'Rücken',                      t: 'body',      n: '' },
  { id: 133, r: 'surat',              m: 'Gesicht',                     t: 'body',      n: '' },
  { id: 134, r: 'mu',                 m: 'Haar',                        t: 'body',      n: '' },
  { id: 135, r: 'dandân',             m: 'Zahn',                        t: 'body',      n: 'Urverwandt mit lat. "dens/dentis" und engl. "dental"' },
  { id: 136, r: 'gardan',             m: 'Hals / Nacken',               t: 'body',      n: '' },
  { id: 137, r: 'zâno',               m: 'Knie',                        t: 'body',      n: '' },

  { id: 138, r: 'otâq',               m: 'Zimmer',                      t: 'home',      n: '' },
  { id: 139, r: 'dar',                m: 'Tür',                         t: 'home',      n: '' },
  { id: 140, r: 'panjareh',           m: 'Fenster',                     t: 'home',      n: '' },
  { id: 141, r: 'miz',                m: 'Tisch',                       t: 'home',      n: '' },
  { id: 142, r: 'sandali',            m: 'Stuhl',                       t: 'home',      n: '' },
  { id: 143, r: 'takht',              m: 'Bett',                        t: 'home',      n: '' },
  { id: 144, r: 'hammâm',             m: 'Bad / Badezimmer',            t: 'home',      n: '' },
  { id: 145, r: 'âshpazkhâne',        m: 'Küche',                       t: 'home',      n: 'Wörtl. "Koch-Haus"' },
  { id: 146, r: 'salon',              m: 'Wohnzimmer',                  t: 'home',      n: '' },
  { id: 147, r: 'kolid',              m: 'Schlüssel',                   t: 'home',      n: '' },
  { id: 148, r: 'cherâgh',            m: 'Lampe / Licht',               t: 'home',      n: '' },
  { id: 149, r: 'yakhchâl',           m: 'Kühlschrank',                 t: 'home',      n: 'Wörtl. "Eisgrube" — historische persische Kühltechnik!' },
  { id: 150, r: 'farsh',              m: 'Teppich',                     t: 'home',      n: 'Persische Teppiche sind weltberühmt' },
  { id: 151, r: 'divâr',              m: 'Wand',                        t: 'home',      n: '' },
  { id: 152, r: 'saqf',               m: 'Decke (Zimmer)',              t: 'home',      n: '' },

  { id: 153, r: 'raftan',             m: 'gehen',                       t: 'verbs',     n: 'Präsens: mirav- (miravad = er/sie geht)' },
  { id: 154, r: 'âmadan',             m: 'kommen',                      t: 'verbs',     n: 'Präsens: miây- (miâyad = er/sie kommt)' },
  { id: 155, r: 'goftan',             m: 'sagen',                       t: 'verbs',     n: 'Präsens: miguy- (miguyad = er/sie sagt)' },
  { id: 156, r: 'didan',              m: 'sehen',                       t: 'verbs',     n: 'Präsens: mibin- (mibinad = er/sie sieht)' },
  { id: 157, r: 'khândan',            m: 'lesen / rufen',               t: 'verbs',     n: 'Präsens: mikhân- (mikhânad = er/sie liest)' },
  { id: 158, r: 'neveshtan',          m: 'schreiben',                   t: 'verbs',     n: 'Präsens: minevis- (minevisad = er/sie schreibt)' },
  { id: 159, r: 'khordan',            m: 'essen / trinken',             t: 'verbs',     n: 'Präsens: mikhor- — ein Verb für beides!' },
  { id: 160, r: 'khâbidan',           m: 'schlafen',                    t: 'verbs',     n: 'Präsens: mikhâb-' },
  { id: 161, r: 'budan',              m: 'sein',                        t: 'verbs',     n: 'Als Suffix: -am (ich bin), -i (du bist), -ast (er/sie ist)' },
  { id: 162, r: 'dâshtan',            m: 'haben',                       t: 'verbs',     n: 'Präsens: dâr- (dârad = er/sie hat)' },
  { id: 163, r: 'kardan',             m: 'machen / tun',                t: 'verbs',     n: 'Präsens: mikon- — sehr häufig in zusammengesetzten Verben' },
  { id: 164, r: 'dust dâshtan',       m: 'mögen / lieben',              t: 'verbs',     n: 'Wörtl. "Freund haben"' },
  { id: 165, r: 'fahmidan',           m: 'verstehen',                   t: 'verbs',     n: 'Präsens: mifahm-' },
  { id: 166, r: 'harf zadan',         m: 'sprechen / reden',            t: 'verbs',     n: 'Wörtl. "Buchstaben schlagen"' },
  { id: 167, r: 'shenidan',           m: 'hören',                       t: 'verbs',     n: 'Präsens: mishen-' },
  { id: 168, r: 'dâdan',              m: 'geben',                       t: 'verbs',     n: 'Präsens: midah- (midahad = er/sie gibt)' },
  { id: 169, r: 'porsidan',           m: 'fragen',                      t: 'verbs',     n: 'Präsens: mipors-' },
  { id: 170, r: 'kharid kardan',      m: 'einkaufen',                   t: 'verbs',     n: 'Zusammengesetztes Verb: kharid (Einkauf) + kardan (machen)' },

  { id: 171, r: 'khub',               m: 'gut',                         t: 'feelings',  n: '' },
  { id: 172, r: 'bad',                m: 'schlecht',                    t: 'feelings',  n: 'Gleiche Aussprache wie dt. "bad" (Bad)!' },
  { id: 173, r: 'bozorg',             m: 'groß',                        t: 'feelings',  n: '' },
  { id: 174, r: 'kuchak',             m: 'klein',                       t: 'feelings',  n: '' },
  { id: 175, r: 'sard',               m: 'kalt',                        t: 'feelings',  n: '' },
  { id: 176, r: 'garm',               m: 'warm / heiß',                 t: 'feelings',  n: 'Urverwandt mit dt. "warm"!' },
  { id: 177, r: 'tund',               m: 'schnell / scharf (Geschmack)',t: 'feelings',  n: '' },
  { id: 178, r: 'âheste',             m: 'langsam',                     t: 'feelings',  n: '' },
  { id: 179, r: 'khoshhal',           m: 'glücklich / fröhlich',        t: 'feelings',  n: 'Wörtl. "guter Zustand"' },
  { id: 180, r: 'nârâhat',            m: 'traurig / unzufrieden',       t: 'feelings',  n: 'Wörtl. "nicht bequem"' },
  { id: 181, r: 'khaste',             m: 'müde',                        t: 'feelings',  n: '' },
  { id: 182, r: 'gerân',              m: 'teuer',                       t: 'feelings',  n: '' },
  { id: 183, r: 'arzân',              m: 'billig / günstig',            t: 'feelings',  n: '' },
  { id: 184, r: 'por',                m: 'voll',                        t: 'feelings',  n: '' },
  { id: 185, r: 'khâli',              m: 'leer',                        t: 'feelings',  n: '' },
  { id: 186, r: 'tâze',               m: 'frisch / neu',                t: 'feelings',  n: '' },
  { id: 187, r: 'âsân',               m: 'einfach / leicht',            t: 'feelings',  n: '' },
  { id: 188, r: 'moshkel',            m: 'schwierig / Problem',         t: 'feelings',  n: '' },

  { id: 189, r: 'âftâb',              m: 'Sonne / Sonnenschein',        t: 'nature',    n: '' },
  { id: 190, r: 'mâhtâb',             m: 'Mondlicht / Mond',            t: 'nature',    n: 'Wörtl. "Mondglanz"' },
  { id: 191, r: 'setâre',             m: 'Stern',                       t: 'nature',    n: 'Urverwandt mit lat. "stella" und dt. "Stern"!' },
  { id: 192, r: 'bârun',              m: 'Regen',                       t: 'nature',    n: '' },
  { id: 193, r: 'bâd',                m: 'Wind',                        t: 'nature',    n: '' },
  { id: 194, r: 'barf',               m: 'Schnee',                      t: 'nature',    n: '' },
  { id: 195, r: 'daryâ',              m: 'Meer / See',                  t: 'nature',    n: '' },
  { id: 196, r: 'kuh',                m: 'Berg',                        t: 'nature',    n: 'Der Hindukusch enthält dieses Wort: "Kuh-e Hend"' },
  { id: 197, r: 'jangal',             m: 'Wald / Dschungel',            t: 'nature',    n: '"Dschungel" kommt aus dem Persischen über Hindi!' },
  { id: 198, r: 'gol',                m: 'Blume / Rose',                t: 'nature',    n: 'Persien ist berühmt für seine Rosen und Rosenwasser' },
  { id: 199, r: 'derakht',            m: 'Baum',                        t: 'nature',    n: '' },
  { id: 200, r: 'âsemân',             m: 'Himmel',                      t: 'nature',    n: '' },
];

const GRAMMAR = [
  {
    title: 'Wortstellung: Subjekt – Objekt – Verb (SOV)',
    rule: 'Anders als im Deutschen (SVO/V2) steht das Verb im Farsi am ENDE. Das ist die größte strukturelle Umstellung für Deutsche.',
    examples: [
      { r: 'Man âb mikhâram.',    m: 'Ich Wasser trinke. (= Ich trinke Wasser.)' },
      { r: 'Ali ketâb mikhânad.', m: 'Ali Buch liest. (= Ali liest ein Buch.)' },
      { r: 'Mâ Irân miravim.',    m: 'Wir Iran gehen. (= Wir fahren in den Iran.)' },
    ]
  },
  {
    title: 'Das Verb „sein" — budan (Präsens)',
    rule: 'Das Kopulaverb wird als Suffix an das Subjekt oder Prädikat angehängt. Anders als dt. „sein" sind es keine eigenständigen Wörter.',
    examples: [
      { r: 'Man khubam.',        m: 'Ich gut-bin. (= Mir geht es gut.)' },
      { r: 'To khubi.',          m: 'Du gut-bist. (= Dir geht es gut.)' },
      { r: 'U doktor ast.',      m: 'Er/Sie Arzt ist. (= Er/Sie ist Arzt.)' },
      { r: 'Mâ Âlemân hastim.', m: 'Wir Deutschland sind. (= Wir kommen aus Deutschland.)' },
    ]
  },
  {
    title: 'Kein grammatisches Geschlecht — super Neuigkeit!',
    rule: 'Farsi hat KEIN grammatisches Geschlecht. Kein der/die/das! Das Wort „u" bedeutet sowohl er als auch sie. Adjektive verändern ihre Form nie.',
    examples: [
      { r: 'U doktor ast.',         m: '"Er/Sie ist Arzt" — ein Wort für beides!' },
      { r: 'U khâne-ash bozorg ast.', m: 'Sein/Ihr Haus ist groß.' },
    ]
  },
  {
    title: 'Die Ezâfe: Nomen und Adjektive verknüpfen',
    rule: 'Farsi verbindet Nomen mit Adjektiven oder anderen Nomen durch „-e" (oder „-ye"). Das Adjektiv steht NACH dem Nomen — umgekehrt wie im Deutschen!',
    examples: [
      { r: 'ketâb-e bozorg', m: 'Buch-[von] groß = das große Buch' },
      { r: 'pedar-e man',    m: 'Vater-[von] mir = mein Vater' },
      { r: 'chây-e sard',    m: 'Tee-[von] kalt = kalter Tee' },
    ]
  },
  {
    title: 'Präsens-Verben: das Präfix mi-',
    rule: 'Die meisten Präsensverben erhalten das Präfix „mi-". Der Stamm kommt vom Infinitiv (ohne „-dan" oder „-tan"). Dann folgt eine Personalendung.',
    examples: [
      { r: 'raftan → miravad',   m: 'gehen → er/sie geht' },
      { r: 'khândan → mikhânad', m: 'lesen → er/sie liest' },
      { r: 'Man mikonam.',       m: 'Ich mache / Ich tue.' },
    ]
  },
  {
    title: 'Zahlen 1–10 (kein Plural nötig!)',
    rule: 'Zahlen stehen VOR dem Nomen — wie im Deutschen. Aber anders als im Deutschen braucht man nach einer Zahl keine Pluralendung.',
    examples: [
      { r: 'yek, do, se, chahâr, panj',    m: '1, 2, 3, 4, 5' },
      { r: 'shesh, haft, hasht, noh, dah', m: '6, 7, 8, 9, 10' },
      { r: 'se ketâb',                     m: 'drei Buch (= drei Bücher — kein Plural!)' },
    ]
  },
  {
    title: 'Neue Konsonanten für Deutsche',
    rule: 'Drei Laute brauchen besondere Aufmerksamkeit: „kh" (wie „ch" in Bach), „gh" (stimmhaftes kh, wie das französische R), und „â" (langes offenes A wie in „Vater").',
    examples: [
      { r: 'kh — khâne',  m: '"kh" = wie Bach/ach, Haus' },
      { r: 'gh — gheyr',  m: '"gh" = stimmhafter Guttural, "außer"' },
      { r: 'â — âb',      m: '"â" = langes offenes A, Wasser' },
    ]
  },
];

const EXERCISES = [
  { q: 'Man ___ (Mir geht es gut — Suffix an "khub" anhängen).',    ans: 'khubam',   hint: 'Personalsuffix für "ich" ist -am' },
  { q: 'Ali ketâb ___ (Ali liest — mi- an khândan-Stamm).',         ans: 'mikhânad', hint: '"khândan"-Stamm = khân' },
  { q: 'Pedar-___ man = mein Vater (die Ezâfe).',                    ans: 'e',        hint: 'Kurzer Bindevokal' },
  { q: '___ doktor ast. (Sie ist Ärztin.)',                           ans: 'U',        hint: '"U" = er UND sie im Farsi' },
  { q: 'Se ___ (= drei Bücher — kein Plural!).',                     ans: 'ketâb',    hint: 'Nach Zahlen keine Veränderung nötig' },
  { q: 'Man âb ___. (Ich trinke Wasser — Verb am Ende.)',            ans: 'mikhâram', hint: '"khordan" = essen/trinken' },
  { q: 'Chây-e ___ = kalter Tee (Adjektiv nach dem Nomen).',         ans: 'sard',     hint: '"sard" = kalt' },
  { q: '___ miravid? (Wohin gehst du? — Fragewort)',                 ans: 'Kojâ',     hint: '"Kojâ" = wo / wohin' },
];

const PHRASES = {
  'Notfall-Basics': [
    { r: 'Komak!',                             d: 'Hilfe!' },
    { r: 'Englisi balad hasti?',               d: 'Sprechen Sie Englisch?' },
    { r: 'Nemifahmam.',                        d: 'Ich verstehe nicht.' },
    { r: 'Lotfan âhesteh tar sohbat konid.',  d: 'Bitte sprechen Sie langsamer.' },
    { r: 'Esm-e man ... ast.',                 d: 'Mein Name ist ...' },
    { r: 'Az Âlemân hastam.',                  d: 'Ich komme aus Deutschland.' },
  ],
  'Im Restaurant': [
    { r: 'Menoo dârid?',         d: 'Haben Sie eine Speisekarte?' },
    { r: 'In che ghazâiyi ast?', d: 'Was ist das für ein Gericht?' },
    { r: 'Hisâb lotfan.',        d: 'Die Rechnung bitte.' },
    { r: 'Khoshmazeh bud!',      d: 'Es war köstlich!' },
    { r: 'Bê gosht lotfan.',     d: 'Ohne Fleisch bitte.' },
  ],
  'Unterwegs': [
    { r: 'Be ... mikhâham beram.',  d: 'Ich möchte nach ... fahren.' },
    { r: 'In âdres kojâst?',        d: 'Wo ist diese Adresse?' },
    { r: 'Che mowqi bâz ast?',      d: 'Wann öffnet es?' },
    { r: 'Chand daqiqe râh ast?',   d: 'Wie viele Minuten zu Fuß?' },
    { r: 'Lotfan motevaghef shid.', d: 'Bitte hier anhalten. (Taxi)' },
  ],
  'Einkaufen': [
    { r: 'In cheghadr ast?',  d: 'Wie viel kostet das?' },
    { r: 'Gerân ast.',        d: 'Das ist teuer.' },
    { r: 'Arzântar dârid?',   d: 'Haben Sie etwas Günstigeres?' },
    { r: 'Mikhâram.',         d: 'Ich nehme es.' },
  ],
  'Zahlen & Zeit': [
    { r: 'Sâat chand ast?',   d: 'Wie viel Uhr ist es?' },
    { r: 'Emruz chand ast?',  d: 'Welches Datum ist heute?' },
    { r: 'Fardâ / Diruz',     d: 'Morgen / Gestern' },
    { r: 'Sobh / Asr / Shab', d: 'Morgen / Nachmittag / Nacht' },
  ],
};
