/* ── EXERCISE LEVEL DEFINITIONS ── */

const EXERCISE_LEVELS = [

  /* ════════════════════════════════════════
     PHASE 1 — FUNDAMENT (Level 1–10)
  ════════════════════════════════════════ */

  {
    id: 1, title: 'Erste Schritte', phase: 1,
    tasks: [
      { type:2, sentence:'___ (Hallo)', de:'Wie sagt man "Hallo"?',
        options:['Salâm','Khoda hâfez','Mersi','Bebakhshid'],
        correct:'Salâm', explanation:'Salâm bedeutet "Hallo" oder "Guten Tag" — der häufigste persische Gruß.' },
      { type:2, sentence:'___ (Tschüss)',
        options:['Khoda hâfez','Salâm','Bebakhshid','Lotfan'],
        correct:'Khoda hâfez', explanation:'Khoda hâfez = "Gott beschütze dich" — die häufigste Verabschiedung.' },
      { type:1, de:'Danke.',
        tiles:['Mersi','.'], solution:['Mersi','.'],
        explanation:'Mersi (aus dem Französischen) und Mamnun sind beide üblich für "Danke".' },
      { type:2, sentence:'___ (Bitte / Entschuldigung)',
        options:['Lotfan','Salâm','Mersi','Khub'],
        correct:'Lotfan', explanation:'Lotfan = "bitte" oder als Aufforderung zur Höflichkeit.' },
      { type:1, de:'Entschuldigung.',
        tiles:['Bebakhshid','.'], solution:['Bebakhshid','.'],
        explanation:'Bebakhshid = "Entschuldigung" oder "Verzeihung". Wörtlich: "Vergib mir".' },
      { type:2, sentence:'___ (Ja)',
        options:['Baleh','Na','Khub','Che'],
        correct:'Baleh', explanation:'Baleh = "ja". Im Umgangssprachlichen auch "Are" oder "Âre".' },
      { type:2, sentence:'___ (Nein)',
        options:['Na','Baleh','Khub','Lotfan'],
        correct:'Na', explanation:'Na = "nein". Auch: "Nah" in lässigem Sprechen.' },
      { type:1, de:'Wie geht es dir?',
        tiles:['Hâlet','chetore','?'], solution:['Hâlet','chetore','?'],
        explanation:'Hâlet chetore? = "Wie geht es dir?" — informelle Form.' },
      { type:2, sentence:'Khubam, ___. (Gut, danke.)',
        options:['mersi','salâm','lotfan','na'],
        correct:'mersi', explanation:'Khubam = ich bin gut. Khubam, mersi = "Gut, danke".' },
    ]
  },

  {
    id: 2, title: 'Ich bin…', phase: 1,
    tasks: [
      { type:2, sentence:'Man khub___ (Ich bin gut.)',
        options:['-am','-i','-id','-and'],
        correct:'-am', explanation:'1. Person Singular von "sein": -am an das Adjektiv anhängen.' },
      { type:1, de:'Du bist gut.',
        tiles:['To','khubi','.'], solution:['To','khubi','.'],
        explanation:'2. Person Singular: Adjektiv + -i. khub + i = khubi.' },
      { type:2, sentence:'U doktor ___ (Er/Sie ist Arzt.)',
        options:['ast','am','id','and'],
        correct:'ast', explanation:'3. Person Singular: "ast" steht nach dem Prädikat. Alternativ als Suffix: -e.' },
      { type:1, de:'Wir sind gut.',
        tiles:['Mâ','khubim','.'], solution:['Mâ','khubim','.'],
        explanation:'1. Person Plural: khub + im = khubim.' },
      { type:2, sentence:'Shomâ khub___ (Sie/Ihr seid gut.)',
        options:['-id','-im','-am','-i'],
        correct:'-id', explanation:'2. Person Plural: -id. Auch die Höflichkeitsform für "Sie".' },
      { type:1, de:'Er ist Lehrer.',
        tiles:['U','moalem','ast','.'], solution:['U','moalem','ast','.'],
        explanation:'U = er/sie (kein Unterschied). moalem = Lehrer. U moalem ast.' },
      { type:2, sentence:'Man Âlemâni ___ (Ich bin Deutsche/r.)',
        options:['hastam','hasti','hastid','hastand'],
        correct:'hastam', explanation:'hast-am: die betonte vollständige Form von "ich bin".' },
      { type:1, de:'Ich bin nicht gut.',
        tiles:['Man','khub','nistam','.'], solution:['Man','khub','nistam','.'],
        explanation:'Verneinung von "sein": nist- + Endung. Man khub nistam = Ich bin nicht gut.' },
    ]
  },

  {
    id: 3, title: 'Meine Familie', phase: 1,
    tasks: [
      { type:2, sentence:'___ = Vater',
        options:['Pedar','Mâdar','Baradar','Khahar'],
        correct:'Pedar', explanation:'Pedar = Vater. Verwandt mit deutschem "Vater" — beide indoeuropäisch!' },
      { type:2, sentence:'___ = Mutter',
        options:['Mâdar','Pedar','Baradar','Dust'],
        correct:'Mâdar', explanation:'Mâdar = Mutter. Auch verwandt mit "Mutter" (deutsch) über den gemeinsamen indoeuropäischen Ursprung.' },
      { type:1, de:'mein Vater',
        tiles:['pedar-e','man'], solution:['pedar-e','man'],
        explanation:'Besitz mit Ezâfe: pedar-e man = "Vater-EZ ich" = mein Vater.' },
      { type:2, sentence:'___ = Bruder',
        options:['Baradar','Khahar','Pedar','Mâdar'],
        correct:'Baradar', explanation:'Baradar = Bruder.' },
      { type:2, sentence:'___ = Schwester',
        options:['Khahar','Baradar','Dokhtar','Pesar'],
        correct:'Khahar', explanation:'Khahar = Schwester.' },
      { type:1, de:'meine Schwester',
        tiles:['khahar-e','man'], solution:['khahar-e','man'],
        explanation:'Ezâfe verbindet: khahar-e man = "Schwester-EZ ich".' },
      { type:2, sentence:'___ = Tochter',
        options:['Dokhtar','Pesar','Baradar','Zan'],
        correct:'Dokhtar', explanation:'Dokhtar = Tochter (auch: Mädchen). Verwandt mit "Tochter"!' },
      { type:2, sentence:'___ = Sohn',
        options:['Pesar','Dokhtar','Mard','Zan'],
        correct:'Pesar', explanation:'Pesar = Sohn (auch: Junge).' },
      { type:1, de:'sein Bruder',
        tiles:['baradar-e','u'], solution:['baradar-e','u'],
        explanation:'U = er/sie. baradar-e u = sein/ihr Bruder.' },
    ]
  },

  {
    id: 4, title: 'Wie viele?', phase: 1,
    tasks: [
      { type:2, sentence:'___ = eins',
        options:['Yek','Do','Se','Chahâr'],
        correct:'Yek', explanation:'Yek = 1. Die Zahlen 1–10 sind Grundvokabular.' },
      { type:2, sentence:'___ = drei',
        options:['Se','Do','Chahâr','Panj'],
        correct:'Se', explanation:'Se = 3.' },
      { type:1, de:'fünf',
        tiles:['Panj'], solution:['Panj'],
        explanation:'Panj = 5. Yek, do, se, chahâr, panj = 1–5.' },
      { type:2, sentence:'___ = sieben',
        options:['Haft','Shesh','Hasht','Noh'],
        correct:'Haft', explanation:'Haft = 7. Auch in "Haft-Sin" (sieben S beim Nowruz).' },
      { type:5, farsi:'Se ketâb.',
        options:['drei Bücher','drei Buch — kein Plural nötig!','dreimal Buch','drei Büchern'],
        correct:'drei Buch — kein Plural nötig!',
        explanation:'Nach Zahlen steht das Nomen im Singular! Se ketâb = drei Buch (= drei Bücher).' },
      { type:2, sentence:'Panj ___ (fünf Äpfel — kein Plural!)',
        options:['sib','sib-hâ','sib-ân','sib-e'],
        correct:'sib', explanation:'Nach Zahlen kein Plural! Panj sib = fünf Apfel (= Äpfel).' },
      { type:5, farsi:'Dah nâmeh.',
        options:['zehn Briefe','zehn Brief','der zehnte Brief','zehn Briefen'],
        correct:'zehn Briefe',
        explanation:'Dah = 10, nâmeh = Brief. Korrekte Übersetzung ist "zehn Briefe" — auch wenn im Persischen kein Plural steht.' },
      { type:1, de:'zwei Häuser',
        tiles:['Do','khâne'], solution:['Do','khâne'],
        explanation:'Do khâne = "zwei Haus" — kein Plural nach Zahlen!' },
    ]
  },

  {
    id: 5, title: 'Wo ist…?', phase: 1,
    tasks: [
      { type:2, sentence:'___ = wo?',
        options:['Kojâ','Chi','Kie','Chand'],
        correct:'Kojâ', explanation:'Kojâ = wo? Häufige Frage beim Reisen.' },
      { type:1, de:'Wo ist das Haus?',
        tiles:['Khâne','kojâst','?'], solution:['Khâne','kojâst','?'],
        explanation:'kojâst = kojâ + ast = "wo ist". Das Verb am Ende!' },
      { type:2, sentence:'___ = hier',
        options:['Injâ','Ânjâ','Kojâ','Haminajâ'],
        correct:'Injâ', explanation:'Injâ = hier. Ânjâ = dort.' },
      { type:2, sentence:'___ = dort',
        options:['Ânjâ','Injâ','Bâlâ','Pâyin'],
        correct:'Ânjâ', explanation:'Ânjâ = dort. Injâ = hier.' },
      { type:5, farsi:'Dastshui kojâst?',
        options:['Wo ist die Toilette?','Wo ist das Haus?','Wo ist der Markt?','Was ist das?'],
        correct:'Wo ist die Toilette?',
        explanation:'Dastshui = Toilette/Waschraum. kojâst = wo ist.' },
      { type:1, de:'Ich bin hier.',
        tiles:['Man','injâ','hastam','.'], solution:['Man','injâ','hastam','.'],
        explanation:'Man injâ hastam = Ich bin hier. Subjekt → Ort → Verb.' },
      { type:2, sentence:'Bâzâr ___ (Der Markt ist dort.)',
        options:['ânjâst','injâst','kojâst','nist'],
        correct:'ânjâst', explanation:'ânjâst = ânjâ + ast = "dort ist". Kurze Verbindungsform.' },
      { type:5, farsi:'Hotel kojâst?',
        options:['Wo ist das Hotel?','Wie heißt das Hotel?','Gibt es ein Hotel?','Was kostet das Hotel?'],
        correct:'Wo ist das Hotel?',
        explanation:'Hotel = hotel (Lehnwort). kojâst = wo ist.' },
    ]
  },

  {
    id: 6, title: 'Farben & Adjektive', phase: 1,
    tasks: [
      { type:2, sentence:'ketâb___ bozorg (das große Buch)',
        options:['-e','-ye','-râ','-hâ'],
        correct:'-e', explanation:'Nach einem Konsonanten (b) steht die Ezâfe -e.' },
      { type:1, de:'der rote Apfel',
        tiles:['sib-e','germez'], solution:['sib-e','germez'],
        explanation:'Adjektiv nach Nomen mit Ezâfe: sib-e germez = Apfel-EZ rot.' },
      { type:2, sentence:'___ = weiß',
        options:['Sefid','Siyâh','Germez','Zard'],
        correct:'Sefid', explanation:'Sefid = weiß. Siyâh = schwarz.' },
      { type:2, sentence:'___ = blau',
        options:['Âbi','Sabz','Zard','Sefid'],
        correct:'Âbi', explanation:'Âbi = blau (wörtlich: wasserfarben, von âb = Wasser).' },
      { type:1, de:'das blaue Auto',
        tiles:['mâshin-e','âbi'], solution:['mâshin-e','âbi'],
        explanation:'mâshin-e âbi: Adjektiv kommt NACH dem Nomen mit Ezâfe.' },
      { type:5, farsi:'Otâq-e kuchek.',
        options:['das kleine Zimmer','das große Zimmer','das rote Zimmer','ein Zimmer'],
        correct:'das kleine Zimmer',
        explanation:'kuchek = klein. otâq-e kuchek = kleines Zimmer.' },
      { type:2, sentence:'khâne___ bozorg (das große Haus)',
        options:['-ye','-e','-râ','-ân'],
        correct:'-ye', explanation:'khâne endet auf -e (Vokal) → Ezâfe wird -ye.' },
      { type:1, de:'der kalte Tee',
        tiles:['chây-e','sard'], solution:['chây-e','sard'],
        explanation:'chây-e sard = Tee-EZ kalt = der kalte Tee.' },
    ]
  },

  {
    id: 7, title: 'Essen & Trinken I', phase: 1,
    tasks: [
      { type:2, sentence:'___ = Wasser',
        options:['Âb','Nân','Chây','Mast'],
        correct:'Âb', explanation:'Âb = Wasser. Â = langes offenes A.' },
      { type:2, sentence:'___ = Brot',
        options:['Nân','Berenj','Gosht','Mive'],
        correct:'Nân', explanation:'Nân = Brot. Flachbrot ist die häufigste Form im Iran.' },
      { type:1, de:'ein Glas Wasser bitte',
        tiles:['Yek','livân','âb','lotfan'], solution:['Yek','livân','âb','lotfan'],
        explanation:'lotfan = bitte. Am Ende des Satzes.' },
      { type:2, sentence:'___ = Reis',
        options:['Berenj','Gosht','Nân','Mâhi'],
        correct:'Berenj', explanation:'Berenj = Reis. Zentrales Nahrungsmittel im Iran.' },
      { type:5, farsi:'Man gushneh hastam.',
        options:['Ich habe Hunger.','Ich habe Durst.','Ich bin müde.','Ich bin gut.'],
        correct:'Ich habe Hunger.',
        explanation:'gushneh = hungrig. Man gushneh hastam = ich bin hungrig.' },
      { type:2, sentence:'___ = Fleisch',
        options:['Gosht','Mive','Sabzi','Berenj'],
        correct:'Gosht', explanation:'Gosht = Fleisch.' },
      { type:1, de:'ein Tee bitte',
        tiles:['Yek','chây','lotfan'], solution:['Yek','chây','lotfan'],
        explanation:'Yek chây lotfan = einen Tee bitte.' },
      { type:5, farsi:'Khoshmazeh bud!',
        options:['Es war köstlich!','Es war kalt!','Es war teuer!','Es war schlecht!'],
        correct:'Es war köstlich!',
        explanation:'Khoshmazeh = lecker/köstlich. bud = war (Vergangenheit von sein).' },
    ]
  },

  {
    id: 8, title: 'Ezâfe Grundlagen', phase: 1,
    tasks: [
      { type:2, sentence:'mard___ khub (der gute Mann)',
        options:['-e','-ye','-hâ','-ân'],
        correct:'-e', explanation:'mard endet auf Konsonant → Ezâfe -e.' },
      { type:2, sentence:'âqâ___ Rezai (Herr Rezai)',
        options:['-ye','-e','-râ','-i'],
        correct:'-ye', explanation:'âqâ endet auf -â (Vokal) → Ezâfe -ye.' },
      { type:1, de:'das alte Haus',
        tiles:['khâne-ye','qadim'], solution:['khâne-ye','qadim'],
        explanation:'khâne endet auf -e (Vokal) → khâne-ye. qadim = alt.' },
      { type:5, farsi:'Mard-e bozorg.',
        options:['der große Mann','der Mann ist groß','ein großer Baum','der alte Mann'],
        correct:'der große Mann',
        explanation:'mard-e bozorg = Mann-EZ groß = der große Mann.' },
      { type:2, sentence:'ketâb___ bozorg-___ siyâh (das große schwarze Buch)',
        options:['-e / -e','-ye / -ye','-e / -ye','-râ / -e'],
        correct:'-e / -e', explanation:'Beide Nomen/Adjektive enden auf Konsonant → je -e.' },
      { type:1, de:'das warme Wetter',
        tiles:['havâ-ye','garm'], solution:['havâ-ye','garm'],
        explanation:'havâ endet auf -â → havâ-ye. garm = warm.' },
      { type:5, farsi:'Otâq-e sard.',
        options:['das kalte Zimmer','das heiße Zimmer','ein Zimmer','das große Zimmer'],
        correct:'das kalte Zimmer',
        explanation:'sard = kalt. otâq-e sard = das kalte Zimmer.' },
      { type:2, sentence:'bâzu___ man (mein Arm)',
        options:['-ye','-e','-râ','-hâ'],
        correct:'-ye', explanation:'bâzu endet auf -u (Vokal) → Ezâfe -ye.' },
    ]
  },

  {
    id: 9, title: 'Mein, dein, sein…', phase: 1,
    tasks: [
      { type:1, de:'mein Buch',
        tiles:['ketâb-e','man'], solution:['ketâb-e','man'],
        explanation:'Besitz: Besessenes + Ezâfe + Besitzer. ketâb-e man = mein Buch.' },
      { type:1, de:'deine Mutter',
        tiles:['mâdar-e','to'], solution:['mâdar-e','to'],
        explanation:'to = du. mâdar-e to = deine Mutter.' },
      { type:2, sentence:'___ = sein/ihr Haus',
        options:['khâne-ye u','khâne-ye man','khâne-ye to','khâne-ye mâ'],
        correct:'khâne-ye u', explanation:'u = er/sie (kein Unterschied). khâne-ye u = sein/ihr Haus.' },
      { type:5, farsi:'Pedar-e mâ.',
        options:['unser Vater','mein Vater','euer Vater','ihr Vater (Pl.)'],
        correct:'unser Vater',
        explanation:'mâ = wir. pedar-e mâ = unser Vater.' },
      { type:1, de:'euer Auto',
        tiles:['mâshin-e','shomâ'], solution:['mâshin-e','shomâ'],
        explanation:'shomâ = ihr / Sie (Höflichkeit). mâshin-e shomâ = euer/Ihr Auto.' },
      { type:2, sentence:'___ = ihr Buch (Plural)',
        options:['ketâb-e ânhâ','ketâb-e u','ketâb-e mâ','ketâb-e to'],
        correct:'ketâb-e ânhâ', explanation:'ânhâ = sie (Plural). ketâb-e ânhâ = ihr Buch.' },
      { type:5, farsi:'Ketâb-e man kojâst?',
        options:['Wo ist mein Buch?','Was ist mein Buch?','Wessen Buch ist das?','Hast du mein Buch?'],
        correct:'Wo ist mein Buch?',
        explanation:'ketâb-e man = mein Buch. kojâst = wo ist.' },
      { type:1, de:'die Tür seines Hauses',
        tiles:['dar-e','khâne-ye','u'], solution:['dar-e','khâne-ye','u'],
        explanation:'Ezâfe-Kette: dar-e khâne-ye u = Tür-EZ Haus-EZ er.' },
    ]
  },

  {
    id: 10, title: 'Phase-1-Wiederholung', phase: 1,
    tasks: [
      { type:5, farsi:'Man doktor hastam.',
        options:['Ich bin Arzt.','Du bist Arzt.','Er ist Arzt.','Wir sind Ärzte.'],
        correct:'Ich bin Arzt.',
        explanation:'man = ich, doktor = Arzt, hastam = ich bin.' },
      { type:1, de:'das große schwarze Buch',
        tiles:['ketâb-e','bozorg-e','siyâh'], solution:['ketâb-e','bozorg-e','siyâh'],
        explanation:'Jedes Adjektiv bekommt seine eigene Ezâfe.' },
      { type:2, sentence:'Se ketâb___ (drei Bücher)',
        options:['[kein Suffix]','-hâ','-ân','-e'],
        correct:'[kein Suffix]', explanation:'Nach Zahlen kein Plural! Se ketâb = drei Buch.' },
      { type:2, sentence:'Man nist___ (Ich bin nicht ...)',
        options:['-am','-i','-id','-and'],
        correct:'-am', explanation:'nist + am = nistam = ich bin nicht.' },
      { type:5, farsi:'Khahar-e to kojâst?',
        options:['Wo ist deine Schwester?','Wer ist deine Schwester?','Was macht deine Schwester?','Hast du eine Schwester?'],
        correct:'Wo ist deine Schwester?',
        explanation:'khahar-e to = deine Schwester. kojâst = wo ist.' },
      { type:1, de:'meine Familie',
        tiles:['khânevâde-ye','man'], solution:['khânevâde-ye','man'],
        explanation:'khânevâde = Familie. Endet auf -e → khânevâde-ye.' },
      { type:2, sentence:'âqâ___ Ahmad (Herr Ahmad)',
        options:['-ye','-e','-râ','-hâ'],
        correct:'-ye', explanation:'Eigenname als Ezâfe-Glied: âqâ-ye Ahmad.' },
      { type:5, farsi:'Nân va âb.',
        options:['Brot und Wasser','Brot und Fleisch','Wasser und Obst','Brot und Tee'],
        correct:'Brot und Wasser',
        explanation:'va = und. nân = Brot, âb = Wasser.' },
      { type:1, de:'Wo ist das Hotel?',
        tiles:['Hotel','kojâst','?'], solution:['Hotel','kojâst','?'],
        explanation:'Einfache Frage: Nomen + kojâst?' },
    ]
  },

  /* ════════════════════════════════════════
     PHASE 2 — AUFBAU (Level 11–25)
  ════════════════════════════════════════ */

  {
    id: 11, title: 'Ich gehe, du gehst', phase: 2,
    tasks: [
      { type:2, sentence:'Man mi-rav___ (Ich gehe.)',
        options:['-am','-i','-ad','-im'],
        correct:'-am', explanation:'mi- + Präsensstamm (rav) + Endung. 1. Sg: -am.' },
      { type:1, de:'Du gehst.',
        tiles:['To','mi-ravi','.'], solution:['To','mi-ravi','.'],
        explanation:'mi-rav-i = du gehst. Präsensstamm von raftan = rav.' },
      { type:2, sentence:'U mi-rav___ (Er/Sie geht.)',
        options:['-ad','-am','-i','-id'],
        correct:'-ad', explanation:'3. Person Singular Präsens: -ad.' },
      { type:5, farsi:'Mâ mi-ravim.',
        options:['Wir gehen.','Ihr geht.','Sie gehen.','Ich gehe.'],
        correct:'Wir gehen.',
        explanation:'mi-rav-im = wir gehen. mâ = wir.' },
      { type:1, de:'Ihr geht.',
        tiles:['Shomâ','mi-ravid','.'], solution:['Shomâ','mi-ravid','.'],
        explanation:'mi-rav-id = ihr geht / Sie gehen.' },
      { type:2, sentence:'Ânhâ mi-rav___ (Sie gehen.)',
        options:['-and','-ad','-im','-id'],
        correct:'-and', explanation:'3. Person Plural: -and.' },
      { type:5, farsi:'Man be bâzâr mi-ravam.',
        options:['Ich gehe zum Markt.','Ich gehe nach Hause.','Ich bin auf dem Markt.','Wir gehen zum Markt.'],
        correct:'Ich gehe zum Markt.',
        explanation:'be = nach/zu. bâzâr = Markt. mi-ravam = ich gehe.' },
      { type:1, de:'Sie geht nach Hause.',
        tiles:['U','be','khâne','mi-ravad','.'], solution:['U','be','khâne','mi-ravad','.'],
        explanation:'be khâne = nach Hause. Verb ans Ende!' },
    ]
  },

  {
    id: 12, title: 'Das mi-Präfix', phase: 2,
    tasks: [
      { type:2, sentence:'Man mi-khân___ (Ich lese.)',
        options:['-am','-i','-ad','-im'],
        correct:'-am', explanation:'Präsensstamm von khândan = khân. mi-khân-am = ich lese.' },
      { type:1, de:'Er liest ein Buch.',
        tiles:['U','ketâb','mi-khânad','.'], solution:['U','ketâb','mi-khânad','.'],
        explanation:'SOV: Subjekt → Objekt → Verb. mi-khân-ad = er liest.' },
      { type:2, sentence:'Man mi-kon___ (Ich tue/mache.)',
        options:['-am','-i','-id','-and'],
        correct:'-am', explanation:'Präsensstamm von kardan = kon. mi-kon-am = ich mache.' },
      { type:5, farsi:'U mi-khânad.',
        options:['Er/Sie liest.','Er/Sie geht.','Er/Sie spricht.','Er/Sie schreibt.'],
        correct:'Er/Sie liest.',
        explanation:'mi-khân-ad = er/sie liest. (von khândan = lesen).' },
      { type:2, sentence:'Ânhâ mi-nevis___ (Sie schreiben.)',
        options:['-and','-ad','-im','-id'],
        correct:'-and', explanation:'Präsensstamm von neveshtan = nevis. mi-nevis-and = sie schreiben.' },
      { type:1, de:'Wir essen.',
        tiles:['Mâ','mi-khorim','.'], solution:['Mâ','mi-khorim','.'],
        explanation:'Präsensstamm von khordan = khor. mi-khor-im = wir essen.' },
      { type:5, farsi:'To chizi mi-guyid?',
        options:['Sagst du etwas?','Machst du etwas?','Siehst du etwas?','Weißt du etwas?'],
        correct:'Sagst du etwas?',
        explanation:'mi-guyid = ihr sagt / Sie sagen (von goftan, Stamm: gu). Chizi = etwas.' },
      { type:2, sentence:'Man dâr___ (Ich habe.) — kein mi-!',
        options:['dâram','mi-dâram','dârim','dârâm'],
        correct:'dâram', explanation:'dâshtan (haben) nimmt kein mi-! dâr-am = ich habe.' },
    ]
  },

  {
    id: 13, title: 'Das Buch — râ!', phase: 2,
    tasks: [
      { type:2, sentence:'Man ketâb ___ khândam. (Ich las das Buch.)',
        options:['râ','—','ra','be'],
        correct:'râ', explanation:'Bestimmtes direktes Objekt bekommt râ. ketâb râ = das Buch (akkusativ).' },
      { type:1, de:'Ali kaufte das Auto.',
        tiles:['Ali','mâshin','râ','kharid','.'], solution:['Ali','mâshin','râ','kharid','.'],
        explanation:'Râ steht direkt nach dem Objekt, vor dem Verb.' },
      { type:2, sentence:'Man mâhi khordam. (Ich aß ___)',
        options:['Fisch (unbestimmt)','den Fisch (bestimmt)','einen bestimmten Fisch','viel Fisch'],
        correct:'Fisch (unbestimmt)', explanation:'Kein râ = unbestimmtes Objekt. Man mâhi khordam = ich aß Fisch (generisch).' },
      { type:5, farsi:'Mâ film râ didim.',
        options:['Wir sahen den Film.','Wir sahen einen Film.','Wir sahen nicht.','Er sah den Film.'],
        correct:'Wir sahen den Film.',
        explanation:'film râ = den Film (bestimmt + râ). didim = wir sahen.' },
      { type:2, sentence:'Ali ___ ketâb dâd. (Ali gab ein Buch.)',
        options:['—','râ','be','az'],
        correct:'—', explanation:'Unbestimmtes Objekt (ein Buch) bekommt kein râ.' },
      { type:1, de:'Er sah uns.',
        tiles:['U','mârâ','did','.'], solution:['U','mârâ','did','.'],
        explanation:'mârâ = mâ râ = uns. Pronomen + râ verschmelzen oft.' },
      { type:5, farsi:'Man torâ dust dâram.',
        options:['Ich habe dich lieb.','Du hast mich lieb.','Ich liebe ihn.','Wir lieben dich.'],
        correct:'Ich habe dich lieb.',
        explanation:'torâ = to râ = dich. dust dâram = ich mag/liebe.' },
      { type:2, sentence:'Man in ketâb ___ mikhâham khândan.',
        options:['râ','—','be','az'],
        correct:'râ', explanation:'in ketâb = dieses Buch (bestimmt durch Demonstrativum) → râ nötig.' },
    ]
  },

  {
    id: 14, title: 'Plural mit -hâ', phase: 2,
    tasks: [
      { type:2, sentence:'ketâb → ___ (Plural)',
        options:['ketâb-hâ','ketâb-ân','ketâb-e','ketâb-i'],
        correct:'ketâb-hâ', explanation:'-hâ ist die universelle Pluralendung.' },
      { type:1, de:'die Bücher',
        tiles:['ketâb-hâ'], solution:['ketâb-hâ'],
        explanation:'ketâb + -hâ = ketâb-hâ.' },
      { type:2, sentence:'khâne → ___ (Plural)',
        options:['khâne-hâ','khâne-ân','khâne-ye','khâne-i'],
        correct:'khâne-hâ', explanation:'-hâ ist immer korrekt, auch nach Vokal.' },
      { type:5, farsi:'Mard-hâ mi-ravand.',
        options:['Die Männer gehen.','Ein Mann geht.','Der Mann geht.','Männer laufen.'],
        correct:'Die Männer gehen.',
        explanation:'mard-hâ = die Männer. mi-ravand = sie gehen.' },
      { type:2, sentence:'dokhtar → ___ (formeller Plural)',
        options:['dokhtar-ân','dokhtar-hâ','dokhtar-e','dokhtar-ye'],
        correct:'dokhtar-ân', explanation:'-ân ist die formelle Pluralendung für belebte Nomen.' },
      { type:2, sentence:'dâneshju → ___ (Plural mit -ân)',
        options:['dâneshju-yân','dâneshju-ân','dâneshju-hâ-ân','dâneshju-ye'],
        correct:'dâneshju-yân', explanation:'Vokal-Endung -u + -ân → y-Gleitlaut nötig: dâneshju-yân.' },
      { type:5, farsi:'Ketâb-hâ-ye bozorg.',
        options:['die großen Bücher','das große Buch','ein großes Buch','die Bücher sind groß'],
        correct:'die großen Bücher',
        explanation:'Plural (-hâ) + Ezâfe (-ye) + Adjektiv: ketâb-hâ-ye bozorg.' },
      { type:1, de:'meine Bücher',
        tiles:['ketâb-hâ-ye','man'], solution:['ketâb-hâ-ye','man'],
        explanation:'Plural + Ezâfe: ketâb-hâ-ye man = meine Bücher.' },
    ]
  },

  {
    id: 15, title: 'Im Restaurant', phase: 2,
    tasks: [
      { type:5, farsi:'Menoo dârid?',
        options:['Haben Sie eine Speisekarte?','Was haben Sie heute?','Haben Sie einen Tisch?','Haben Sie Reis?'],
        correct:'Haben Sie eine Speisekarte?',
        explanation:'Menoo = Speisekarte (aus dem Französischen). dârid = Sie haben.' },
      { type:1, de:'Die Rechnung bitte.',
        tiles:['Hisâb','lotfan','.'], solution:['Hisâb','lotfan','.'],
        explanation:'Hisâb = Rechnung. lotfan = bitte.' },
      { type:2, sentence:'___ = ohne Fleisch',
        options:['Bê gosht','Bâ gosht','Gosht-e khub','Gosht-hâ'],
        correct:'Bê gosht', explanation:'Bê = ohne. gosht = Fleisch. Bê gosht = ohne Fleisch.' },
      { type:5, farsi:'In che ghazâyiye?',
        options:['Was ist das für ein Gericht?','Wie viel kostet das?','Ist es scharf?','Schmeckt das gut?'],
        correct:'Was ist das für ein Gericht?',
        explanation:'in = das/dies. che = was. ghazâ = Essen. -yiye = ist es?' },
      { type:1, de:'Es war köstlich!',
        tiles:['Khoshmazeh','bud','!'], solution:['Khoshmazeh','bud','!'],
        explanation:'Khoshmazeh = köstlich. bud = war (Vergangenheit).' },
      { type:2, sentence:'___ = scharf (würzig)',
        options:['Tund','Sard','Garm','Shirin'],
        correct:'Tund', explanation:'Tund = scharf/würzig. Sard = kalt. Garm = warm.' },
      { type:5, farsi:'Yek chây lotfan.',
        options:['Einen Tee bitte.','Ein Wasser bitte.','Eine Speisekarte bitte.','Die Rechnung bitte.'],
        correct:'Einen Tee bitte.',
        explanation:'chây = Tee. lotfan = bitte.' },
      { type:1, de:'Ich möchte Reis.',
        tiles:['Man','berenj','mikhâham','.'], solution:['Man','berenj','mikhâham','.'],
        explanation:'SOV: man → berenj (Objekt) → mikhâham (ich möchte).' },
    ]
  },

  {
    id: 16, title: 'Einkaufen', phase: 2,
    tasks: [
      { type:2, sentence:'___ = wie viel kostet?',
        options:['Chand-e?','Chi-e?','Kojâst?','Chetore?'],
        correct:'Chand-e?', explanation:'Chand = wie viel. Chand-e? = Wie viel kostet es?' },
      { type:1, de:'Das ist teuer.',
        tiles:['In','gerân','ast','.'], solution:['In','gerân','ast','.'],
        explanation:'gerân = teuer. in = das/dies. in gerân ast = das ist teuer.' },
      { type:2, sentence:'___ = billig',
        options:['Arzân','Gerân','Khub','Bozorg'],
        correct:'Arzân', explanation:'Arzân = billig. Gerân = teuer.' },
      { type:5, farsi:'In râ mikhâham.',
        options:['Das möchte ich.','Das habe ich.','Das sehe ich.','Das kenne ich.'],
        correct:'Das möchte ich.',
        explanation:'in râ = das (bestimmt + râ). mikhâham = ich möchte.' },
      { type:1, de:'Geben Sie mir das bitte.',
        tiles:['In','râ','be','man','bedahid','lotfan','.'], solution:['In','râ','be','man','bedahid','lotfan','.'],
        explanation:'in râ = das. be man = mir. bedahid = geben Sie. lotfan = bitte.' },
      { type:2, sentence:'___ = Markt / Basar',
        options:['Bâzâr','Ketâb-forushi','Dâru-khâne','Mâshin'],
        correct:'Bâzâr', explanation:'Bâzâr = Markt. Dieses persische Wort ist in viele Sprachen eingegangen.' },
      { type:5, farsi:'Man in mive râ kharid.',
        options:['Ich kaufte dieses Obst.','Ich kaufte das Fleisch.','Er kaufte dieses Obst.','Ich verkaufte dieses Obst.'],
        correct:'Ich kaufte dieses Obst.',
        explanation:'man = ich. in mive râ = dieses Obst (bestimmt). kharid = kaufte.' },
      { type:2, sentence:'Mive-hâ ___ gerân hastand. (Das Obst ist teuer.)',
        options:['—','râ','be','az'],
        correct:'—', explanation:'Als Subjekt bekommt mive-hâ kein râ — nur direkte Objekte bekommen râ.' },
    ]
  },

  {
    id: 17, title: 'Unregelmäßige Verben I', phase: 2,
    tasks: [
      { type:2, sentence:'raftan — Präsensstamm: ___',
        options:['rav','raft','raf','rân'],
        correct:'rav', explanation:'raftan (gehen): Vergangenheitsstamm raft, Präsensstamm rav.' },
      { type:2, sentence:'âmadan — Präsensstamm: ___',
        options:['â(y)','âmad','âm','âd'],
        correct:'â(y)', explanation:'âmadan (kommen): Stamm â, vor Endungen mit y-Gleitlaut: mi-yâ-m.' },
      { type:5, farsi:'Man mi-yâm.',
        options:['Ich komme.','Ich gehe.','Ich bin.','Ich mache.'],
        correct:'Ich komme.',
        explanation:'âmadan (kommen), Stamm â + y-Gleitlaut: mi-yâ-m = ich komme.' },
      { type:2, sentence:'kardan — Präsensstamm: ___',
        options:['kon','kard','kar','kan'],
        correct:'kon', explanation:'kardan (machen/tun): Stamm kon. mi-kon-am = ich mache.' },
      { type:1, de:'Ich sehe.',
        tiles:['Man','mi-binam','.'], solution:['Man','mi-binam','.'],
        explanation:'didan (sehen): Stamm bin. mi-bin-am = ich sehe.' },
      { type:2, sentence:'goftan — Präsensstamm: ___',
        options:['gu','goft','gof','gav'],
        correct:'gu', explanation:'goftan (sagen): Stamm gu. mi-gu-yam = ich sage.' },
      { type:5, farsi:'U mi-gu-yad.',
        options:['Er/Sie sagt.','Er/Sie geht.','Er/Sie liest.','Er/Sie sieht.'],
        correct:'Er/Sie sagt.',
        explanation:'goftan (sagen), Stamm gu + y-Gleitlaut + -ad = mi-gu-yad.' },
      { type:1, de:'Wir nehmen das.',
        tiles:['Mâ','in','râ','mi-girim','.'], solution:['Mâ','in','râ','mi-girim','.'],
        explanation:'gereftan (nehmen): Stamm gir. mi-gir-im = wir nehmen.' },
    ]
  },

  {
    id: 18, title: 'Fehler finden I', phase: 2,
    tasks: [
      { type:6, prompt:'Fehlerhafter Satz: "Man ketâb bozorg râ khândam."',
        options:[
          'Man ketâb-e bozorg râ khândam.',
          'Man ketâb bozorg khândam.',
          'Man râ ketâb-e bozorg khândam.',
          'Man ketâb-e bozorg khândam râ.',
        ],
        correct:'Man ketâb-e bozorg râ khândam.',
        explanation:'Adjektive werden mit Ezâfe angehängt: ketâb-e bozorg.' },
      { type:6, prompt:'Fehlerhafter Satz: "Ali ketâb mikhânad râ."',
        options:[
          'Ali ketâb râ mikhânad.',
          'Ali râ ketâb mikhânad.',
          'Râ Ali ketâb mikhânad.',
          'Ali ketâb mikhânad.',
        ],
        correct:'Ali ketâb râ mikhânad.',
        explanation:'Râ steht direkt nach dem Objekt, nicht nach dem Verb.' },
      { type:6, prompt:'Fehlerhafter Satz: "Man mi-dâram yek ketâb."',
        options:[
          'Man yek ketâb dâram.',
          'Man yek ketâb mi-dâram.',
          'Yek ketâb man dâram.',
          'Man dâram yek ketâb.',
        ],
        correct:'Man yek ketâb dâram.',
        explanation:'dâshtan (haben) nimmt kein mi-! Außerdem SOV: man → ketâb → dâram.' },
      { type:6, prompt:'Fehlerhafter Satz: "Se ketâb-hâ ru miz hastand."',
        options:[
          'Se ketâb ru miz hast.',
          'Se ketâb-hâ ru miz ast.',
          'Se ketâb ru miz hastand.',
          'Se ketâb-hâ ru mizan hastand.',
        ],
        correct:'Se ketâb ru miz hast.',
        explanation:'Nach Zahlen kein Plural! Se ketâb (nicht ketâb-hâ).' },
      { type:6, prompt:'Fehlerhafter Satz: "U khâne-e bozorg dârad."',
        options:[
          'U khâne-ye bozorg dârad.',
          'U khâne-e bozorg ast.',
          'U khâne bozorg-e dârad.',
          'U khâne-ye bozorg-e dârad.',
        ],
        correct:'U khâne-ye bozorg dârad.',
        explanation:'khâne endet auf Vokal -e → Ezâfe wird -ye, nicht -e.' },
      { type:6, prompt:'Fehlerhafter Satz: "Man be khâne mi-yam nemikonam."',
        options:[
          'Man be khâne nemi-yam.',
          'Man nemi-yam be khâne nemikonam.',
          'Man be khâne mi-yam.',
          'Man be khâne nemiyam nistam.',
        ],
        correct:'Man be khâne nemi-yam.',
        explanation:'Verneinung im Präsens: mi- wird durch nemi- ersetzt. Ein Verb reicht.' },
      { type:6, prompt:'Fehlerhafter Satz: "Pedar man doktor ast."',
        options:[
          'Pedar-e man doktor ast.',
          'Man pedar doktor ast.',
          'Pedar man-e doktor ast.',
          'Man-e pedar doktor ast.',
        ],
        correct:'Pedar-e man doktor ast.',
        explanation:'Besitz mit Ezâfe: pedar-e man, nicht pedar man.' },
      { type:6, prompt:'Fehlerhafter Satz: "Ânhâ râ ketâb mikhânand."',
        options:[
          'Ânhâ ketâb râ mikhânand.',
          'Râ ânhâ ketâb mikhânand.',
          'Ânhâ ketâb mikhânand râ.',
          'Ânhâ râ mikhânand ketâb.',
        ],
        correct:'Ânhâ ketâb râ mikhânand.',
        explanation:'Râ steht nach dem Objekt (ketâb), nicht vor dem Subjekt.' },
    ]
  },

  {
    id: 19, title: 'Reisen & Transport', phase: 2,
    tasks: [
      { type:5, farsi:'Man be Irân mi-ravam.',
        options:['Ich fahre in den Iran.','Ich komme aus dem Iran.','Ich bin im Iran.','Wir fahren in den Iran.'],
        correct:'Ich fahre in den Iran.',
        explanation:'be = nach/in (Richtung). mi-ravam = ich gehe/fahre.' },
      { type:2, sentence:'___ = Flugzeug',
        options:['Havâpeymâ','Otoboos','Tâksi','Ghatar'],
        correct:'Havâpeymâ', explanation:'Havâpeymâ = Flugzeug (wörtlich: Himmelschiff).' },
      { type:1, de:'Ich möchte ein Ticket kaufen.',
        tiles:['Man','yek','bilit','mikhâham','bekhar-am','.'], solution:['Man','yek','bilit','mikhâham','bekhar-am','.'],
        explanation:'bilit = Ticket. mikhâham + Infinitiv = ich möchte + Verb.' },
      { type:2, sentence:'___ = Bahnhof',
        options:['Istgâh-e ghatar','Forugâh','Meydan','Khiyâbân'],
        correct:'Istgâh-e ghatar', explanation:'istgâh = Station. ghatar = Zug. istgâh-e ghatar = Bahnhof.' },
      { type:5, farsi:'Tâksi dârid?',
        options:['Haben Sie ein Taxi?','Wo ist das Taxi?','Ich brauche ein Taxi.','Was kostet das Taxi?'],
        correct:'Haben Sie ein Taxi?',
        explanation:'dârid = Sie haben. Tâksi dârid? = Haben Sie ein Taxi?' },
      { type:1, de:'Zum Flughafen bitte.',
        tiles:['Be','forugâh','lotfan','.'], solution:['Be','forugâh','lotfan','.'],
        explanation:'be = nach/zu. forugâh = Flughafen.' },
      { type:2, sentence:'___ = links',
        options:['Chap','Râst','Mostaghim','Bâlâ'],
        correct:'Chap', explanation:'Chap = links. Râst = rechts. Mostaghim = geradeaus.' },
      { type:5, farsi:'Mostaghim beravid.',
        options:['Gehen Sie geradeaus.','Gehen Sie links.','Gehen Sie zurück.','Gehen Sie nach rechts.'],
        correct:'Gehen Sie geradeaus.',
        explanation:'mostaghim = geradeaus. beravid = gehen Sie (Imperativ Plural).' },
    ]
  },

  {
    id: 20, title: 'Uhrzeit & Datum', phase: 2,
    tasks: [
      { type:2, sentence:'___ = Uhr / Stunde',
        options:['Sâat','Daghighe','Ruz','Hafteh'],
        correct:'Sâat', explanation:'Sâat = Stunde / Uhr. Sâat chand-e? = Wie viel Uhr ist es?' },
      { type:5, farsi:'Sâat chand-e?',
        options:['Wie viel Uhr ist es?','Wie lange dauert es?','Wann kommst du?','Wie viele Stunden?'],
        correct:'Wie viel Uhr ist es?',
        explanation:'sâat = Uhr/Stunde. chand = wie viel. chand-e = wie viel ist?' },
      { type:2, sentence:'___ = morgen',
        options:['Fardâ','Diruz','Emruz','Dishab'],
        correct:'Fardâ', explanation:'Fardâ = morgen. Emruz = heute. Diruz = gestern.' },
      { type:2, sentence:'___ = Woche',
        options:['Hafteh','Mâh','Sâl','Ruz'],
        correct:'Hafteh', explanation:'Hafteh = Woche (wörtlich: sieben, weil 7 Tage).' },
      { type:5, farsi:'Emruz chand-shanbeh ast?',
        options:['Was ist heute für ein Wochentag?','Welches Datum ist heute?','Wie viele Tage hat der Monat?','Wann ist Nowruz?'],
        correct:'Was ist heute für ein Wochentag?',
        explanation:'chand-shanbeh = welcher Tag der Woche. emruz = heute.' },
      { type:1, de:'heute Morgen',
        tiles:['emruz','sobh'], solution:['emruz','sobh'],
        explanation:'sobh = Morgen. emruz sobh = heute Morgen.' },
      { type:2, sentence:'___ = Jahr',
        options:['Sâl','Mâh','Hafteh','Ruz'],
        correct:'Sâl', explanation:'Sâl = Jahr. Nowruz ist das persische Neujahr.' },
      { type:5, farsi:'Diruz bârun âmad.',
        options:['Gestern regnete es.','Heute regnet es.','Morgen kommt Regen.','Es hat geregnet.'],
        correct:'Gestern regnete es.',
        explanation:'diruz = gestern. bârun âmad = es regnete (Regen kam).' },
    ]
  },

  {
    id: 21, title: 'Körper & Gesundheit', phase: 2,
    tasks: [
      { type:2, sentence:'___ = Kopf',
        options:['Sar','Dast','Pâ','Cheshm'],
        correct:'Sar', explanation:'Sar = Kopf.' },
      { type:5, farsi:'Dastam dard mi-konad.',
        options:['Meine Hand schmerzt.','Mein Kopf schmerzt.','Mein Bein schmerzt.','Mein Rücken schmerzt.'],
        correct:'Meine Hand schmerzt.',
        explanation:'dast = Hand. dard mi-konad = es schmerzt (wörtlich: Schmerz macht).' },
      { type:2, sentence:'___ = Arzt / Ärztin',
        options:['Doktor','Dâru','Bimârestân','Dard'],
        correct:'Doktor', explanation:'Doktor = Arzt. Lehnwort.' },
      { type:1, de:'Ich bin krank.',
        tiles:['Man','mariz','hastam','.'], solution:['Man','mariz','hastam','.'],
        explanation:'mariz = krank. Man mariz hastam = ich bin krank.' },
      { type:2, sentence:'___ = Krankenhaus',
        options:['Bimârestân','Dâru-khâne','Doktor','Dard'],
        correct:'Bimârestân', explanation:'Bimârestân = Krankenhaus. bimâr = krank, -estân = Ort/Land.' },
      { type:5, farsi:'Saram dard mi-konad.',
        options:['Ich habe Kopfschmerzen.','Ich habe Bauchschmerzen.','Mein Bein tut weh.','Ich bin krank.'],
        correct:'Ich habe Kopfschmerzen.',
        explanation:'sar = Kopf. dard mi-konad = tut weh.' },
      { type:1, de:'Ich brauche einen Arzt.',
        tiles:['Man','be','doktor','niâz','dâram','.'], solution:['Man','be','doktor','niâz','dâram','.'],
        explanation:'niâz dâshtan = brauchen. be doktor niâz dâram = ich brauche einen Arzt.' },
      { type:2, sentence:'___ = Medikament',
        options:['Dâru','Dard','Sar','Bimâr'],
        correct:'Dâru', explanation:'Dâru = Medikament/Arznei.' },
    ]
  },

  {
    id: 22, title: 'Unregelmäßige Verben II', phase: 2,
    tasks: [
      { type:2, sentence:'dâdan — Präsensstamm: ___',
        options:['deh','dâd','dân','dâr'],
        correct:'deh', explanation:'dâdan (geben): Stamm deh. mi-deh-am = ich gebe.' },
      { type:5, farsi:'Man ketâb mi-deham.',
        options:['Ich gebe das Buch.','Ich nehme das Buch.','Ich lese das Buch.','Ich habe das Buch.'],
        correct:'Ich gebe das Buch.',
        explanation:'mi-deh-am = ich gebe (von dâdan).' },
      { type:2, sentence:'shodan — Präsensstamm: ___',
        options:['shav','shod','sha','sho'],
        correct:'shav', explanation:'shodan (werden): Stamm shav. mi-shav-am = ich werde.' },
      { type:1, de:'Er wird Arzt.',
        tiles:['U','doktor','mi-shavad','.'], solution:['U','doktor','mi-shavad','.'],
        explanation:'mi-shav-ad = er/sie wird.' },
      { type:2, sentence:'khâstan — Präsensstamm: ___',
        options:['khâh','khâst','khâ','khân'],
        correct:'khâh', explanation:'khâstan (wollen): Stamm khâh. mi-khâh-am = ich will.' },
      { type:5, farsi:'Man mi-khâham bekhâbam.',
        options:['Ich möchte schlafen.','Ich möchte essen.','Ich möchte gehen.','Ich will lesen.'],
        correct:'Ich möchte schlafen.',
        explanation:'mi-khâham + Konjunktiv = ich möchte. bekhâbam = ich schlafe (Konjunktiv).' },
      { type:2, sentence:'bordan — Präsensstamm: ___',
        options:['bar','bord','bur','bar-am'],
        correct:'bar', explanation:'bordan (tragen/bringen): Stamm bar. mi-bar-am = ich trage.' },
      { type:1, de:'Wir bringen das Buch.',
        tiles:['Mâ','ketâb','râ','mi-barim','.'], solution:['Mâ','ketâb','râ','mi-barim','.'],
        explanation:'mi-bar-im = wir bringen/tragen. Râ da Objekt bestimmt.' },
    ]
  },

  {
    id: 23, title: 'Ezâfe-Ketten', phase: 2,
    tasks: [
      { type:5, farsi:'Ostâd-e zabân-e fârsi.',
        options:['der Persischlehrer','die persische Sprache','der Lehrer der Sprache','das Buch über Persisch'],
        correct:'der Persischlehrer',
        explanation:'ostâd-e zabân-e fârsi = Lehrer + Sprache + Persisch: der Persischlehrer.' },
      { type:1, de:'die Tür meines Zimmers',
        tiles:['dar-e','otâq-e','man'], solution:['dar-e','otâq-e','man'],
        explanation:'Ezâfe-Kette: dar-e otâq-e man = Tür-EZ Zimmer-EZ ich.' },
      { type:5, farsi:'Ketâb-e târikh-e Irân.',
        options:['das Buch der Geschichte Irans','die Geschichte des Iran','das iranische Geschichtsbuch','der Historiker des Iran'],
        correct:'das Buch der Geschichte Irans',
        explanation:'ketâb-e = Buch-EZ. târikh-e = Geschichte-EZ. Irân = Iran.' },
      { type:1, de:'der Freund von Alis Vater',
        tiles:['dust-e','pedar-e','Ali'], solution:['dust-e','pedar-e','Ali'],
        explanation:'Kette: dust-e pedar-e Ali = Freund-EZ Vater-EZ Ali.' },
      { type:2, sentence:'Mâdar-e dokhtar-e ___ (die Mutter des Mädchens meines Lehrers)',
        options:['ostâd-e man','man-e ostâd','ostâd man','man ostâd'],
        correct:'ostâd-e man', explanation:'...dokhtar-e ostâd-e man: das letzte Glied = ostâd-e man = mein Lehrer.' },
      { type:5, farsi:'Dar-e khâne-ye mâ.',
        options:['die Tür unseres Hauses','das Haus unserer Tür','unser Haustor','das Tor des Hauses'],
        correct:'die Tür unseres Hauses',
        explanation:'dar-e khâne-ye mâ: Tür-EZ Haus-EZ wir = die Tür unseres Hauses.' },
      { type:1, de:'das Buch der Geschichte des Iran',
        tiles:['ketâb-e','târikh-e','Irân'], solution:['ketâb-e','târikh-e','Irân'],
        explanation:'Dreigliedrige Kette: jedes Glied bekommt seine Ezâfe.' },
      { type:2, sentence:'Pedar-e ___ doktor ast. (Der Vater des Lehrers ist Arzt.)',
        options:['moalem-e man','man moalem','moalem man','man-e moalem'],
        correct:'moalem-e man', explanation:'pedar-e moalem-e man: Vater-EZ Lehrer-EZ ich.' },
    ]
  },

  {
    id: 24, title: 'râ vertieft', phase: 2,
    tasks: [
      { type:5, farsi:'Man ketâb-e bozorg râ khândam.',
        options:['Ich las das große Buch.','Ich las ein großes Buch.','Er las das große Buch.','Das große Buch las ich nicht.'],
        correct:'Ich las das große Buch.',
        explanation:'ketâb-e bozorg râ = das große Buch (bestimmt, Akkusativ). khândam = ich las.' },
      { type:2, sentence:'___ → Wann kommt râ?',
        options:['bei bestimmtem Objekt','bei jedem Objekt','nur bei Personen','nur beim Verb am Ende'],
        correct:'bei bestimmtem Objekt', explanation:'Râ markiert ein bestimmtes direktes Objekt.' },
      { type:1, de:'Ali kaufte das alte Haus.',
        tiles:['Ali','khâne-ye','qadim','râ','kharid','.'], solution:['Ali','khâne-ye','qadim','râ','kharid','.'],
        explanation:'Râ nach der ganzen Ezâfe-Phrase: khâne-ye qadim râ.' },
      { type:6, prompt:'Fehlerhafter Satz (râ-Position): "Man râ in film didam."',
        options:[
          'Man in film râ didam.',
          'Râ man in film didam.',
          'Man in film didam râ.',
          'In film man râ didam.',
        ],
        correct:'Man in film râ didam.',
        explanation:'Râ steht nach dem Objekt (in film), nicht vor dem Subjekt.' },
      { type:5, farsi:'U ketâb-hâ-ye man râ gereft.',
        options:['Er/Sie nahm meine Bücher.','Er/Sie gab mir Bücher.','Ich nahm seine Bücher.','Er/Sie hat meine Bücher.'],
        correct:'Er/Sie nahm meine Bücher.',
        explanation:'ketâb-hâ-ye man râ = meine Bücher (Akkusativ). gereft = nahm.' },
      { type:2, sentence:'Man ostâd-e zabân-e fârsi ___ shenâkhtam.',
        options:['râ','—','be','az'],
        correct:'râ', explanation:'ostâd-e zabân-e fârsi ist ein bestimmtes Objekt → râ nötig, nach der Ezâfe-Kette.' },
      { type:1, de:'Wir sahen den iranischen Film.',
        tiles:['Mâ','film-e','irâni','râ','didim','.'], solution:['Mâ','film-e','irâni','râ','didim','.'],
        explanation:'film-e irâni râ = den iranischen Film. Râ steht nach der Ezâfe-Phrase.' },
      { type:5, farsi:'Ânhâ urâ shenâkhtand.',
        options:['Sie erkannten ihn.','Sie erkannten uns.','Er erkannte sie.','Wir erkannten sie.'],
        correct:'Sie erkannten ihn.',
        explanation:'urâ = u + râ = ihn/sie. shenâkhtand = sie erkannten.' },
    ]
  },

  {
    id: 25, title: 'Phase-2-Wiederholung', phase: 2,
    tasks: [
      { type:5, farsi:'Man pedar-e to râ shenâkhtam.',
        options:['Ich kannte deinen Vater.','Mein Vater kannte dich.','Du kanntest meinen Vater.','Er kannte deinen Vater.'],
        correct:'Ich kannte deinen Vater.',
        explanation:'pedar-e to râ = deinen Vater (Akkusativ). shenâkhtam = ich kannte.' },
      { type:6, prompt:'Fehlerhafter Satz: "Ânhâ be khâne mi-ravand râ."',
        options:[
          'Ânhâ be khâne mi-ravand.',
          'Ânhâ râ be khâne mi-ravand.',
          'Râ ânhâ be khâne mi-ravand.',
          'Ânhâ be khâne-râ mi-ravand.',
        ],
        correct:'Ânhâ be khâne mi-ravand.',
        explanation:'mi-ravan ist intransitiv — râ nicht nötig. Ânhâ be khâne mi-ravand.' },
      { type:1, de:'Sie gehen nach Hause.',
        tiles:['Ânhâ','be','khâne','mi-ravand','.'], solution:['Ânhâ','be','khâne','mi-ravand','.'],
        explanation:'be khâne = nach Hause. mi-ravand = sie gehen.' },
      { type:2, sentence:'Man mi-khâham ___ (Ich möchte kommen.)',
        options:['biyâm','biâm','mi-yâm','âmad-am'],
        correct:'biyâm', explanation:'Modalverb + Konjunktiv: mi-khâham biyâm = ich möchte kommen.' },
      { type:5, farsi:'Dâneshju-yân-e dâneshgâh.',
        options:['die Studenten der Universität','die Universität der Studenten','die Studenten und die Universität','die große Universität'],
        correct:'die Studenten der Universität',
        explanation:'dâneshju-yân (-ân Plural nach Vokal) + Ezâfe + dâneshgâh.' },
      { type:6, prompt:'Fehlerhafter Satz: "Man dâram yek baradar."',
        options:[
          'Man yek baradar dâram.',
          'Man yek baradar mi-dâram.',
          'Dâram man yek baradar.',
          'Man-e yek baradar dâram.',
        ],
        correct:'Man yek baradar dâram.',
        explanation:'SOV-Ordnung: man → yek baradar → dâram. dâshtan kein mi-!' },
      { type:1, de:'Er möchte das Buch lesen.',
        tiles:['U','ketâb','râ','mikhâhad','bekhânad','.'], solution:['U','ketâb','râ','mikhâhad','bekhânad','.'],
        explanation:'Râ nach Objekt vor Modalverb-Komplex. mikhâhad + bekhânad.' },
      { type:5, farsi:'Haft ketâb dâram.',
        options:['Ich habe sieben Bücher.','Ich habe sieben Buch gelesen.','Sieben Bücher sind da.','Er hat sieben Bücher.'],
        correct:'Ich habe sieben Bücher.',
        explanation:'haft = 7. ketâb = Buch (kein Plural nach Zahl). dâram = ich habe.' },
    ]
  },

  /* ════════════════════════════════════════
     PHASE 3 — KONSOLIDIERUNG (Level 26–30)
  ════════════════════════════════════════ */

  {
    id: 26, title: 'Was ich gestern tat', phase: 3,
    tasks: [
      { type:2, sentence:'Man raft___ (Ich ging.)',
        options:['-am','-i','-ad','-im'],
        correct:'-am', explanation:'Vergangenheit: Vergangenheitsstamm (raft) + Endung. 1. Sg: -am.' },
      { type:1, de:'Er/Sie ging.',
        tiles:['U','raft','.'], solution:['U','raft','.'],
        explanation:'3. Person Singular Vergangenheit: kein Suffix! U raft = er/sie ging.' },
      { type:5, farsi:'Mâ raft-im.',
        options:['Wir gingen.','Ihr gingt.','Sie gingen.','Wir werden gehen.'],
        correct:'Wir gingen.',
        explanation:'raft-im = Vergangenheitsstamm + -im = wir gingen.' },
      { type:2, sentence:'Man diruz ketâb ___ (Ich las gestern.)',
        options:['khândam','mi-khânam','bekhânam','khânid-am'],
        correct:'khândam', explanation:'Vergangenheit ohne mi-: khând-am = ich las.' },
      { type:6, prompt:'Fehlerhafter Satz: "Man diruz mi-raftam bâzâr."',
        options:[
          'Man diruz be bâzâr raftam.',
          'Man bâzâr diruz raftam.',
          'Man diruz raftam mi-bâzâr.',
          'Man diruz bâzâr mi-raftam.',
        ],
        correct:'Man diruz be bâzâr raftam.',
        explanation:'Einfache Vergangenheit ohne mi-. be bâzâr = zum Markt.' },
      { type:1, de:'Ich sah ihn gestern.',
        tiles:['Man','diruz','urâ','didam','.'], solution:['Man','diruz','urâ','didam','.'],
        explanation:'didam = ich sah. urâ = ihn/sie.' },
      { type:5, farsi:'Ânhâ nâme nevesht-and.',
        options:['Sie schrieben den Brief.','Sie lasen den Brief.','Sie schickten den Brief.','Er schrieb den Brief.'],
        correct:'Sie schrieben den Brief.',
        explanation:'nevesht = Vergangenheitsstamm von neveshtan. -and = sie.' },
      { type:2, sentence:'budan (sein) — Vergangenheit 3. Sg: ___',
        options:['bud','bud-am','bud-i','bud-and'],
        correct:'bud', explanation:'3. Person Singular Vergangenheit: kein Suffix. bud = er/sie war.' },
      { type:1, de:'Wir waren dort.',
        tiles:['Mâ','ânjâ','budim','.'], solution:['Mâ','ânjâ','budim','.'],
        explanation:'budim = wir waren (bud-im).' },
    ]
  },

  {
    id: 27, title: 'Ich will nicht…', phase: 3,
    tasks: [
      { type:2, sentence:'Man ___ ravam. (Ich gehe nicht.)',
        options:['nemi-','na-','ne-','bi-'],
        correct:'nemi-', explanation:'Verneinung im Präsens: mi- → nemi-. nemi-ravam = ich gehe nicht.' },
      { type:1, de:'Sie geht nicht nach Hause.',
        tiles:['U','be','khâne','nemi-ravad','.'], solution:['U','be','khâne','nemi-ravad','.'],
        explanation:'nemi-rav-ad = sie geht nicht.' },
      { type:2, sentence:'Man ___ raftam. (Ich ging nicht.)',
        options:['na-','nemi-','ne-','bi-'],
        correct:'na-', explanation:'Verneinung in der Vergangenheit: na- vor den Stamm. na-raftam.' },
      { type:5, farsi:'Man nemi-dânam.',
        options:['Ich weiß nicht.','Ich habe nicht.','Ich gehe nicht.','Ich verstehe nicht.'],
        correct:'Ich weiß nicht.',
        explanation:'dânestan (wissen), Stamm dân. nemi-dân-am = ich weiß nicht.' },
      { type:6, prompt:'Fehlerhafter Satz: "Man ketâb nemi-khândam na."',
        options:[
          'Man ketâb nemi-khânam.',
          'Man na-ketâb mi-khânam.',
          'Man nemi-khânam ketâb na.',
          'Na man ketâb mi-khânam.',
        ],
        correct:'Man ketâb nemi-khânam.',
        explanation:'Einfach nemi- verwenden. Kein "na" am Ende nötig.' },
      { type:1, de:'Ich möchte das nicht tun.',
        tiles:['Man','in','kâr','râ','nemi-khâham','bekonam','.'], solution:['Man','in','kâr','râ','nemi-khâham','bekonam','.'],
        explanation:'nemi-khâham = ich möchte nicht. bekonam = tun (Konjunktiv).' },
      { type:5, farsi:'Ânhâ nâmad-and.',
        options:['Sie kamen nicht.','Sie kamen.','Sie gingen nicht.','Er kam nicht.'],
        correct:'Sie kamen nicht.',
        explanation:'na-âmad-and: na- vor Vergangenheitsstamm. âmadan (kommen).' },
      { type:2, sentence:'Verneinung von budan — Präsens: ___',
        options:['nist','nabud','nemi-bud','na-bâsh'],
        correct:'nist', explanation:'Verneinung von sein im Präsens: nist (3. Sg), nistam (1. Sg) usw.' },
      { type:1, de:'Wir können das nicht tun.',
        tiles:['Mâ','in','kâr','râ','nemi-tavânim','kardan','.'], solution:['Mâ','in','kâr','râ','nemi-tavânim','kardan','.'],
        explanation:'nemi-tavânim = wir können nicht (Verneinung von tavânestan).' },
    ]
  },

  {
    id: 28, title: 'Modalverben', phase: 3,
    tasks: [
      { type:5, farsi:'Man mi-khâham bekhânam.',
        options:['Ich möchte lesen.','Ich lese gern.','Ich habe gelesen.','Ich kann lesen.'],
        correct:'Ich möchte lesen.',
        explanation:'mi-khâham (ich möchte) + bekhânam (Konjunktiv = ich lese).' },
      { type:2, sentence:'___ = können (Modalverb)',
        options:['tavânestan','khâstan','bâyad','dâshtan'],
        correct:'tavânestan', explanation:'tavânestan = können. Stamm tavân. mi-tavân-am = ich kann.' },
      { type:1, de:'Kannst du Farsi sprechen?',
        tiles:['Âyâ','to','mi-tavâni','fârsi','sohbat','koni','?'], solution:['Âyâ','to','mi-tavâni','fârsi','sohbat','koni','?'],
        explanation:'mi-tavâni = kannst du. sohbat koni = sprechen (Konjunktiv).' },
      { type:2, sentence:'Bâyad berav___ (Ich muss gehen.)',
        options:['am','i','id','ad'],
        correct:'am', explanation:'bâyad = müssen/sollen + Konjunktiv. berav-am = dass ich gehe.' },
      { type:5, farsi:'U nemi-tavânad biyâyad.',
        options:['Er/Sie kann nicht kommen.','Er/Sie will nicht kommen.','Er/Sie muss nicht kommen.','Er/Sie darf nicht kommen.'],
        correct:'Er/Sie kann nicht kommen.',
        explanation:'nemi-tavânad = er/sie kann nicht. biyâyad = kommen (Konjunktiv).' },
      { type:6, prompt:'Fehlerhafter Satz: "Man mi-khâham ketâb râ bekhândam mi-konam."',
        options:[
          'Man ketâb râ mi-khâham bekhânam.',
          'Man ketâb mi-khâham bekhândam râ.',
          'Man mi-khâham ketâb bekhândam.',
          'Man mi-khâham râ ketâb bekhândam.',
        ],
        correct:'Man ketâb râ mi-khâham bekhânam.',
        explanation:'Richtige Struktur: Subjekt + Objekt + râ + Modalverb + Konjunktiv.' },
      { type:1, de:'Wir müssen jetzt gehen.',
        tiles:['Mâ','bâyad','hâlâ','beravim','.'], solution:['Mâ','bâyad','hâlâ','beravim','.'],
        explanation:'bâyad + Konjunktiv. hâlâ = jetzt. beravim = dass wir gehen.' },
      { type:5, farsi:'Âyâ mi-tavânid komak konid?',
        options:['Können Sie helfen?','Wollen Sie helfen?','Müssen Sie helfen?','Dürfen Sie helfen?'],
        correct:'Können Sie helfen?',
        explanation:'mi-tavânid = Sie können. komak konid = helfen Sie (Konjunktiv).' },
    ]
  },

  {
    id: 29, title: 'Fehler finden II', phase: 3,
    tasks: [
      { type:6, prompt:'Fehlerhafter Satz: "Man diruz bâ u mi-raftam."',
        options:[
          'Man diruz bâ u raftam.',
          'Man diruz bâ u nemi-raftam.',
          'Man bâ u diruz mi-raftam.',
          'Man diruz mi-raftam bâ u.',
        ],
        correct:'Man diruz bâ u raftam.',
        explanation:'diruz (gestern) → Vergangenheit, kein mi-. raftam = ich ging.' },
      { type:6, prompt:'Fehlerhafter Satz: "Man yek ketâb râ dâram."',
        options:[
          'Man yek ketâb dâram.',
          'Man yek ketâb râ mi-dâram.',
          'Man râ yek ketâb dâram.',
          'Man dâram yek ketâb.',
        ],
        correct:'Man yek ketâb dâram.',
        explanation:'Unbestimmtes Objekt (yek ketâb) bekommt kein râ.' },
      { type:6, prompt:'Fehlerhafter Satz: "Khâne-e bozorg-e siyâh."',
        options:[
          'Khâne-ye bozorg-e siyâh.',
          'Khâne-e bozorg siyâh.',
          'Khâne bozorg-e siyâh.',
          'Khâne-ye-e bozorg siyâh.',
        ],
        correct:'Khâne-ye bozorg-e siyâh.',
        explanation:'khâne endet auf -e (Vokal) → Ezâfe ist -ye, nicht -e.' },
      { type:6, prompt:'Fehlerhafter Satz: "Ânhâ nâmad-and diruz."',
        options:[
          'Ânhâ diruz nâmad-and.',
          'Diruz nâmad-and ânhâ.',
          'Ânhâ diruz na-mâd-and.',
          'Diruz ânhâ nâmadand.',
        ],
        correct:'Ânhâ diruz nâmad-and.',
        explanation:'Zeitangaben (diruz) stehen zwischen Subjekt und Verb, Verb ans Ende.' },
      { type:6, prompt:'Fehlerhafter Satz: "Man mi-khâham bekhândam ketâb râ."',
        options:[
          'Man ketâb râ mi-khâham bekhânam.',
          'Man mi-khâham ketâb râ bekhândam.',
          'Man bekhândam ketâb râ mi-khâham.',
          'Ketâb râ mi-khâham man bekhândam.',
        ],
        correct:'Man ketâb râ mi-khâham bekhânam.',
        explanation:'Richtige Reihenfolge: Subjekt + Objekt + râ + Modalverb + Infinitiv/Konjunktiv.' },
      { type:6, prompt:'Fehlerhafter Satz: "Man nistam khub."',
        options:[
          'Man khub nistam.',
          'Nistam man khub.',
          'Man khub-am nistam.',
          'Khub man nistam.',
        ],
        correct:'Man khub nistam.',
        explanation:'SOV gilt auch für negative Kopula. man → khub → nistam.' },
      { type:6, prompt:'Fehlerhafter Satz: "Ali-ye doktor ast."',
        options:[
          'Ali doktor ast.',
          'Ali-ye doktor-e ast.',
          'Doktor Ali ast.',
          'Ali ast doktor.',
        ],
        correct:'Ali doktor ast.',
        explanation:'Eigennamen als Subjekt brauchen keine Ezâfe. Ali doktor ast = Ali ist Arzt.' },
      { type:6, prompt:'Fehlerhafter Satz: "U dâshtan yek khâne dârad."',
        options:[
          'U yek khâne dârad.',
          'U dâshtan khâne-ye yek dârad.',
          'Yek khâne u dârad.',
          'U yek khâne-e dârad.',
        ],
        correct:'U yek khâne dârad.',
        explanation:'dâshtan nicht doppelt! Einfach: u yek khâne dârad = er/sie hat ein Haus.' },
    ]
  },

  {
    id: 30, title: 'Langer Weg', phase: 3,
    tasks: [
      { type:1, de:'Er wollte das alte Haus kaufen.',
        tiles:['U','khâne-ye','qadim','râ','mikhâst','bekharad','.'],
        solution:['U','khâne-ye','qadim','râ','mikhâst','bekharad','.'],
        explanation:'mikhâst = er wollte. bekharad = Konjunktiv von kaufen. Râ nach der Ezâfe-Phrase.' },
      { type:5, farsi:'Man nemi-dânestam ke u kojâst.',
        options:['Ich wusste nicht, wo er ist.','Ich weiß nicht, wo er ist.','Er wusste nicht, wo ich bin.','Ich wusste nicht, wer er ist.'],
        correct:'Ich wusste nicht, wo er ist.',
        explanation:'nemi-dânestam = ich wusste nicht. ke = dass/wo. u kojâst = wo er ist.' },
      { type:1, de:'Wir konnten das nicht verstehen.',
        tiles:['Mâ','in','râ','nemi-tavânestim','befahmim','.'],
        solution:['Mâ','in','râ','nemi-tavânestim','befahmim','.'],
        explanation:'nemi-tavânestim = wir konnten nicht. befahmim = verstehen (Konjunktiv).' },
      { type:6, prompt:'Fehlerhafter Satz: "U goft man be khâne mi-ravad."',
        options:[
          'U goft ke man be khâne mi-ravam.',
          'U goft ke man mi-ravad be khâne.',
          'Goft u ke man be khâne mi-ravam.',
          'U goft man mi-ravam be khâne.',
        ],
        correct:'U goft ke man be khâne mi-ravam.',
        explanation:'ke = dass (Einleitung des Nebensatzes). Verbform anpassen: mi-ravam (1. Sg).' },
      { type:5, farsi:'Ostâd-e mâ goft ke fardâ emtehân dârim.',
        options:['Unser Lehrer sagte, dass wir morgen eine Prüfung haben.','Der Lehrer hat morgen eine Prüfung.','Unser Lehrer hatte gestern eine Prüfung.','Der Lehrer sagte, wir haben keine Prüfung.'],
        correct:'Unser Lehrer sagte, dass wir morgen eine Prüfung haben.',
        explanation:'ostâd-e mâ = unser Lehrer. goft = sagte. ke = dass. fardâ = morgen. emtehân dârim = wir haben eine Prüfung.' },
      { type:1, de:'Weil er gesagt hat, dass er kommt.',
        tiles:['chon','u','goft','ke','mi-yâyad'], solution:['chon','u','goft','ke','mi-yâyad'],
        explanation:'chon = weil. ke = dass. mi-yâyad = er kommt.' },
      { type:6, prompt:'Fehlerhafter Satz: "Man be u ketâb râ dâdam."',
        options:[
          'Man ketâb râ be u dâdam.',
          'Man râ ketâb be u dâdam.',
          'Be u man ketâb râ dâdam.',
          'Man be u dâdam ketâb râ.',
        ],
        correct:'Man ketâb râ be u dâdam.',
        explanation:'Standardreihenfolge: Subjekt + direktes Objekt + râ + indirektes Objekt + Verb.' },
      { type:5, farsi:'Agar fardâ bârun biyâyad, man nemi-ravam.',
        options:['Wenn es morgen regnet, gehe ich nicht.','Wenn es regnet, komme ich morgen.','Morgen werde ich nicht gehen.','Wenn es nicht regnet, gehe ich.'],
        correct:'Wenn es morgen regnet, gehe ich nicht.',
        explanation:'agar = wenn. bârun biyâyad = es regnet (Konjunktiv). nemi-ravam = ich gehe nicht.' },
      { type:1, de:'Das war der schwierigste Teil der Reise.',
        tiles:['In','sakht-tarin','qesmat-e','safar','bud','.'],
        solution:['In','sakht-tarin','qesmat-e','safar','bud','.'],
        explanation:'sakht-tarin = schwierigste (Superlativ). qesmat-e safar = Teil-EZ Reise.' },
    ]
  },

];
