/* ── FRENCH DATA ── */
const FRENCH_VOCAB = [
  { id:    1, r: 'de', m: 'von / aus' },
  { id:    2, r: 'la', m: 'die (weibl. Artikel)' },
  { id:    3, r: 'le', m: 'der (männl. Artikel)' },
  { id:    4, r: 'et', m: 'und' },
  { id:    5, r: 'les', m: 'die (Plural)' },
  { id:    6, r: 'des', m: 'von den / einige' },
  { id:    7, r: 'en', m: 'in / auf' },
  { id:    8, r: 'un', m: 'ein (männl.)' },
  { id:    9, r: 'du', m: 'von dem / vom' },
  { id:   10, r: 'une', m: 'eine (weibl.)' },
  { id:   11, r: 'que', m: 'dass / was / als' },
  { id:   12, r: 'est', m: 'ist' },
  { id:   13, r: 'pour', m: 'für' },
  { id:   14, r: 'qui', m: 'der / die / das / wer' },
  { id:   15, r: 'dans', m: 'in' },
  { id:   16, r: 'a', m: 'hat' },
  { id:   17, r: 'par', m: 'durch / pro' },
  { id:   18, r: 'plus', m: 'mehr' },
  { id:   19, r: 'pas', m: 'nicht' },
  { id:   20, r: 'au', m: 'beim / am' },
  { id:   21, r: 'sur', m: 'auf / über' },
  { id:   22, r: 'ne', m: 'nicht (Verneinungspartikel)' },
  { id:   23, r: 'se', m: 'sich' },
  { id:   24, r: 'Le', m: 'der (männl. Artikel, groß)' },
  { id:   25, r: 'ce', m: 'dieser / dieses' },
  { id:   26, r: 'il', m: 'er' },
  { id:   27, r: 'sont', m: 'sind' },
  { id:   28, r: 'La', m: 'die (weibl. Artikel, groß)' },
  { id:   29, r: 'Les', m: 'die (Plural, groß)' },
  { id:   30, r: 'ou', m: 'oder' },
  { id:   31, r: 'avec', m: 'mit' },
  { id:   32, r: 'son', m: 'sein / ihr' },
  { id:   33, r: 'Il', m: 'Er (groß)' },
  { id:   34, r: 'aux', m: 'bei den / an den' },
  { id:   35, r: 'd\'un', m: 'von einem' },
  { id:   36, r: 'En', m: 'In (groß)' },
  { id:   37, r: 'cette', m: 'diese' },
  { id:   38, r: 'd\'une', m: 'von einer' },
  { id:   39, r: 'ont', m: 'haben' },
  { id:   40, r: 'ses', m: 'seine / ihre' },
  { id:   41, r: 'mais', m: 'aber' },
  { id:   42, r: 'comme', m: 'wie / als' },
  { id:   43, r: 'on', m: 'man' },
  { id:   44, r: 'tout', m: 'alles / ganz' },
  { id:   45, r: 'nous', m: 'wir' },
  { id:   46, r: 'sa', m: 'sein / ihr (weibl.)' },
  { id:   47, r: 'Mais', m: 'Aber (groß)' },
  { id:   48, r: 'fait', m: 'gemacht / getan' },
  { id:   49, r: 'été', m: 'gewesen / Sommer' },
  { id:   50, r: 'aussi', m: 'auch' },
  { id:   51, r: 'leur', m: 'ihr / ihnen' },
  { id:   52, r: 'bien', m: 'gut / wohl' },
  { id:   53, r: 'peut', m: 'kann' },
  { id:   54, r: 'ces', m: 'diese (Plural)' },
  { id:   55, r: 'y', m: 'dort / darin / dazu' },
  { id:   56, r: 'deux', m: 'zwei' },
  { id:   57, r: 'A', m: 'Bei / An (groß)' },
  { id:   58, r: 'ans', m: 'Jahre' },
  { id:   59, r: 'l', m: 'l (Abkürzung)' },
  { id:   60, r: 'encore', m: 'noch / wieder' },
  { id:   61, r: 'n\'est', m: 'ist nicht' },
  { id:   62, r: 'marché', m: 'Markt' },
  { id:   63, r: 'd', m: 'd (Abkürzung)' },
  { id:   64, r: 'Pour', m: 'Für (groß)' },
  { id:   65, r: 'donc', m: 'also / folglich' },
  { id:   66, r: 'cours', m: 'Kurs / Verlauf' },
  { id:   67, r: 'qu\'il', m: 'dass er' },
  { id:   68, r: 'moins', m: 'weniger' },
  { id:   69, r: 'sans', m: 'ohne' },
  { id:   70, r: 'C\'est', m: 'Das ist' },
  { id:   71, r: 'Et', m: 'Und (groß)' },
  { id:   72, r: 'si', m: 'wenn / ob / so' },
  { id:   73, r: 'entre', m: 'zwischen' },
  { id:   74, r: 'Un', m: 'Ein (männl., groß)' },
  { id:   75, r: 'Ce', m: 'Dieser (groß)' },
  { id:   76, r: 'faire', m: 'machen / tun' },
  { id:   77, r: 'elle', m: 'sie' },
  { id:   78, r: 'c\'est', m: 'das ist' },
  { id:   79, r: 'peu', m: 'wenig' },
  { id:   80, r: 'vous', m: 'Sie / ihr' },
  { id:   81, r: 'Une', m: 'Eine (groß)' },
  { id:   82, r: 'prix', m: 'Preis' },
  { id:   83, r: 'On', m: 'Man (groß)' },
  { id:   84, r: 'dont', m: 'dessen / wovon' },
  { id:   85, r: 'lui', m: 'ihm / ihr / er' },
  { id:   86, r: 'également', m: 'ebenfalls / auch' },
  { id:   87, r: 'Dans', m: 'In (groß)' },
  { id:   88, r: 'effet', m: 'Wirkung / Effekt' },
  { id:   89, r: 'pays', m: 'Land' },
  { id:   90, r: 'cas', m: 'Fall' },
  { id:   91, r: 'De', m: 'Von (groß)' },
  { id:   92, r: 'millions', m: 'Millionen' },
  { id:   93, r: 'Belgique', m: 'Belgien' },
  { id:   94, r: 'BEF', m: 'Belgischer Franken (Währung)' },
  { id:   95, r: 'mois', m: 'Monat' },
  { id:   96, r: 'leurs', m: 'ihre (Plural)' },
  { id:   97, r: 'taux', m: 'Rate / Kurs / Zinssatz' },
  { id:   98, r: 'années', m: 'Jahre' },
  { id:   99, r: 'temps', m: 'Zeit / Wetter' },
  { id:  100, r: 'groupe', m: 'Gruppe' },
  { id:  101, r: 'ainsi', m: 'so / damit' },
  { id:  102, r: 'toujours', m: 'immer / noch' },
  { id:  103, r: 'société', m: 'Gesellschaft / Unternehmen' },
  { id:  104, r: 'depuis', m: 'seit' },
  { id:  105, r: 'tous', m: 'alle' },
  { id:  106, r: 'soit', m: 'sei / oder' },
  { id:  107, r: 'faut', m: 'muss / braucht' },
  { id:  108, r: 'Bruxelles', m: 'Brüssel' },
  { id:  109, r: 'fois', m: 'mal / Mal' },
  { id:  110, r: 'quelques', m: 'einige' },
  { id:  111, r: 'sera', m: 'wird sein' },
  { id:  112, r: 'entreprises', m: 'Unternehmen (Plural)' },
  { id:  113, r: 'F', m: 'F (Abkürzung)' },
  { id:  114, r: 'contre', m: 'gegen' },
  { id:  115, r: 'francs', m: 'Franken (Währung)' },
  { id:  116, r: 'je', m: 'ich' },
  { id:  117, r: 'n\'a', m: 'hat nicht' },
  { id:  118, r: 'Nous', m: 'Wir (groß)' },
  { id:  119, r: 'Cette', m: 'Diese (groß)' },
  { id:  120, r: 'dernier', m: 'letzter / letzte' },
  { id:  121, r: 'était', m: 'war' },
  { id:  122, r: 'Si', m: 'Wenn / Ob (groß)' },
  { id:  123, r: 's\'est', m: 'sich ist' },
  { id:  124, r: 'chez', m: 'bei / zu' },
  { id:  125, r: 'L', m: 'L (Abkürzung)' },
  { id:  126, r: 'monde', m: 'Welt' },
  { id:  127, r: 'alors', m: 'dann / also' },
  { id:  128, r: 'sous', m: 'unter' },
  { id:  129, r: 'actions', m: 'Aktien / Handlungen' },
  { id:  130, r: 'autres', m: 'andere' },
  { id:  131, r: 'Au', m: 'Beim / Am (groß)' },
  { id:  132, r: 'ils', m: 'sie (männl. Plural)' },
  { id:  133, r: 'reste', m: 'Rest / bleibt' },
  { id:  134, r: 'trois', m: 'drei' },
  { id:  135, r: 'non', m: 'nein / nicht' },
  { id:  136, r: 'notre', m: 'unser / unsere' },
  { id:  137, r: 'doit', m: 'muss / soll' },
  { id:  138, r: 'nouveau', m: 'neu' },
  { id:  139, r: 'milliards', m: 'Milliarden' },
  { id:  140, r: 'avant', m: 'vor / bevor' },
  { id:  141, r: 'exemple', m: 'Beispiel' },
  { id:  142, r: 'compte', m: 'Konto / Konto / zählt' },
  { id:  143, r: 'belge', m: 'belgisch' },
  { id:  144, r: 'premier', m: 'erster / erste' },
  { id:  145, r: 's', m: 's (Abkürzung)' },
  { id:  146, r: 'nouvelle', m: 'neu (weibl.) / Neuigkeit' },
  { id:  147, r: 'Elle', m: 'Sie (groß)' },
  { id:  148, r: 'l\'on', m: 'man' },
  { id:  149, r: 'terme', m: 'Begriff / Frist' },
  { id:  150, r: 'avait', m: 'hatte' },
  { id:  151, r: 'produits', m: 'Produkte' },
  { id:  152, r: 'cela', m: 'das / dies' },
  { id:  153, r: 'd\'autres', m: 'andere' },
  { id:  154, r: 'fin', m: 'Ende' },
  { id:  155, r: 'niveau', m: 'Niveau / Ebene' },
  { id:  156, r: 'bénéfice', m: 'Gewinn / Vorteil' },
  { id:  157, r: 'toute', m: 'ganz / alle (weibl.)' },
  { id:  158, r: 'travail', m: 'Arbeit' },
  { id:  159, r: 'partie', m: 'Teil / Partie' },
  { id:  160, r: 'trop', m: 'zu viel / zu sehr' },
  { id:  161, r: 'hausse', m: 'Anstieg / Erhöhung' },
  { id:  162, r: 'secteur', m: 'Sektor / Bereich' },
  { id:  163, r: 'part', m: 'Anteil / Teil' },
  { id:  164, r: 'beaucoup', m: 'viel / viele' },
  { id:  165, r: 'Je', m: 'Ich (groß)' },
  { id:  166, r: 'valeur', m: 'Wert' },
  { id:  167, r: 'croissance', m: 'Wachstum' },
  { id:  168, r: 'rapport', m: 'Bericht / Verhältnis' },
  { id:  169, r: 'USD', m: 'US-Dollar' },
  { id:  170, r: 'aujourd\'hui', m: 'heute' },
  { id:  171, r: 'année', m: 'Jahr' },
  { id:  172, r: 'base', m: 'Basis / Grundlage' },
  { id:  173, r: 'Bourse', m: 'Börse' },
  { id:  174, r: 'lors', m: 'bei / während' },
  { id:  175, r: 'vers', m: 'gegen / in Richtung' },
  { id:  176, r: 'souvent', m: 'oft' },
  { id:  177, r: 'vie', m: 'Leben' },
  { id:  178, r: 'l\'entreprise', m: 'das Unternehmen' },
  { id:  179, r: 'autre', m: 'andere / anderer' },
  { id:  180, r: 'peuvent', m: 'können' },
  { id:  181, r: 'bon', m: 'gut' },
  { id:  182, r: 'surtout', m: 'vor allem / besonders' },
  { id:  183, r: 'toutes', m: 'alle (weibl. Plural)' },
  { id:  184, r: 'nombre', m: 'Anzahl / Zahl' },
  { id:  185, r: 'fonds', m: 'Fonds / Fond' },
  { id:  186, r: 'point', m: 'Punkt' },
  { id:  187, r: 'grande', m: 'groß (weibl.)' },
  { id:  188, r: 'jour', m: 'Tag' },
  { id:  189, r: 'va', m: 'geht' },
  { id:  190, r: 'avoir', m: 'haben' },
  { id:  191, r: 'nos', m: 'unsere' },
  { id:  192, r: 'quelque', m: 'irgendein / etwas' },
  { id:  193, r: 'place', m: 'Platz / Stelle' },
  { id:  194, r: 'grand', m: 'groß' },
  { id:  195, r: 'personnes', m: 'Personen' },
  { id:  196, r: 'plusieurs', m: 'mehrere' },
  { id:  197, r: 'certains', m: 'bestimmte / einige' },
  { id:  198, r: 'd\'affaires', m: 'Geschäfts-' },
  { id:  199, r: 'permet', m: 'erlaubt / ermöglicht' },
  { id:  200, r: 'politique', m: 'Politik / politisch' },
  { id:  201, r: 'cet', m: 'dieser (vor Vokal)' },
  { id:  202, r: 'chaque', m: 'jeder / jede' },
  { id:  203, r: 'chiffre', m: 'Zahl / Ziffer' },
  { id:  204, r: 'pourrait', m: 'könnte' },
  { id:  205, r: 'devrait', m: 'sollte' },
  { id:  206, r: 'produit', m: 'Produkt / erzeugt' },
  { id:  207, r: 'l\'année', m: 'das Jahr' },
  { id:  208, r: 'Par', m: 'Durch / Pro (groß)' },
  { id:  209, r: 'rien', m: 'nichts' },
  { id:  210, r: 'mieux', m: 'besser' },
  { id:  211, r: 'celui', m: 'derjenige' },
  { id:  212, r: 'qualité', m: 'Qualität' },
  { id:  213, r: 'France', m: 'Frankreich' },
  { id:  214, r: 'Ils', m: 'Sie (männl. Plural, groß)' },
  { id:  215, r: 'Ces', m: 'Diese (Plural, groß)' },
  { id:  216, r: 's\'agit', m: 'es geht um / handelt sich' },
  { id:  217, r: 'vente', m: 'Verkauf' },
  { id:  218, r: 'jamais', m: 'nie / niemals' },
  { id:  219, r: 'production', m: 'Produktion' },
  { id:  220, r: 'action', m: 'Aktion / Aktie' },
  { id:  221, r: 'baisse', m: 'Rückgang / Senkung' },
  { id:  222, r: 'Avec', m: 'Mit (groß)' },
  { id:  223, r: 'résultats', m: 'Ergebnisse' },
  { id:  224, r: 'Des', m: 'Von den / Einige (groß)' },
  { id:  225, r: 'votre', m: 'Ihr / euer' },
  { id:  226, r: 'risque', m: 'Risiko' },
  { id:  227, r: 'début', m: 'Beginn / Anfang' },
  { id:  228, r: 'banque', m: 'Bank' },
  { id:  229, r: 'an', m: 'Jahr' },
  { id:  230, r: 'voir', m: 'sehen' },
  { id:  231, r: 'avons', m: 'haben (wir)' },
  { id:  232, r: 'qu\'un', m: 'als ein' },
  { id:  233, r: 'qu\'', m: 'dass / was' },
  { id:  234, r: 'elles', m: 'sie (weibl. Plural)' },
  { id:  235, r: 'moment', m: 'Moment / Augenblick' },
  { id:  236, r: 'qu\'on', m: 'dass man' },
  { id:  237, r: 'question', m: 'Frage' },
  { id:  238, r: 'pouvoir', m: 'können / Macht' },
  { id:  239, r: 'titre', m: 'Titel / Wertpapier' },
  { id:  240, r: 'doute', m: 'Zweifel' },
  { id:  241, r: 'long', m: 'lang' },
  { id:  242, r: 'petit', m: 'klein' },
  { id:  243, r: 'd\'ailleurs', m: 'übrigens / außerdem' },
  { id:  244, r: 'notamment', m: 'insbesondere / namentlich' },
  { id:  245, r: 'FB', m: 'FB (Abkürzung)' },
  { id:  246, r: 'droit', m: 'Recht / gerade' },
  { id:  247, r: 'qu\'elle', m: 'dass sie' },
  { id:  248, r: 'heures', m: 'Stunden' },
  { id:  249, r: 'cependant', m: 'jedoch / trotzdem' },
  { id:  250, r: 'service', m: 'Dienst / Service' },
  { id:  251, r: 'Etats-Unis', m: 'Vereinigte Staaten' },
  { id:  252, r: 'qu\'ils', m: 'dass sie' },
  { id:  253, r: 'l\'action', m: 'die Aktie' },
  { id:  254, r: 'jours', m: 'Tage' },
  { id:  255, r: 'celle', m: 'diejenige' },
  { id:  256, r: 'demande', m: 'Nachfrage / Anfrage' },
  { id:  257, r: 'belges', m: 'belgisch (Plural)' },
  { id:  258, r: 'ceux', m: 'diejenigen' },
  { id:  259, r: 'services', m: 'Dienste / Leistungen' },
  { id:  260, r: 'bonne', m: 'gut (weibl.)' },
  { id:  261, r: 'seront', m: 'werden sein' },
  { id:  262, r: 'économique', m: 'wirtschaftlich' },
  { id:  263, r: 'raison', m: 'Grund / Vernunft' },
  { id:  264, r: 'car', m: 'denn / weil' },
  { id:  265, r: 'situation', m: 'Situation / Lage' },
  { id:  266, r: 'Depuis', m: 'Seit (groß)' },
  { id:  267, r: 'entreprise', m: 'Unternehmen' },
  { id:  268, r: 'me', m: 'mir / mich' },
  { id:  269, r: 'nouvelles', m: 'neu (weibl. Pl.) / Nachrichten' },
  { id:  270, r: 'n\'y', m: 'nicht dort' },
  { id:  271, r: 'possible', m: 'möglich' },
  { id:  272, r: 'toutefois', m: 'jedoch / dennoch' },
  { id:  273, r: 'tant', m: 'so viel / solange' },
  { id:  274, r: 'nouveaux', m: 'neu (männl. Plural)' },
  { id:  275, r: 'selon', m: 'gemäß / laut' },
  { id:  276, r: 'parce', m: 'weil (parce que)' },
  { id:  277, r: 'dit', m: 'gesagt / sagt' },
  { id:  278, r: 'seul', m: 'allein / einzig' },
  { id:  279, r: 'qu\'une', m: 'als eine' },
  { id:  280, r: 'sociétés', m: 'Gesellschaften / Unternehmen' },
  { id:  281, r: 'vient', m: 'kommt' },
  { id:  282, r: 'jusqu\'', m: 'bis' },
  { id:  283, r: 'quatre', m: 'vier' },
  { id:  284, r: 'marchés', m: 'Märkte' },
  { id:  285, r: 'mise', m: 'Einsatz / Einlage' },
  { id:  286, r: 'seulement', m: 'nur / lediglich' },
  { id:  287, r: 'Van', m: 'Van (Namensteil)' },
  { id:  288, r: 'semble', m: 'scheint' },
  { id:  289, r: 'clients', m: 'Kunden' },
  { id:  290, r: 'Tout', m: 'Alles (groß)' },
  { id:  291, r: 'Cela', m: 'Das / Dies (groß)' },
  { id:  292, r: 'serait', m: 'wäre' },
  { id:  293, r: 'fort', m: 'stark' },
  { id:  294, r: 'frais', m: 'Kosten / frisch' },
  { id:  295, r: 'lieu', m: 'Ort / Stelle' },
  { id:  296, r: 'gestion', m: 'Verwaltung / Management' },
  { id:  297, r: 'font', m: 'machen / tun (sie)' },
  { id:  298, r: 'quand', m: 'wann / wenn' },
  { id:  299, r: 'capital', m: 'Kapital' },
  { id:  300, r: 'gouvernement', m: 'Regierung' },
  { id:  301, r: 'projet', m: 'Projekt / Vorhaben' },
  { id:  302, r: 'grands', m: 'groß (männl. Plural)' },
  { id:  303, r: 'réseau', m: 'Netzwerk' },
  { id:  304, r: 'l\'autre', m: 'der/die andere' },
  { id:  305, r: 'données', m: 'Daten' },
  { id:  306, r: 'prendre', m: 'nehmen' },
  { id:  307, r: 'plan', m: 'Plan' },
  { id:  308, r: 'points', m: 'Punkte' },
  { id:  309, r: 'outre', m: 'außerdem' },
  { id:  310, r: 'pourtant', m: 'jedoch / dennoch' },
  { id:  311, r: 'Ainsi', m: 'So / Damit (groß)' },
  { id:  312, r: 'ni', m: 'noch / weder' },
  { id:  313, r: 'type', m: 'Typ / Art' },
  { id:  314, r: 'Europe', m: 'Europa' },
  { id:  315, r: 'pendant', m: 'während' },
  { id:  316, r: 'Comme', m: 'Wie / Als (groß)' },
  { id:  317, r: 'mesure', m: 'Maßnahme / Maß' },
  { id:  318, r: 'actuellement', m: 'zurzeit / derzeit' },
  { id:  319, r: 'public', m: 'öffentlich / Publikum' },
  { id:  320, r: 'dire', m: 'sagen' },
  { id:  321, r: 'important', m: 'wichtig' },
  { id:  322, r: 'mis', m: 'gelegt / gestellt' },
  { id:  323, r: 'partir', m: 'abfahren / ab' },
  { id:  324, r: 'parfois', m: 'manchmal' },
  { id:  325, r: 'nom', m: 'Name' },
  { id:  326, r: 'n\'ont', m: 'haben nicht' },
  { id:  327, r: 'veut', m: 'will' },
  { id:  328, r: 'présent', m: 'anwesend / Geschenk / Gegenwart' },
  { id:  329, r: 'passé', m: 'Vergangenheit / vergangen' },
  { id:  330, r: 'forme', m: 'Form' },
  { id:  331, r: 'autant', m: 'genauso viel' },
  { id:  332, r: 'développement', m: 'Entwicklung' },
  { id:  333, r: 'mettre', m: 'legen / stellen / setzen' },
  { id:  334, r: 'grandes', m: 'groß (weibl. Plural)' },
  { id:  335, r: 'vue', m: 'Ansicht / Sicht' },
  { id:  336, r: 'investisseurs', m: 'Investoren' },
  { id:  337, r: 'D', m: 'D (Abkürzung)' },
  { id:  338, r: 'trouve', m: 'findet' },
  { id:  339, r: 'maison', m: 'Haus' },
  { id:  340, r: 'mal', m: 'schlecht / Schmerz' },
  { id:  341, r: 'l\'an', m: 'das Jahr' },
  { id:  342, r: 'moyen', m: 'Mittel / durchschnittlich' },
  { id:  343, r: 'choix', m: 'Wahl / Auswahl' },
  { id:  344, r: 'doivent', m: 'müssen' },
  { id:  345, r: 'NLG', m: 'Niederländischer Gulden (Währung)' },
  { id:  346, r: 'direction', m: 'Richtung / Leitung' },
  { id:  347, r: 'Sur', m: 'Auf / Über (groß)' },
  { id:  348, r: 'simple', m: 'einfach' },
  { id:  349, r: 'période', m: 'Zeitraum / Periode' },
  { id:  350, r: 'enfants', m: 'Kinder' },
  { id:  351, r: 'dollars', m: 'Dollar' },
  { id:  352, r: 'personnel', m: 'Personal / persönlich' },
  { id:  353, r: 'assez', m: 'genug / ziemlich' },
  { id:  354, r: 'programme', m: 'Programm' },
  { id:  355, r: 'général', m: 'allgemein / General' },
  { id:  356, r: 'banques', m: 'Banken' },
  { id:  357, r: 'eux', m: 'sie / ihnen (männl.)' },
  { id:  358, r: 'semaine', m: 'Woche' },
  { id:  359, r: 'président', m: 'Präsident' },
  { id:  360, r: 'personne', m: 'Person / niemand' },
  { id:  361, r: 'européenne', m: 'europäisch (weibl.)' },
  { id:  362, r: 'moyenne', m: 'Durchschnitt' },
  { id:  363, r: 'tard', m: 'spät' },
  { id:  364, r: 'loi', m: 'Gesetz' },
  { id:  365, r: 'petite', m: 'klein (weibl.)' },
  { id:  366, r: 'certaines', m: 'bestimmte (weibl. Plural)' },
  { id:  367, r: 'savoir', m: 'wissen' },
  { id:  368, r: 'loin', m: 'weit / fern' },
  { id:  369, r: 'explique', m: 'erklärt' },
  { id:  370, r: 'plupart', m: 'Mehrheit / die meisten' },
  { id:  371, r: 'jeunes', m: 'jung (Plural) / Jugendliche' },
  { id:  372, r: 'cinq', m: 'fünf' },
  { id:  373, r: 'contrat', m: 'Vertrag' },
  { id:  374, r: 'Banque', m: 'Bank (groß)' },
  { id:  375, r: 'valeurs', m: 'Werte' },
  { id:  376, r: 'seule', m: 'allein (weibl.) / einzig' },
  { id:  377, r: 'rendement', m: 'Rendite / Ertrag' },
  { id:  378, r: 'nombreux', m: 'zahlreich' },
  { id:  379, r: 'fonction', m: 'Funktion / Aufgabe' },
  { id:  380, r: 'offre', m: 'Angebot' },
  { id:  381, r: 'client', m: 'Kunde' },
  { id:  382, r: 'activités', m: 'Aktivitäten / Tätigkeiten' },
  { id:  383, r: 'eu', m: 'gehabt' },
  { id:  384, r: 'environ', m: 'ungefähr / etwa' },
  { id:  385, r: 'ministre', m: 'Minister' },
  { id:  386, r: 'cadre', m: 'Rahmen / Führungskraft' },
  { id:  387, r: 'sens', m: 'Sinn / Bedeutung' },
  { id:  388, r: 'étaient', m: 'waren' },
  { id:  389, r: 'sécurité', m: 'Sicherheit' },
  { id:  390, r: 'recherche', m: 'Forschung / Suche' },
  { id:  391, r: 'Paris', m: 'Paris' },
  { id:  392, r: 'sorte', m: 'Art / Weise' },
  { id:  393, r: 'décembre', m: 'Dezember' },
  { id:  394, r: 'Son', m: 'Sein / Ihr (groß)' },
  { id:  395, r: 'suite', m: 'Folge / Fortsetzung' },
  { id:  396, r: 'davantage', m: 'mehr' },
  { id:  397, r: 'ensuite', m: 'danach / dann' },
  { id:  398, r: 'janvier', m: 'Januar' },
  { id:  399, r: 'donne', m: 'gibt' },
  { id:  400, r: 'vrai', m: 'wahr' },
  { id:  401, r: 'cause', m: 'Ursache / Grund' },
  { id:  402, r: 'd\'abord', m: 'zunächst / zuerst' },
  { id:  403, r: 'conditions', m: 'Bedingungen' },
  { id:  404, r: 'suis', m: 'bin' },
  { id:  405, r: 'juin', m: 'Juni' },
  { id:  406, r: 'peine', m: 'Mühe / Strafe' },
  { id:  407, r: 'certain', m: 'bestimmt / sicher' },
  { id:  408, r: 'septembre', m: 'September' },
  { id:  409, r: 'sommes', m: 'sind (wir) / Summen' },
  { id:  410, r: 'famille', m: 'Familie' },
  { id:  411, r: 'l\'indice', m: 'der Index' },
  { id:  412, r: 'pris', m: 'genommen' },
  { id:  413, r: 'laquelle', m: 'welche / die' },
  { id:  414, r: 'directeur', m: 'Direktor / Leiter' },
  { id:  415, r: 'qu\'en', m: 'als in / was in' },
  { id:  416, r: 'propose', m: 'schlägt vor' },
  { id:  417, r: 'gens', m: 'Leute' },
  { id:  418, r: 'derniers', m: 'letzten (Plural)' },
  { id:  419, r: 'étant', m: 'seiend' },
  { id:  420, r: 'fut', m: 'war (Vergangenheit)' },
  { id:  421, r: 'chose', m: 'Sache / Ding' },
  { id:  422, r: 'portefeuille', m: 'Portfolio / Brieftasche' },
  { id:  423, r: 'obligations', m: 'Anleihen / Verpflichtungen' },
  { id:  424, r: 'afin', m: 'damit / um zu' },
  { id:  425, r: 'différents', m: 'verschieden (Plural)' },
  { id:  426, r: 'technique', m: 'Technik / technisch' },
  { id:  427, r: 'Aujourd\'hui', m: 'Heute (groß)' },
  { id:  428, r: 'ailleurs', m: 'anderswo' },
  { id:  429, r: 'P', m: 'P (Abkürzung)' },
  { id:  430, r: 'l\'ensemble', m: 'die Gesamtheit' },
  { id:  431, r: 'américain', m: 'amerikanisch' },
  { id:  432, r: 'ventes', m: 'Verkäufe' },
  { id:  433, r: 'Selon', m: 'Laut / Gemäß (groß)' },
  { id:  434, r: 'rue', m: 'Straße' },
  { id:  435, r: 'livre', m: 'Buch / Pfund' },
  { id:  436, r: 'octobre', m: 'Oktober' },
  { id:  437, r: 'vraiment', m: 'wirklich' },
  { id:  438, r: 'sein', m: 'Schoß / Inneres' },
  { id:  439, r: 'Or', m: 'Gold / Nun (groß)' },
  { id:  440, r: 'dollar', m: 'Dollar' },
  { id:  441, r: 'Enfin', m: 'Schließlich / Endlich (groß)' },
  { id:  442, r: 'haut', m: 'hoch / oben' },
  { id:  443, r: 'Plus', m: 'Mehr (groß)' },
  { id:  444, r: 'petits', m: 'klein (männl. Plural)' },
  { id:  445, r: 'porte', m: 'Tür / trägt' },
  { id:  446, r: 'tel', m: 'solch / wie' },
  { id:  447, r: 'durée', m: 'Dauer' },
  { id:  448, r: 'domaine', m: 'Bereich / Domäne' },
  { id:  449, r: 'aurait', m: 'hätte' },
  { id:  450, r: 'jeune', m: 'jung' },
  { id:  451, r: 'présente', m: 'stellt vor / anwesend' },
  { id:  452, r: 'passe', m: 'geht vorbei / Pass' },
  { id:  453, r: 'PC', m: 'PC (Computer)' },
  { id:  454, r: 'lorsque', m: 'wenn / als' },
  { id:  455, r: 'choses', m: 'Sachen / Dinge' },
  { id:  456, r: 'puis', m: 'dann / danach' },
  { id:  457, r: 'Vous', m: 'Sie / Ihr (groß)' },
  { id:  458, r: 'aucun', m: 'kein' },
  { id:  459, r: 'l\'un', m: 'einer' },
  { id:  460, r: 'n\'en', m: 'nicht davon' },
  { id:  461, r: 'tandis', m: 'während (tandis que)' },
  { id:  462, r: 'coup', m: 'Schlag / Mal' },
  { id:  463, r: 'existe', m: 'existiert' },
  { id:  464, r: 'propre', m: 'eigen / sauber' },
  { id:  465, r: 'carte', m: 'Karte' },
  { id:  466, r: 'crise', m: 'Krise' },
  { id:  467, r: 'importante', m: 'wichtig (weibl.)' },
  { id:  468, r: 'atteint', m: 'erreicht' },
  { id:  469, r: 'revenus', m: 'Einkommen / Einnahmen' },
  { id:  470, r: 'montant', m: 'Betrag / Menge' },
  { id:  471, r: 'forte', m: 'stark (weibl.)' },
  { id:  472, r: 'ici', m: 'hier' },
  { id:  473, r: 's\'il', m: 'wenn er' },
  { id:  474, r: 'Quant', m: 'Was … betrifft' },
  { id:  475, r: 'vu', m: 'gesehen' },
  { id:  476, r: 'rapidement', m: 'schnell / rasch' },
  { id:  477, r: 'j\'ai', m: 'ich habe' },
  { id:  478, r: 'ville', m: 'Stadt' },
  { id:  479, r: 'etc', m: 'usw. / etc.' },
  { id:  480, r: 'mars', m: 'März' },
  { id:  481, r: 's\'en', m: 'sich davon' },
  { id:  482, r: 'mon', m: 'mein' },
  { id:  483, r: 'premiers', m: 'erste (Plural)' },
  { id:  484, r: 'bas', m: 'niedrig / unten' },
  { id:  485, r: 'marque', m: 'Marke' },
  { id:  486, r: 'véritable', m: 'echt / wahr' },
  { id:  487, r: 'ligne', m: 'Linie / Zeile' },
  { id:  488, r: 'longtemps', m: 'lange (Zeit)' },
  { id:  489, r: 'propres', m: 'eigen (Plural) / sauber' },
  { id:  490, r: 'devant', m: 'vor / vorne' },
  { id:  491, r: 'passer', m: 'vorbeigehen / verbringen' },
  { id:  492, r: 'départ', m: 'Abfahrt / Beginn' },
  { id:  493, r: 'pu', m: 'gekonnt' },
  { id:  494, r: 'total', m: 'gesamt / Total' },
  { id:  495, r: 'série', m: 'Serie / Reihe' },
  { id:  496, r: 'quoi', m: 'was' },
  { id:  497, r: 'particulier', m: 'besonders / Einzelner' },
  { id:  498, r: 'concurrence', m: 'Konkurrenz / Wettbewerb' },
  { id:  499, r: 'élevé', m: 'hoch / erhöht' },
  { id:  500, r: 'position', m: 'Position / Stelle' },
  { id:  501, r: 'connu', m: 'bekannt' },
  { id:  502, r: 'principe', m: 'Prinzip / Grundsatz' },
  { id:  503, r: 'tendance', m: 'Tendenz / Trend' },
  { id:  504, r: 'court', m: 'kurz' },
  { id:  505, r: 'n', m: 'n (Abkürzung)' },
  { id:  506, r: 'pages', m: 'Seiten' },
  { id:  507, r: 'évidemment', m: 'offensichtlich / natürlich' },
  { id:  508, r: 'résultat', m: 'Ergebnis' },
  { id:  509, r: 'aura', m: 'wird haben' },
  { id:  510, r: 'parmi', m: 'unter / zwischen' },
  { id:  511, r: 'Sans', m: 'Ohne (groß)' },
  { id:  512, r: 'américaine', m: 'amerikanisch (weibl.)' },
  { id:  513, r: 'face', m: 'Gesicht / gegenüber' },
  { id:  514, r: 'trouver', m: 'finden' },
  { id:  515, r: 'durant', m: 'während / dauern' },
  { id:  516, r: 'femmes', m: 'Frauen' },
  { id:  517, r: 'construction', m: 'Bau / Konstruktion' },
  { id:  518, r: 'désormais', m: 'fortan / ab jetzt' },
  { id:  519, r: 'distribution', m: 'Verteilung / Distribution' },
  { id:  520, r: 'telle', m: 'solch (weibl.)' },
  { id:  521, r: 'difficile', m: 'schwierig' },
  { id:  522, r: 'autour', m: 'um … herum' },
  { id:  523, r: 'européen', m: 'europäisch' },
  { id:  524, r: 'pratique', m: 'Praxis / praktisch' },
  { id:  525, r: 'centre', m: 'Zentrum / Mitte' },
  { id:  526, r: 'vendre', m: 'verkaufen' },
  { id:  527, r: 'juillet', m: 'Juli' },
  { id:  528, r: 'mai', m: 'Mai' },
  { id:  529, r: 'région', m: 'Region' },
  { id:  530, r: 'sociale', m: 'sozial (weibl.)' },
  { id:  531, r: 'filiale', m: 'Tochtergesellschaft' },
  { id:  532, r: 'film', m: 'Film' },
  { id:  533, r: 'h', m: 'h (Abkürzung / Stunde)' },
  { id:  534, r: 'besoin', m: 'Bedarf / Bedürfnis' },
  { id:  535, r: 'mode', m: 'Modus / Mode' },
  { id:  536, r: 'Pas', m: 'Nicht (groß)' },
  { id:  537, r: 'représente', m: 'repräsentiert' },
  { id:  538, r: 'réalité', m: 'Realität / Wirklichkeit' },
  { id:  539, r: 'femme', m: 'Frau' },
  { id:  540, r: 'vaut', m: 'ist wert' },
  { id:  541, r: 'Tél', m: 'Tel. (Telefon)' },
  { id:  542, r: 'aucune', m: 'keine (weibl.)' },
  { id:  543, r: 'hommes', m: 'Männer / Menschen' },
  { id:  544, r: 'donner', m: 'geben' },
  { id:  545, r: 'titres', m: 'Titel / Wertpapiere' },
  { id:  546, r: 'l\'Europe', m: 'Europa' },
  { id:  547, r: 'nombreuses', m: 'zahlreich (weibl. Plural)' },
  { id:  548, r: 'différentes', m: 'verschieden (weibl. Plural)' },
  { id:  549, r: 'moyens', m: 'Mittel (Plural) / durchschnittlich' },
  { id:  550, r: 'formation', m: 'Ausbildung / Bildung' },
  { id:  551, r: 'chiffres', m: 'Zahlen' },
  { id:  552, r: 'Générale', m: 'Allgemein (weibl., groß)' },
  { id:  553, r: 'dix', m: 'zehn' },
  { id:  554, r: 'prochain', m: 'nächste' },
  { id:  555, r: 'l\'Etat', m: 'der Staat' },
  { id:  556, r: 'genre', m: 'Art / Genre' },
  { id:  557, r: 'bureau', m: 'Büro' },
  { id:  558, r: 'communication', m: 'Kommunikation' },
  { id:  559, r: 'participation', m: 'Beteiligung / Teilnahme' },
  { id:  560, r: 'gros', m: 'groß / dick / Großteil' },
  { id:  561, r: 'pourquoi', m: 'warum' },
  { id:  562, r: 'estime', m: 'schätzt / Wertschätzung' },
  { id:  563, r: 'devient', m: 'wird' },
  { id:  564, r: 'réalisé', m: 'realisiert / durchgeführt' },
  { id:  565, r: 'création', m: 'Erstellung / Erschaffung' },
  { id:  566, r: 'novembre', m: 'November' },
  { id:  567, r: 'l\'évolution', m: 'die Entwicklung' },
  { id:  568, r: 'pourra', m: 'wird können' },
  { id:  569, r: 'semaines', m: 'Wochen' },
  { id:  570, r: 'consommation', m: 'Konsum / Verbrauch' },
  { id:  571, r: 'faible', m: 'schwach / gering' },
  { id:  572, r: 'terrain', m: 'Gelände / Boden' },
  { id:  573, r: 'site', m: 'Standort / Website' },
  { id:  574, r: 'droits', m: 'Rechte' },
  { id:  575, r: 'moitié', m: 'Hälfte' },
  { id:  576, r: 'puisque', m: 'da / weil' },
  { id:  577, r: 'Du', m: 'Vom (groß)' },
  { id:  578, r: 'reprise', m: 'Aufschwung / Wiederaufnahme' },
  { id:  579, r: 'compris', m: 'verstanden / einschließlich' },
  { id:  580, r: 'projets', m: 'Projekte' },
  { id:  581, r: 'avril', m: 'April' },
  { id:  582, r: 'vont', m: 'gehen' },
  { id:  583, r: 'call', m: 'Anruf / Call' },
  { id:  584, r: 'donné', m: 'gegeben' },
  { id:  585, r: 'simplement', m: 'einfach / schlicht' },
  { id:  586, r: 'six', m: 'sechs' },
  { id:  587, r: 'firme', m: 'Firma' },
  { id:  588, r: 'perte', m: 'Verlust' },
  { id:  589, r: 'Bien', m: 'Gut / Wohl (groß)' },
  { id:  590, r: 'Philippe', m: 'Philippe (Eigenname)' },
  { id:  591, r: 'sait', m: 'weiß' },
  { id:  592, r: 'prend', m: 'nimmt' },
  { id:  593, r: 'vite', m: 'schnell' },
  { id:  594, r: 'via', m: 'über / via' },
  { id:  595, r: 'stratégie', m: 'Strategie' },
  { id:  596, r: 'vos', m: 'Ihre / eure' },
  { id:  597, r: 'jeu', m: 'Spiel' },
  { id:  598, r: 'J\'', m: 'Ich (vor Vokal)' },
  { id:  599, r: 'petites', m: 'klein (weibl. Plural)' },
  { id:  600, r: 'marketing', m: 'Marketing' },
  { id:  601, r: 'presque', m: 'fast / beinahe' },
  { id:  602, r: 'Michel', m: 'Michel (Eigenname)' },
  { id:  603, r: 'manque', m: 'Mangel / fehlt' },
  { id:  604, r: 'réaliser', m: 'realisieren / verwirklichen' },
  { id:  605, r: 'financiers', m: 'Finanziers / finanziell (Plural)' },
  { id:  606, r: 'Car', m: 'Denn (groß)' },
  { id:  607, r: 'Comment', m: 'Wie (groß)' },
  { id:  608, r: 'voiture', m: 'Auto' },
  { id:  609, r: 'chef', m: 'Chef / Anführer' },
  { id:  610, r: 'constitue', m: 'bildet / stellt dar' },
  { id:  611, r: 'Internet', m: 'Internet' },
  { id:  612, r: 'J\'ai', m: 'Ich habe (groß)' },
  { id:  613, r: 'enfin', m: 'schließlich / endlich' },
  { id:  614, r: 'net', m: 'netto / klar' },
  { id:  615, r: 'charge', m: 'Last / Aufgabe' },
  { id:  616, r: 'nature', m: 'Natur' },
  { id:  617, r: 'second', m: 'zweite' },
  { id:  618, r: 'payer', m: 'zahlen / bezahlen' },
  { id:  619, r: 'actuel', m: 'aktuell / derzeitig' },
  { id:  620, r: 'Elles', m: 'Sie (weibl. Plural, groß)' },
  { id:  621, r: 'investissements', m: 'Investitionen' },
  { id:  622, r: 'dispose', m: 'verfügt' },
  { id:  623, r: 'financier', m: 'finanziell / Finanzier' },
  { id:  624, r: 'd\'achat', m: 'Kauf-' },
  { id:  625, r: 'membres', m: 'Mitglieder' },
  { id:  626, r: 'date', m: 'Datum' },
  { id:  627, r: 'avaient', m: 'hatten' },
  { id:  628, r: 'gamme', m: 'Sortiment / Palette' },
  { id:  629, r: 'revanche', m: 'Revanche / Rache' },
  { id:  630, r: 'comment', m: 'wie / wie so' },
  { id:  631, r: 'décision', m: 'Entscheidung' },
  { id:  632, r: 'l\'avenir', m: 'die Zukunft' },
  { id:  633, r: 'tour', m: 'Turm / Runde / Tour' },
  { id:  634, r: 'actionnaires', m: 'Aktionäre' },
  { id:  635, r: 's\'y', m: 'sich darin' },
  { id:  636, r: 'solution', m: 'Lösung' },
  { id:  637, r: 'créer', m: 'erstellen / schaffen' },
  { id:  638, r: 'l\'économie', m: 'die Wirtschaft' },
  { id:  639, r: 'concerne', m: 'betrifft' },
  { id:  640, r: 'l\'époque', m: 'die Epoche / die Zeit' },
  { id:  641, r: 'belle', m: 'schön (weibl.)' },
  { id:  642, r: 'lequel', m: 'welcher' },
  { id:  643, r: 'tél', m: 'Tel. (Telefon)' },
  { id:  644, r: 'seconde', m: 'Sekunde / zweite (weibl.)' },
  { id:  645, r: 'version', m: 'Version' },
  { id:  646, r: 'Pays-Bas', m: 'Niederlande' },
  { id:  647, r: 'cher', m: 'teuer / lieber' },
  { id:  648, r: 'chacun', m: 'jeder' },
  { id:  649, r: 'lire', m: 'lesen / Lira' },
  { id:  650, r: 'techniques', m: 'Techniken / technisch (Plural)' },
  { id:  651, r: 'décidé', m: 'entschieden' },
  { id:  652, r: 'mouvement', m: 'Bewegung' },
  { id:  653, r: 'conseil', m: 'Rat / Beratung' },
  { id:  654, r: 'nécessaire', m: 'notwendig / nötig' },
  { id:  655, r: 'meilleur', m: 'besser / beste' },
  { id:  656, r: 'double', m: 'doppelt / Doppel' },
  { id:  657, r: 'sujet', m: 'Thema / Subjekt' },
  { id:  658, r: 'généralement', m: 'im Allgemeinen' },
  { id:  659, r: 'restent', m: 'bleiben' },
  { id:  660, r: 'celles', m: 'diejenigen (weibl.)' },
  { id:  661, r: 'politiques', m: 'politisch (Plural) / Politiker' },
  { id:  662, r: 'malgré', m: 'trotz' },
  { id:  663, r: 'confiance', m: 'Vertrauen' },
  { id:  664, r: 'homme', m: 'Mann' },
  { id:  665, r: 'd\'actions', m: 'von Aktien' },
  { id:  666, r: 'Certains', m: 'Bestimmte (groß)' },
  { id:  667, r: 'ayant', m: 'habend / mit' },
  { id:  668, r: 'papier', m: 'Papier' },
  { id:  669, r: 'commerce', m: 'Handel / Geschäft' },
  { id:  670, r: 'Région', m: 'Region (groß)' },
  { id:  671, r: 'Wallonie', m: 'Wallonien' },
  { id:  672, r: 'Windows', m: 'Windows' },
  { id:  673, r: 'termes', m: 'Begriffe / Bedingungen' },
  { id:  674, r: 'met', m: 'setzt / stellt' },
  { id:  675, r: 'contraire', m: 'Gegenteil / entgegengesetzt' },
  { id:  676, r: 'informations', m: 'Informationen' },
  { id:  677, r: 'l\'industrie', m: 'die Industrie' },
  { id:  678, r: 'trimestre', m: 'Quartal' },
  { id:  679, r: 'E', m: 'E (Abkürzung)' },
  { id:  680, r: 'différence', m: 'Unterschied' },
  { id:  681, r: 'certaine', m: 'bestimmt (weibl.)' },
  { id:  682, r: 'formule', m: 'Formel / Formulierung' },
  { id:  683, r: 'jusqu\'au', m: 'bis zum' },
  { id:  684, r: 'voit', m: 'sieht' },
  { id:  685, r: 'programmes', m: 'Programme' },
  { id:  686, r: 'actuelle', m: 'aktuell (weibl.)' },
  { id:  687, r: 'permis', m: 'erlaubt / Erlaubnis' },
  { id:  688, r: 'dossier', m: 'Akte / Mappe' },
  { id:  689, r: 'Quand', m: 'Wenn / Wann (groß)' },
  { id:  690, r: 'l\'heure', m: 'die Stunde / die Zeit' },
  { id:  691, r: 'guerre', m: 'Krieg' },
  { id:  692, r: 'acheter', m: 'kaufen' },
  { id:  693, r: 'rendre', m: 'zurückgeben / machen' },
  { id:  694, r: 'février', m: 'Februar' },
  { id:  695, r: 'ma', m: 'meine (weibl.)' },
  { id:  696, r: 'l\'emploi', m: 'die Beschäftigung' },
  { id:  697, r: 'main', m: 'Hand' },
  { id:  698, r: 'voire', m: 'sogar / oder gar' },
  { id:  699, r: 'bons', m: 'gut (Plural) / Gutscheine' },
  { id:  700, r: 'technologie', m: 'Technologie' },
  { id:  701, r: 'européens', m: 'europäisch (Plural)' },
  { id:  702, r: 'Sa', m: 'Sein / Ihr (weibl., groß)' },
  { id:  703, r: 'éléments', m: 'Elemente' },
  { id:  704, r: 'unique', m: 'einzigartig / einzig' },
  { id:  705, r: 'l\'eau', m: 'das Wasser' },
  { id:  706, r: 'venir', m: 'kommen' },
  { id:  707, r: 'générale', m: 'allgemein (weibl.)' },
  { id:  708, r: 'courant', m: 'aktuell / Strom' },
  { id:  709, r: 'suffit', m: 'genügt' },
  { id:  710, r: 'l\'ordre', m: 'die Ordnung' },
  { id:  711, r: 'conserver', m: 'aufbewahren / erhalten' },
  { id:  712, r: 'maximum', m: 'Maximum' },
  { id:  713, r: 'force', m: 'Kraft / Stärke' },
  { id:  714, r: 'fax', m: 'Fax' },
  { id:  715, r: 'Que', m: 'Was / Dass (groß)' },
  { id:  716, r: 'largement', m: 'weitgehend / großzügig' },
  { id:  717, r: 'milliard', m: 'Milliarde' },
  { id:  718, r: 'soient', m: 'seien' },
  { id:  719, r: 'Pierre', m: 'Pierre (Eigenname) / Stein' },
  { id:  720, r: 'devenir', m: 'werden' },
  { id:  721, r: 'l\'Union', m: 'die Union' },
  { id:  722, r: 'franc', m: 'Franken / offen' },
  { id:  723, r: 'minimum', m: 'Minimum' },
  { id:  724, r: 'mort', m: 'Tod / tot' },
  { id:  725, r: 'responsable', m: 'verantwortlich / Verantwortliche' },
  { id:  726, r: 'possibilité', m: 'Möglichkeit' },
  { id:  727, r: 'presse', m: 'Presse' },
  { id:  728, r: 'affaires', m: 'Geschäfte / Angelegenheiten' },
  { id:  729, r: 'longue', m: 'lang (weibl.)' },
  { id:  730, r: 'travers', m: 'durch / quer' },
  { id:  731, r: 'M', m: 'M (Abkürzung)' },
  { id:  732, r: 'BBL', m: 'BBL (Abkürzung)' },
  { id:  733, r: 'relativement', m: 'relativ / verhältnismäßig' },
  { id:  734, r: 'moi', m: 'ich / mich / mir' },
  { id:  735, r: 'Deux', m: 'Zwei (groß)' },
  { id:  736, r: 'présence', m: 'Anwesenheit' },
  { id:  737, r: 'européennes', m: 'europäisch (weibl. Plural)' },
  { id:  738, r: 'devraient', m: 'sollten' },
  { id:  739, r: 'groupes', m: 'Gruppen' },
  { id:  740, r: 'ensemble', m: 'zusammen / Gesamtheit' },
  { id:  741, r: 'santé', m: 'Gesundheit' },
  { id:  742, r: 'New', m: 'Neu (engl.)' },
  { id:  743, r: 'pense', m: 'denkt' },
  { id:  744, r: 'bénéfices', m: 'Gewinne' },
  { id:  745, r: 'but', m: 'Ziel / Tor' },
  { id:  746, r: 'compagnie', m: 'Gesellschaft / Unternehmen' },
  { id:  747, r: 'publique', m: 'öffentlich (weibl.)' },
  { id:  748, r: 'coeur', m: 'Herz' },
  { id:  749, r: 'revenu', m: 'Einkommen' },
  { id:  750, r: 'mesures', m: 'Maßnahmen' },
  { id:  751, r: 'table', m: 'Tisch / Tabelle' },
  { id:  752, r: 'nettement', m: 'deutlich / klar' },
  { id:  753, r: 'questions', m: 'Fragen' },
  { id:  754, r: 'd\'avoir', m: 'zu haben' },
  { id:  755, r: 'permettre', m: 'erlauben / ermöglichen' },
  { id:  756, r: 'l\'homme', m: 'der Mann / der Mensch' },
  { id:  757, r: 'Chez', m: 'Bei (groß)' },
  { id:  758, r: 'retour', m: 'Rückkehr' },
  { id:  759, r: 'qu\'elles', m: 'dass sie (weibl.)' },
  { id:  760, r: 'C', m: 'C (Abkürzung)' },
  { id:  761, r: 'majorité', m: 'Mehrheit' },
  { id:  762, r: 'potentiel', m: 'Potenzial / potenziell' },
  { id:  763, r: 'moindre', m: 'geringer / minder' },
  { id:  764, r: 'récemment', m: 'kürzlich / neulich' },
  { id:  765, r: 'secteurs', m: 'Sektoren' },
  { id:  766, r: 'réduction', m: 'Reduzierung / Rabatt' },
  { id:  767, r: 'large', m: 'breit / groß' },
  { id:  768, r: 'traitement', m: 'Behandlung / Verarbeitung' },
  { id:  769, r: 'perdu', m: 'verloren' },
  { id:  770, r: 'étrangers', m: 'Ausländer / fremd' },
  { id:  771, r: 'parents', m: 'Eltern' },
  { id:  772, r: 'l\'une', m: 'eine (von ihnen)' },
  { id:  773, r: 'fond', m: 'Hintergrund / Grund' },
  { id:  774, r: 'capacité', m: 'Kapazität / Fähigkeit' },
  { id:  775, r: 'vitesse', m: 'Geschwindigkeit' },
  { id:  776, r: 'activité', m: 'Tätigkeit / Aktivität' },
  { id:  777, r: 'l\'exercice', m: 'das Geschäftsjahr' },
  { id:  778, r: 'l\'objet', m: 'der Gegenstand / das Objekt' },
  { id:  779, r: 'quel', m: 'welcher / welche' },
  { id:  780, r: 'tient', m: 'hält' },
  { id:  781, r: 'taille', m: 'Größe / Taille' },
  { id:  782, r: 'éviter', m: 'vermeiden' },
  { id:  783, r: 'risques', m: 'Risiken' },
  { id:  784, r: 'Jean', m: 'Jean (Eigenname)' },
  { id:  785, r: 'Pourtant', m: 'Jedoch / Dennoch (groß)' },
  { id:  786, r: 'Allemagne', m: 'Deutschland' },
  { id:  787, r: 'parler', m: 'sprechen' },
  { id:  788, r: 'propos', m: 'Zweck / Betreff' },
  { id:  789, r: 'quant', m: 'was … betrifft' },
  { id:  790, r: 'signifie', m: 'bedeutet' },
  { id:  791, r: 'voie', m: 'Weg / Spur' },
  { id:  792, r: 'jouer', m: 'spielen' },
  { id:  793, r: 'prévoit', m: 'plant / sieht vor' },
  { id:  794, r: 'blanc', m: 'weiß' },
  { id:  795, r: 'noir', m: 'schwarz' },
  { id:  796, r: 'parti', m: 'Partei / gegangen' },
  { id:  797, r: 'logiciel', m: 'Software' },
  { id:  798, r: 'continue', m: 'setzt fort / weiter' },
  { id:  799, r: 'Notre', m: 'Unser (groß)' },
  { id:  800, r: 'bois', m: 'Holz / Wald' },
  { id:  801, r: 'meilleure', m: 'besser (weibl.) / beste' },
  { id:  802, r: 'l\'argent', m: 'das Geld' },
  { id:  803, r: 'perspectives', m: 'Perspektiven / Aussichten' },
  { id:  804, r: 'développer', m: 'entwickeln' },
  { id:  805, r: 'celui-ci', m: 'dieser hier' },
  { id:  806, r: 'oeuvre', m: 'Werk' },
  { id:  807, r: 'structure', m: 'Struktur' },
  { id:  808, r: 'suivre', m: 'folgen' },
  { id:  809, r: 'tiers', m: 'Drittel / Dritter' },
  { id:  810, r: 'prise', m: 'Einnahme / Griff' },
  { id:  811, r: 'professionnels', m: 'Fachleute / professionell' },
  { id:  812, r: 'raisons', m: 'Gründe' },
  { id:  813, r: 'néanmoins', m: 'nichtsdestoweniger / dennoch' },
  { id:  814, r: 'preuve', m: 'Beweis' },
  { id:  815, r: 'social', m: 'sozial' },
  { id:  816, r: 'bénéficiaire', m: 'Begünstigter / gewinnend' },
  { id:  817, r: 'couleurs', m: 'Farben' },
  { id:  818, r: 'mondial', m: 'weltweit' },
  { id:  819, r: 'Cet', m: 'Dieser (vor Vokal, groß)' },
  { id:  820, r: 'maintenant', m: 'jetzt / nun' },
  { id:  821, r: 'essentiellement', m: 'im Wesentlichen' },
  { id:  822, r: 'prévu', m: 'geplant / vorgesehen' },
  { id:  823, r: 'Japon', m: 'Japan' },
  { id:  824, r: 'prévisions', m: 'Prognosen / Vorhersagen' },
  { id:  825, r: 'centrale', m: 'zentral (weibl.) / Zentrale' },
  { id:  826, r: 'Alors', m: 'Dann / Also (groß)' },
  { id:  827, r: 'international', m: 'international' },
  { id:  828, r: 'yeux', m: 'Augen' },
  { id:  829, r: 'PME', m: 'KMU (kleine und mittlere Unternehmen)' },
  { id:  830, r: 'l\'a', m: 'es hat' },
  { id:  831, r: 'ait', m: 'habe (Konjunktiv)' },
  { id:  832, r: 'bonnes', m: 'gut (weibl. Plural)' },
  { id:  833, r: 'opérations', m: 'Operationen / Transaktionen' },
  { id:  834, r: 'pied', m: 'Fuß' },
  { id:  835, r: 'l\'art', m: 'die Kunst' },
  { id:  836, r: 'pourraient', m: 'könnten' },
  { id:  837, r: 'Londres', m: 'London' },
  { id:  838, r: 'juge', m: 'Richter / urteilt' },
  { id:  839, r: 'devra', m: 'wird müssen' },
  { id:  840, r: 'uniquement', m: 'ausschließlich / nur' },
  { id:  841, r: 'corps', m: 'Körper' },
  { id:  842, r: 'divers', m: 'verschiedene' },
  { id:  843, r: 'Parmi', m: 'Unter (groß)' },
  { id:  844, r: 'numéro', m: 'Nummer' },
  { id:  845, r: 'réduire', m: 'reduzieren' },
  { id:  846, r: 'Tous', m: 'Alle (groß)' },
  { id:  847, r: 'texte', m: 'Text' },
  { id:  848, r: 'tenu', m: 'gehalten' },
  { id:  849, r: 'budget', m: 'Budget / Haushalt' },
  { id:  850, r: 'l\'étranger', m: 'das Ausland' },
  { id:  851, r: 'pression', m: 'Druck' },
  { id:  852, r: 'mes', m: 'meine (Plural)' },
  { id:  853, r: 'n\'était', m: 'war nicht' },
  { id:  854, r: 'style', m: 'Stil' },
  { id:  855, r: 'économiques', m: 'wirtschaftlich (Plural)' },
  { id:  856, r: 'Jacques', m: 'Jacques (Eigenname)' },
  { id:  857, r: 'montre', m: 'zeigt / Uhr' },
  { id:  858, r: 'population', m: 'Bevölkerung' },
  { id:  859, r: 'analystes', m: 'Analysten' },
  { id:  860, r: 'S', m: 'S (Abkürzung)' },
  { id:  861, r: 'processus', m: 'Prozess' },
  { id:  862, r: 'placement', m: 'Anlage / Investition' },
  { id:  863, r: 'classique', m: 'klassisch' },
  { id:  864, r: 'dividende', m: 'Dividende' },
  { id:  865, r: 'rester', m: 'bleiben' },
  { id:  866, r: 'publics', m: 'öffentlich (Plural)' },
  { id:  867, r: 'fortement', m: 'stark / kräftig' },
  { id:  868, r: 'plein', m: 'voll' },
  { id:  869, r: 'wallonne', m: 'wallonisch (weibl.)' },
  { id:  870, r: 'DEM', m: 'Deutsche Mark (Währung)' },
  { id:  871, r: 'Express', m: 'Express' },
  { id:  872, r: 'faudra', m: 'wird nötig sein' },
  { id:  873, r: 'travailler', m: 'arbeiten' },
  { id:  874, r: 'Crédit', m: 'Kredit (groß)' },
  { id:  875, r: 'directement', m: 'direkt' },
  { id:  876, r: 'prime', m: 'Prämie / Prime' },
  { id:  877, r: 'Flandre', m: 'Flandern' },
  { id:  878, r: 'crédit', m: 'Kredit' },
  { id:  879, r: 'monnaie', m: 'Währung / Münze' },
  { id:  880, r: 'précise', m: 'präzisiert / genau' },
  { id:  881, r: 'appel', m: 'Aufruf / Anruf' },
  { id:  882, r: 'Autre', m: 'Andere (groß)' },
  { id:  883, r: 'travaux', m: 'Arbeiten / Bauarbeiten' },
  { id:  884, r: 'l\'occasion', m: 'die Gelegenheit' },
  { id:  885, r: 'juste', m: 'gerecht / genau' },
  { id:  886, r: 'Chaque', m: 'Jeder / Jede (groß)' },
  { id:  887, r: 'put', m: 'konnte (Vergangenheit)' },
  { id:  888, r: 'tableau', m: 'Tabelle / Gemälde' },
  { id:  889, r: 'terre', m: 'Erde / Land' },
  { id:  890, r: 'permettent', m: 'ermöglichen' },
  { id:  891, r: 'devenu', m: 'geworden' },
  { id:  892, r: 'rouge', m: 'rot' },
  { id:  893, r: 'mémoire', m: 'Gedächtnis / Speicher' },
  { id:  894, r: 'partenaires', m: 'Partner' },
  { id:  895, r: 'rapide', m: 'schnell' },
  { id:  896, r: 'travailleurs', m: 'Arbeiter / Arbeitnehmer' },
  { id:  897, r: 'joue', m: 'spielt' },
  { id:  898, r: 'objectif', m: 'Ziel / objektiv' },
  { id:  899, r: 'salle', m: 'Saal / Zimmer' },
  { id:  900, r: 'parle', m: 'spricht' },
  { id:  901, r: 'musique', m: 'Musik' },
  { id:  902, r: 'milieu', m: 'Mitte / Umfeld' },
  { id:  903, r: 'd\'entreprise', m: 'Unternehmens-' },
  { id:  904, r: 'autorités', m: 'Behörden' },
  { id:  905, r: 'chute', m: 'Fall / Sturz' },
  { id:  906, r: 'régime', m: 'Regime / Diät' },
  { id:  907, r: 'd\'autant', m: 'umso (mehr)' },
  { id:  908, r: 'liste', m: 'Liste' },
  { id:  909, r: 'opération', m: 'Operation / Transaktion' },
  { id:  910, r: 'bout', m: 'Ende / Stück' },
  { id:  911, r: 'performances', m: 'Leistungen' },
  { id:  912, r: 'électronique', m: 'elektronisch' },
  { id:  913, r: 'haute', m: 'hoch (weibl.)' },
  { id:  914, r: 'responsables', m: 'Verantwortliche' },
  { id:  915, r: 'lancé', m: 'gestartet / geworfen' },
  { id:  916, r: 'voitures', m: 'Autos' },
  { id:  917, r: 'patron', m: 'Chef / Inhaber' },
  { id:  918, r: 'Malgré', m: 'Trotz (groß)' },
  { id:  919, r: 'affiche', m: 'zeigt / Plakat' },
  { id:  920, r: 'situe', m: 'befindet sich' },
  { id:  921, r: 'B', m: 'B (Abkürzung)' },
  { id:  922, r: 'l\'image', m: 'das Bild' },
  { id:  923, r: 'études', m: 'Studien / Studium' },
  { id:  924, r: 'Microsoft', m: 'Microsoft' },
  { id:  925, r: 'condition', m: 'Bedingung' },
  { id:  926, r: 'retrouve', m: 'findet wieder' },
  { id:  927, r: 'Aux', m: 'Bei den / An den (groß)' },
  { id:  928, r: 'revient', m: 'kommt zurück' },
  { id:  929, r: 'Belgacom', m: 'Belgacom (Unternehmen)' },
  { id:  930, r: 'route', m: 'Straße / Weg' },
  { id:  931, r: 'Ensuite', m: 'Danach (groß)' },
  { id:  932, r: 'Luxembourg', m: 'Luxemburg' },
  { id:  933, r: 'campagne', m: 'Kampagne / Landschaft' },
  { id:  934, r: 'comptes', m: 'Konten / Berichte' },
  { id:  935, r: 'hors', m: 'außerhalb' },
  { id:  936, r: 'culture', m: 'Kultur' },
  { id:  937, r: 'Commission', m: 'Kommission' },
  { id:  938, r: 'd\'entre', m: 'von / zwischen' },
  { id:  939, r: 'possibilités', m: 'Möglichkeiten' },
  { id:  940, r: 'semestre', m: 'Semester / Halbjahr' },
  { id:  941, r: 'actifs', m: 'aktiv (Plural) / Vermögenswerte' },
  { id:  942, r: 'finalement', m: 'schließlich / letztendlich' },
  { id:  943, r: 'internationale', m: 'international (weibl.)' },
  { id:  944, r: 'l\'achat', m: 'der Kauf' },
  { id:  945, r: 'monétaire', m: 'monetär / Währungs-' },
  { id:  946, r: 'passage', m: 'Durchgang / Übergang' },
  { id:  947, r: 'of', m: 'von (engl.)' },
  { id:  948, r: 'justice', m: 'Gerechtigkeit / Justiz' },
  { id:  949, r: 'page', m: 'Seite' },
  { id:  950, r: 'tels', m: 'solche' },
  { id:  951, r: 'poids', m: 'Gewicht' },
  { id:  952, r: 'celle-ci', m: 'diese hier (weibl.)' },
  { id:  953, r: 'commercial', m: 'kommerziell / kaufmännisch' },
  { id:  954, r: 'entendu', m: 'gehört / natürlich' },
  { id:  955, r: 'l\'investisseur', m: 'der Investor' },
  { id:  956, r: 'mondiale', m: 'weltweit (weibl.)' },
  { id:  957, r: 'accord', m: 'Vereinbarung / Einigung' },
  { id:  958, r: 'diverses', m: 'verschiedene (weibl.)' },
  { id:  959, r: 'totalement', m: 'vollständig / total' },
  { id:  960, r: 'fil', m: 'Faden / Draht' },
  { id:  961, r: 'clair', m: 'klar / hell' },
  { id:  962, r: 'vin', m: 'Wein' },
  { id:  963, r: 'biens', m: 'Güter' },
  { id:  964, r: 'euro', m: 'Euro' },
  { id:  965, r: 'York', m: 'York (Eigenname)' },
  { id:  966, r: 'parfaitement', m: 'perfekt / vollkommen' },
  { id:  967, r: 'viennent', m: 'kommen' },
  { id:  968, r: 'division', m: 'Abteilung / Division' },
  { id:  969, r: 'réseaux', m: 'Netzwerke' },
  { id:  970, r: 'principal', m: 'Haupt- / hauptsächlich' },
  { id:  971, r: 'lancer', m: 'starten / werfen' },
  { id:  972, r: 'supérieur', m: 'überlegen / höher' },
  { id:  973, r: 'atteindre', m: 'erreichen' },
  { id:  974, r: 'référence', m: 'Referenz / Bezug' },
  { id:  975, r: 'téléphone', m: 'Telefon' },
  { id:  976, r: 'management', m: 'Management' },
  { id:  977, r: 'vins', m: 'Weine' },
  { id:  978, r: 'proche', m: 'nah' },
  { id:  979, r: 'collection', m: 'Sammlung' },
  { id:  980, r: 'fiscale', m: 'steuerlich (weibl.)' },
  { id:  981, r: 'Ceci', m: 'Dies (groß)' },
  { id:  982, r: 'informatique', m: 'Informatik / EDV' },
  { id:  983, r: 'investissement', m: 'Investition' },
  { id:  984, r: 'volume', m: 'Volumen' },
  { id:  985, r: 'matériel', m: 'Material / Hardware' },
  { id:  986, r: 'publicité', m: 'Werbung' },
  { id:  987, r: 'train', m: 'Zug' },
  { id:  988, r: 'coupon', m: 'Coupon / Gutschein' },
  { id:  989, r: 'progression', m: 'Fortschritt / Zunahme' },
  { id:  990, r: 'tenir', m: 'halten' },
  { id:  991, r: 'protection', m: 'Schutz' },
  { id:  992, r: 'l\'aide', m: 'die Hilfe' },
  { id:  993, r: 'couleur', m: 'Farbe' },
  { id:  994, r: 'nouvel', m: 'neu (vor Vokal)' },
  { id:  995, r: 'Lorsque', m: 'Als / Wenn (groß)' },
  { id:  996, r: 'change', m: 'ändert / Wechsel' },
  { id:  997, r: 'changement', m: 'Veränderung / Wechsel' },
  { id:  998, r: 'garantie', m: 'Garantie' },
  { id:  999, r: 'somme', m: 'Summe' },
  { id: 1000, r: 'Belge', m: 'Belgier / belgisch (groß)' },
];

const FRENCH_PHRASES = {
  'Notfall-Basics': [
    { r: 'Au secours !',                              d: 'Hilfe!',                                  gap: 'secours',     distractors: ['revoir', 'plait', 'merci'] },
    { r: 'Parlez-vous anglais ?',                     d: 'Sprechen Sie Englisch?',                  gap: 'anglais',     distractors: ['français', 'allemand', 'arabe'] },
    { r: 'Je ne comprends pas.',                      d: 'Ich verstehe nicht.',                     gap: 'comprends',   distractors: ['parle', 'vois', 'veux'] },
    { r: "Parlez plus lentement, s'il vous plaît.",   d: 'Bitte sprechen Sie langsamer.',           gap: 'lentement',   distractors: ['vite', 'fort', 'bien'] },
    { r: "Je m'appelle ...",                          d: 'Mein Name ist ...',                       gap: 'appelle',     distractors: ['suis', 'viens', 'habite'] },
    { r: "Je viens d'Allemagne.",                     d: 'Ich komme aus Deutschland.',              gap: 'Allemagne',   distractors: ['France', 'Angleterre', 'Espagne'] },
  ],
  'Im Restaurant': [
    { r: 'Avez-vous un menu ?',                       d: 'Haben Sie eine Speisekarte?',             gap: 'menu',        distractors: ['thé', 'plat', 'eau'] },
    { r: "Qu'est-ce que c'est comme plat ?",          d: 'Was ist das für ein Gericht?',            gap: 'plat',        distractors: ['boisson', 'dessert', 'entrée'] },
    { r: "L'addition, s'il vous plaît.",              d: 'Die Rechnung bitte.',                     gap: 'addition',    distractors: ['menu', 'thé', 'eau'] },
    { r: "C'était délicieux !",                       d: 'Es war köstlich!',                        gap: 'délicieux',   distractors: ['cher', 'froid', 'chaud'] },
    { r: "Sans viande, s'il vous plaît.",             d: 'Ohne Fleisch bitte.',                     gap: 'viande',      distractors: ['sel', 'huile', 'lait'] },
  ],
  'Unterwegs': [
    { r: 'Je voudrais aller à ...',                   d: 'Ich möchte nach ... fahren.',             gap: 'voudrais',    distractors: ['peux', 'dois', 'vais'] },
    { r: 'Où se trouve cette adresse ?',              d: 'Wo ist diese Adresse?',                   gap: 'adresse',     distractors: ['métro', 'hôtel', 'marché'] },
    { r: "À quelle heure est-ce ouvert ?",            d: 'Wann öffnet es?',                         gap: 'ouvert',      distractors: ['fermé', 'libre', 'prêt'] },
    { r: 'Combien de minutes à pied ?',               d: 'Wie viele Minuten zu Fuß?',               gap: 'minutes',     distractors: ['kilomètres', 'heures', 'jours'] },
    { r: "Arrêtez ici, s'il vous plaît.",             d: 'Bitte hier anhalten. (Taxi)',             gap: 'Arrêtez',     distractors: ['Continuez', 'Tournez', 'Allez'] },
  ],
  'Einkaufen': [
    { r: "C'est combien ?",                           d: 'Wie viel kostet das?',                    gap: 'combien',     distractors: ['quand', 'quoi', 'où'] },
    { r: "C'est cher.",                               d: 'Das ist teuer.',                          gap: 'cher',        distractors: ['bon', 'frais', 'beau'] },
    { r: 'Avez-vous quelque chose de moins cher ?',   d: 'Haben Sie etwas Günstigeres?',            gap: 'moins',       distractors: ['plus', 'très', 'trop'] },
    { r: 'Je le prends.',                             d: 'Ich nehme es.',                           gap: 'prends',      distractors: ['vois', 'veux', 'fais'] },
  ],
  'Zahlen & Zeit': [
    { r: 'Quelle heure est-il ?',                     d: 'Wie viel Uhr ist es?',                    gap: 'heure',       distractors: ['jour', 'mois', 'semaine'] },
    { r: "Quelle est la date aujourd'hui ?",          d: 'Welches Datum ist heute?',                gap: 'date',        distractors: ['heure', 'semaine', 'mois'] },
    { r: 'Demain / Hier',                             d: 'Morgen / Gestern',                        gap: 'Demain',      distractors: ["Aujourd'hui", 'Ce soir', 'Maintenant'] },
    { r: 'Matin / Après-midi / Soir',                 d: 'Morgen / Nachmittag / Abend',             gap: 'Soir',        distractors: ['Nuit', 'Midi', 'Minuit'] },
  ],
  'Begrüßung & Verabschiedung': [
    { r: 'Bonjour ! Comment allez-vous ?',            d: 'Hallo! Wie geht es Ihnen?',               gap: 'allez',       distractors: ['êtes', 'avez', 'faites'] },
    { r: 'Bien, merci. Et vous ?',                    d: 'Gut, danke. Und Ihnen?',                  gap: 'merci',       distractors: ['pardon', 'voilà', 'désolé'] },
    { r: 'Au revoir.',                                d: 'Auf Wiedersehen.',                        gap: 'revoir',      distractors: ['secours', 'plaisir', 'travail'] },
    { r: 'Adieu.',                                    d: 'Lebwohl. (formeller Abschied)',           gap: 'Adieu',       distractors: ['Bonjour', 'Merci', 'Pardon'] },
    { r: 'Bonne nuit.',                               d: 'Gute Nacht.',                             gap: 'nuit',        distractors: ['journée', 'soirée', 'matinée'] },
    { r: 'Bonjour.',                                  d: 'Guten Morgen.',                           gap: 'Bonjour',     distractors: ['Bonsoir', 'Salut', 'Allô'] },
    { r: 'Bienvenue !',                               d: 'Willkommen!',                             gap: 'Bienvenue',   distractors: ['Merci', 'Pardon', 'Désolé'] },
    { r: 'À la prochaine fois.',                      d: 'Bis zum nächsten Mal.',                   gap: 'prochaine',   distractors: ['dernière', 'première', 'bonne'] },
  ],
  'Bei jemandem zuhause': [
    { r: "Entrez, s'il vous plaît.",                  d: 'Bitte, treten Sie ein.',                  gap: 'Entrez',      distractors: ['Restez', 'Allez', 'Venez'] },
    { r: "Merci pour l'invitation.",                  d: 'Danke für die Einladung.',                gap: 'invitation',  distractors: ['aide', 'repas', 'visite'] },
    { r: 'Votre maison est belle !',                  d: 'Ihr Zuhause ist schön!',                  gap: 'belle',       distractors: ['grande', 'froide', 'chère'] },
    { r: 'Avez-vous besoin de quelque chose ?',       d: 'Brauchen Sie etwas?',                     gap: 'besoin',      distractors: ['envie', 'peur', 'temps'] },
    { r: 'Voulez-vous du thé ?',                      d: 'Möchten Sie Tee?',                        gap: 'thé',         distractors: ['café', 'eau', 'vin'] },
    { r: "Merci, j'ai assez mangé.",                  d: 'Danke, ich bin satt.',                    gap: 'assez',       distractors: ['bien', 'peu', 'trop'] },
    { r: 'Le repas était très délicieux.',            d: 'Das Essen war sehr lecker.',               gap: 'très',        distractors: ['peu', 'trop', 'assez'] },
    { r: 'Avec votre permission, je dois partir.',    d: 'Mit Ihrer Erlaubnis, ich gehe jetzt.',    gap: 'partir',      distractors: ['rester', 'manger', 'dormir'] },
  ],
  'Arzt & Apotheke': [
    { r: 'Je ne me sens pas bien.',                   d: 'Ich fühle mich nicht gut.',               gap: 'sens',        distractors: ['vais', 'vois', 'suis'] },
    { r: "J'ai mal ici.",                             d: 'Hier tut es weh.',                        gap: 'mal',         distractors: ['bien', 'chaud', 'froid'] },
    { r: 'Avez-vous un remède contre le rhume ?',     d: 'Haben Sie ein Mittel gegen Erkältung?',   gap: 'rhume',       distractors: ['mal', 'fièvre', 'toux'] },
    { r: "Est-ce que j'ai besoin d'une ordonnance ?", d: 'Brauche ich ein Rezept?',                 gap: 'ordonnance',  distractors: ['médicament', 'argent', 'temps'] },
    { r: 'Je suis allergique à ce médicament.',       d: 'Ich bin gegen dieses Medikament allergisch.', gap: 'allergique', distractors: ['habitué', 'sensible', 'opposé'] },
    { r: "J'ai besoin d'un médecin.",                 d: 'Ich brauche einen Arzt.',                 gap: 'médecin',     distractors: ['médicament', 'pharmacie', 'hôpital'] },
    { r: 'Où sont les toilettes ?',                   d: 'Wo ist die Toilette?',                    gap: 'toilettes',   distractors: ['pharmacie', 'hôpital', 'sortie'] },
  ],
  'Smalltalk': [
    { r: "D'où venez-vous ?",                         d: 'Woher kommen Sie?',                       gap: 'venez',       distractors: ['êtes', 'allez', 'habitez'] },
    { r: "Je viens d'Allemagne.",                     d: 'Ich komme aus Deutschland.',              gap: 'Allemagne',   distractors: ['France', 'Espagne', 'Russie'] },
    { r: 'Je ne parle pas bien français.',            d: 'Ich spreche nicht gut Französisch.',      gap: 'français',    distractors: ['anglais', 'allemand', 'espagnol'] },
    { r: "Pouvez-vous m'apprendre ?",                 d: 'Können Sie es mir beibringen?',           gap: 'apprendre',   distractors: ['expliquer', 'montrer', 'dire'] },
    { r: 'Comment dit-on ça en français ?',           d: 'Wie sagt man das auf Französisch?',       gap: 'français',    distractors: ['anglais', 'allemand', 'espagnol'] },
    { r: 'Que faites-vous dans la vie ?',             d: 'Was machen Sie beruflich?',               gap: 'faites',      distractors: ['êtes', 'avez', 'aimez'] },
    { r: "J'aime la France.",                         d: 'Ich mag Frankreich.',                     gap: 'France',      distractors: ['Paris', 'langue', 'cuisine'] },
    { r: "J'espère revenir.",                         d: 'Ich hoffe, wieder zu kommen.',            gap: 'revenir',     distractors: ['partir', 'rester', 'voyager'] },
  ],
};
