const SPANISH_VOCAB = [
  { id:    1, r: 'la', m: 'die / sie (Artikel/Pronomen)' },
  { id:    2, r: 'el', m: 'der (Artikel)' },
  { id:    3, r: 'que', m: 'dass / was / welche' },
  { id:    4, r: 'de', m: 'von / aus' },
  { id:    5, r: 'en', m: 'in / auf' },
  { id:    6, r: 'y', m: 'und' },
  { id:    7, r: 'a', m: 'zu / bei / nach' },
  { id:    8, r: 'ser', m: 'sein (dauerhaft)' },
  { id:    9, r: 'no', m: 'nein / nicht' },
  { id:   10, r: 'se', m: '(Reflexivpronomen)' },
  { id:   11, r: 'un', m: 'ein (männl.)' },
  { id:   12, r: 'lo', m: 'es / ihn (Pronomen)' },
  { id:   13, r: 'decir', m: 'sagen / erzählen' },
  { id:   14, r: 'hacer', m: 'machen / tun' },
  { id:   15, r: 'su', m: 'sein / ihr / Ihr' },
  { id:   16, r: 'haber', m: 'haben (Hilfsverb)' },
  { id:   17, r: 'tener', m: 'haben / besitzen' },
  { id:   18, r: 'me', m: 'mir / mich' },
  { id:   19, r: 'otro', m: 'anderer / ein weiterer' },
  { id:   20, r: 'por', m: 'für / durch / pro' },
  { id:   21, r: 'con', m: 'mit' },
  { id:   22, r: 'todo', m: 'alles / jeder / ganz' },
  { id:   23, r: 'más', m: 'mehr' },
  { id:   24, r: 'para', m: 'für / um zu' },
  { id:   25, r: 'yo', m: 'ich' },
  { id:   26, r: 'como', m: 'wie / als' },
  { id:   27, r: 'si', m: 'ob / wenn / falls' },
  { id:   28, r: 'poder', m: 'können / dürfen' },
  { id:   29, r: 'dar', m: 'geben' },
  { id:   30, r: 'le', m: '(indirektes Objektpronomen 3. Person)' },
  { id:   31, r: 'estar', m: 'sein (vorübergehend)' },
  { id:   32, r: 'pero', m: 'aber / jedoch' },
  { id:   33, r: 'qué', m: 'was? / wie!' },
  { id:   34, r: 'este', m: 'dieser (männl.)' },
  { id:   35, r: 'entre', m: 'zwischen / unter' },
  { id:   36, r: 'pasar', m: 'vergehen / vorbeigehen' },
  { id:   37, r: 'mi', m: 'mein' },
  { id:   38, r: 'uno', m: 'eins / man' },
  { id:   39, r: 'primero', m: 'erste' },
  { id:   40, r: 'donde', m: 'wo' },
  { id:   41, r: 'porque', m: 'weil' },
  { id:   42, r: 'deber', m: 'sollen / müssen / schulden' },
  { id:   43, r: 'ese', m: 'jener (männl.)' },
  { id:   44, r: 'sí', m: 'ja' },
  { id:   45, r: 'nos', m: 'uns' },
  { id:   46, r: 'ni', m: 'weder … noch' },
  { id:   47, r: 'sobre', m: 'über / auf' },
  { id:   48, r: 'o', m: 'oder' },
  { id:   49, r: 'cuando', m: 'wann / wenn / als' },
  { id:   50, r: 'hombre', m: 'Mann / Mensch' },
  { id:   51, r: 'grande', m: 'groß / bedeutend' },
  { id:   52, r: 'ir', m: 'gehen / fahren' },
  { id:   53, r: 'alguno', m: 'irgendein / jemand' },
  { id:   54, r: 'muy', m: 'sehr' },
  { id:   55, r: 'forma', m: 'Form / Art / Weise' },
  { id:   56, r: 'cada', m: 'jeder / jede / jedes' },
  { id:   57, r: 'algo', m: 'etwas / irgendwie' },
  { id:   58, r: 'tres', m: 'drei' },
  { id:   59, r: 'ya', m: 'schon / bereits / jetzt' },
  { id:   60, r: 'dos', m: 'zwei' },
  { id:   61, r: 'momento', m: 'Moment / Augenblick' },
  { id:   62, r: 'menos', m: 'weniger / außer' },
  { id:   63, r: 'hasta', m: 'bis / sogar' },
  { id:   64, r: 'vez', m: 'Mal (zeitlich)' },
  { id:   65, r: 'así', m: 'so / auf diese Weise' },
  { id:   66, r: 'esto', m: 'das / dies (sächlich)' },
  { id:   67, r: 'ver', m: 'sehen' },
  { id:   68, r: 'cierto', m: 'sicher / gewiss / bestimmt' },
  { id:   69, r: 'mundo', m: 'Welt' },
  { id:   70, r: 'poner', m: 'stellen / legen / setzen' },
  { id:   71, r: 'sin', m: 'ohne' },
  { id:   72, r: 'punto', m: 'Punkt' },
  { id:   73, r: 'mucho', m: 'viel / sehr' },
  { id:   74, r: 'después', m: 'danach / nachher' },
  { id:   75, r: 'cosa', m: 'Sache / Ding' },
  { id:   76, r: 'él', m: 'er' },
  { id:   77, r: 'casi', m: 'fast / beinahe' },
  { id:   78, r: 'llegar', m: 'ankommen / erreichen' },
  { id:   79, r: 'tan', m: 'so / solch' },
  { id:   80, r: 'también', m: 'auch / ebenfalls' },
  { id:   81, r: 'hablar', m: 'sprechen / reden' },
  { id:   82, r: 'mujer', m: 'Frau' },
  { id:   83, r: 'ella', m: 'sie (weibl.)' },
  { id:   84, r: 'hora', m: 'Stunde / Uhrzeit' },
  { id:   85, r: 'ahora', m: 'jetzt / nun' },
  { id:   86, r: 'propio', m: 'eigen / typisch' },
  { id:   87, r: 'saber', m: 'wissen / kennen' },
  { id:   88, r: 'tanto', m: 'so viel / so sehr' },
  { id:   89, r: 'pensar', m: 'denken / nachdenken' },
  { id:   90, r: 'desde', m: 'seit / von … an' },
  { id:   91, r: 'mejor', m: 'besser / beste' },
  { id:   92, r: 'niño', m: 'Kind / Junge' },
  { id:   93, r: 'mismo', m: 'gleich / selbst' },
  { id:   94, r: 'tipo', m: 'Typ / Art' },
  { id:   95, r: 'pequeño', m: 'klein / jung' },
  { id:   96, r: 'te', m: 'dich / dir' },
  { id:   97, r: 'año', m: 'Jahr' },
  { id:   98, r: 'allí', m: 'dort / da drüben' },
  { id:   99, r: 'parte', m: 'Teil / Abschnitt' },
  { id:  100, r: 'vida', m: 'Leben' },
  { id:  101, r: 'trabajo', m: 'Arbeit / Job' },
  { id:  102, r: 'querer', m: 'wollen / lieben' },
  { id:  103, r: 'nombre', m: 'Name / Substantiv' },
  { id:  104, r: 'casa', m: 'Haus' },
  { id:  105, r: 'país', m: 'Land' },
  { id:  106, r: 'siempre', m: 'immer / stets' },
  { id:  107, r: 'volver', m: 'zurückkehren / wieder tun' },
  { id:  108, r: 'tiempo', m: 'Zeit / Wetter' },
  { id:  109, r: 'mayor', m: 'größer / älter / Haupt-' },
  { id:  110, r: 'eso', m: 'das / jenes (sächlich)' },
  { id:  111, r: 'bajo', m: 'unter / unterhalb' },
  { id:  112, r: 'nada', m: 'nichts / überhaupt nicht' },
  { id:  113, r: 'persona', m: 'Person' },
  { id:  114, r: 'bien', m: 'gut / wohl' },
  { id:  115, r: 'nuestro', m: 'unser' },
  { id:  116, r: 'antes', m: 'vorher / früher' },
  { id:  117, r: 'historia', m: 'Geschichte / Erzählung' },
  { id:  118, r: 'poco', m: 'wenig / ein bisschen' },
  { id:  119, r: 'durante', m: 'während / für' },
  { id:  120, r: 'quien', m: 'wer / der/die/das' },
  { id:  121, r: 'lugar', m: 'Ort / Platz' },
  { id:  122, r: 'realidad', m: 'Wirklichkeit / Realität' },
  { id:  123, r: 'presentar', m: 'vorstellen / präsentieren' },
  { id:  124, r: 'conocer', m: 'kennen / jemanden kennen' },
  { id:  125, r: 'vivir', m: 'leben' },
  { id:  126, r: 'hecho', m: 'Tatsache / Ereignis' },
  { id:  127, r: 'entonces', m: 'dann / also' },
  { id:  128, r: 'día', m: 'Tag' },
  { id:  129, r: 'salir', m: 'ausgehen / verlassen' },
  { id:  130, r: 'llamar', m: 'nennen / anrufen' },
  { id:  131, r: 'cuatro', m: 'vier' },
  { id:  132, r: 'seguir', m: 'folgen / weitermachen' },
  { id:  133, r: 'recordar', m: 'erinnern / erinnern an' },
  { id:  134, r: 'cambio', m: 'Veränderung / Wechsel' },
  { id:  135, r: 'blanco', m: 'weiß' },
  { id:  136, r: 'sacar', m: 'herausnehmen / herausholen' },
  { id:  137, r: 'conseguir', m: 'bekommen / erreichen' },
  { id:  138, r: 'aquel', m: 'jener (dort)' },
  { id:  139, r: 'empezar', m: 'anfangen / beginnen' },
  { id:  140, r: 'modo', m: 'Art / Weise' },
  { id:  141, r: 'llevar', m: 'tragen / mitnehmen' },
  { id:  142, r: 'amigo', m: 'Freund' },
  { id:  143, r: 'tema', m: 'Thema / Betreff' },
  { id:  144, r: 'creer', m: 'glauben / denken' },
  { id:  145, r: 'dejar', m: 'lassen / verlassen' },
  { id:  146, r: 'existir', m: 'existieren' },
  { id:  147, r: 'verdad', m: 'Wahrheit' },
  { id:  148, r: 'aquí', m: 'hier' },
  { id:  149, r: 'ciudad', m: 'Stadt' },
  { id:  150, r: 'general', m: 'allgemein / General' },
  { id:  151, r: 'sólo', m: 'nur / lediglich' },
  { id:  152, r: 'aunque', m: 'obwohl / auch wenn' },
  { id:  153, r: 'calle', m: 'Straße' },
  { id:  154, r: 'parecer', m: 'scheinen / aussehen wie' },
  { id:  155, r: 'manera', m: 'Art / Weise / Methode' },
  { id:  156, r: 'recibir', m: 'empfangen / erhalten' },
  { id:  157, r: 'quedar', m: 'bleiben / verbleiben' },
  { id:  158, r: 'preguntar', m: 'fragen' },
  { id:  159, r: 'trabajar', m: 'arbeiten' },
  { id:  160, r: 'esperar', m: 'warten / hoffen / erwarten' },
  { id:  161, r: 'aceptar', m: 'akzeptieren' },
  { id:  162, r: 'formar', m: 'formen / bilden' },
  { id:  163, r: 'hacia', m: 'in Richtung / gegen' },
  { id:  164, r: 'sino', m: 'sondern / außer' },
  { id:  165, r: 'aún', m: 'noch / immer noch' },
  { id:  166, r: 'nunca', m: 'nie / niemals' },
  { id:  167, r: 'bueno', m: 'gut' },
  { id:  168, r: 'caso', m: 'Fall / Angelegenheit' },
  { id:  169, r: 'mano', m: 'Hand' },
  { id:  170, r: 'nuevo', m: 'neu' },
  { id:  171, r: 'pueblo', m: 'Volk / Dorf' },
  { id:  172, r: 'cuanto', m: 'wie viel / was … betrifft' },
  { id:  173, r: 'solo', m: 'allein / einsam' },
  { id:  174, r: 'sentir', m: 'fühlen / bereuen' },
  { id:  175, r: 'medio', m: 'Mitte / Hälfte' },
  { id:  176, r: 'alcanzar', m: 'erreichen / einholen' },
  { id:  177, r: 'cuyo', m: 'dessen / deren' },
  { id:  178, r: 'jugar', m: 'spielen' },
  { id:  179, r: 'fuerza', m: 'Kraft / Stärke' },
  { id:  180, r: 'tarde', m: 'Nachmittag / Abend' },
  { id:  181, r: 'tal', m: 'solch ein' },
  { id:  182, r: 'posible', m: 'möglich' },
  { id:  183, r: 'ejemplo', m: 'Beispiel' },
  { id:  184, r: 'tratar', m: 'behandeln / versuchen' },
  { id:  185, r: 'crear', m: 'erschaffen / erstellen' },
  { id:  186, r: 'encontrar', m: 'finden' },
  { id:  187, r: 'ante', m: 'vor / angesichts' },
  { id:  188, r: 'ser', m: 'Wesen / Sein' },
  { id:  189, r: 'aire', m: 'Luft / Wind' },
  { id:  190, r: 'venir', m: 'kommen' },
  { id:  191, r: 'escribir', m: 'schreiben' },
  { id:  192, r: 'viejo', m: 'alt / betagt' },
  { id:  193, r: 'palabra', m: 'Wort' },
  { id:  194, r: 'obra', m: 'Werk / Tat' },
  { id:  195, r: 'ninguno', m: 'kein / niemand' },
  { id:  196, r: 'mí', m: 'mir / mich (betont)' },
  { id:  197, r: 'pues', m: 'also / dann / denn' },
  { id:  198, r: 'situación', m: 'Situation / Lage' },
  { id:  199, r: 'campo', m: 'Feld / Land' },
  { id:  200, r: 'luego', m: 'danach / später' },
  { id:  201, r: 'dentro', m: 'innen / drinnen' },
  { id:  202, r: 'cuenta', m: 'Konto / Rechnung' },
  { id:  203, r: 'cuerpo', m: 'Körper' },
  { id:  204, r: 'segundo', m: 'Sekunde / zweite' },
  { id:  205, r: 'cual', m: 'welche / der/die/das' },
  { id:  206, r: 'cambiar', m: 'ändern / wechseln' },
  { id:  207, r: 'ocurrir', m: 'geschehen / passieren' },
  { id:  208, r: 'luz', m: 'Licht' },
  { id:  209, r: 'anterior', m: 'vorherig / vorausgehend' },
  { id:  210, r: 'menor', m: 'jünger / kleiner' },
  { id:  211, r: 'aparecer', m: 'erscheinen / auftauchen' },
  { id:  212, r: 'éste', m: 'dieser hier' },
  { id:  213, r: 'gente', m: 'Leute / Menschen' },
  { id:  214, r: 'tomar', m: 'nehmen / trinken' },
  { id:  215, r: 'escuchar', m: 'zuhören / anhören' },
  { id:  216, r: 'gracia', m: 'Gnade / Dank (pl.)' },
  { id:  217, r: 'además', m: 'außerdem / zudem' },
  { id:  218, r: 'gustar', m: 'gefallen / mögen' },
  { id:  219, r: 'varios', m: 'mehrere / verschiedene' },
  { id:  220, r: 'cabeza', m: 'Kopf' },
  { id:  221, r: 'efecto', m: 'Wirkung / Effekt' },
  { id:  222, r: 'mantener', m: 'aufrechterhalten / behalten' },
  { id:  223, r: 'santo', m: 'Heiliger' },
  { id:  224, r: 'quizás', m: 'vielleicht' },
  { id:  225, r: 'servicio', m: 'Dienst / Service' },
  { id:  226, r: 'cinco', m: 'fünf' },
  { id:  227, r: 'tierra', m: 'Erde / Land / Boden' },
  { id:  228, r: 'cómo', m: 'wie?' },
  { id:  229, r: 'comprender', m: 'verstehen' },
  { id:  230, r: 'comer', m: 'essen' },
  { id:  231, r: 'contar', m: 'zählen / erzählen' },
  { id:  232, r: 'mil', m: 'tausend' },
  { id:  233, r: 'programa', m: 'Programm / Plan' },
  { id:  234, r: 'distinto', m: 'unterschiedlich / verschieden' },
  { id:  235, r: 'ahí', m: 'dort / da' },
  { id:  236, r: 'último', m: 'letzte / final' },
  { id:  237, r: 'don', m: 'Herr / Gabe' },
  { id:  238, r: 'pedir', m: 'bitten / bestellen' },
  { id:  239, r: 'agua', m: 'Wasser' },
  { id:  240, r: 'abrir', m: 'öffnen' },
  { id:  241, r: 'valor', m: 'Wert / Mut' },
  { id:  242, r: 'embargo', m: 'sin embargo: trotzdem' },
  { id:  243, r: 'fácil', m: 'einfach / leicht' },
  { id:  244, r: 'nadie', m: 'niemand' },
  { id:  245, r: 'contrario', m: 'Gegenteil / entgegengesetzt' },
  { id:  246, r: 'imaginar', m: 'sich vorstellen' },
  { id:  247, r: 'junto', m: 'zusammen / neben' },
  { id:  248, r: 'partido', m: 'Partie / Partei / Spiel' },
  { id:  249, r: 'ciento', m: 'hundert' },
  { id:  250, r: 'leer', m: 'lesen' },
  { id:  251, r: 'pregunta', m: 'Frage' },
  { id:  252, r: 'español', m: 'Spanisch / Spanier' },
  { id:  253, r: 'hoy', m: 'heute' },
  { id:  254, r: 'mesa', m: 'Tisch / Tafel' },
  { id:  255, r: 'cualquier', m: 'irgendein / beliebig' },
  { id:  256, r: 'seguridad', m: 'Sicherheit' },
  { id:  257, r: 'mirar', m: 'schauen / ansehen' },
  { id:  258, r: 'estudiar', m: 'studieren / lernen' },
  { id:  259, r: 'lado', m: 'Seite' },
  { id:  260, r: 'mientras', m: 'während / solange' },
  { id:  261, r: 'base', m: 'Basis / Grundlage' },
  { id:  262, r: 'época', m: 'Epoche / Zeitalter' },
  { id:  263, r: 'claro', m: 'klar / natürlich' },
  { id:  264, r: 'clase', m: 'Klasse / Art' },
  { id:  265, r: 'quién', m: 'wer?' },
  { id:  266, r: 'alto', m: 'hoch / groß' },
  { id:  267, r: 'problema', m: 'Problem' },
  { id:  268, r: 'antiguo', m: 'alt / ehemalig' },
  { id:  269, r: 'posibilidad', m: 'Möglichkeit' },
  { id:  270, r: 'vista', m: 'Aussicht / Blick' },
  { id:  271, r: 'obtener', m: 'erhalten / bekommen' },
  { id:  272, r: 'centro', m: 'Mitte / Zentrum' },
  { id:  273, r: 'carta', m: 'Brief / Spielkarte' },
  { id:  274, r: 'pobre', m: 'arm' },
  { id:  275, r: 'contra', m: 'gegen / gegenüber' },
  { id:  276, r: 'hijo', m: 'Sohn / (pl.) Kinder' },
  { id:  277, r: 'mostrar', m: 'zeigen' },
  { id:  278, r: 'interés', m: 'Interesse' },
  { id:  279, r: 'término', m: 'Begriff / Ende' },
  { id:  280, r: 'buscar', m: 'suchen' },
  { id:  281, r: 'especial', m: 'besonders / speziell' },
  { id:  282, r: 'político', m: 'politisch' },
  { id:  283, r: 'desear', m: 'wünschen / begehren' },
  { id:  284, r: 'necesario', m: 'notwendig' },
  { id:  285, r: 'terminar', m: 'beenden / fertig werden' },
  { id:  286, r: 'perder', m: 'verlieren / verpassen' },
  { id:  287, r: 'deseo', m: 'Wunsch / Begehren' },
  { id:  288, r: 'padre', m: 'Vater' },
  { id:  289, r: 'tampoco', m: 'auch nicht / weder noch' },
  { id:  290, r: 'señor', m: 'Herr' },
  { id:  291, r: 'resultar', m: 'sich herausstellen / ergeben' },
  { id:  292, r: 'función', m: 'Funktion / Veranstaltung' },
  { id:  293, r: 'noche', m: 'Nacht / Abend' },
  { id:  294, r: 'largo', m: 'lang' },
  { id:  295, r: 'familia', m: 'Familie' },
  { id:  296, r: 'desarrollar', m: 'entwickeln' },
  { id:  297, r: 'seis', m: 'sechs' },
  { id:  298, r: 'bajo', m: 'niedrig / klein' },
  { id:  299, r: 'producir', m: 'herstellen / erzeugen' },
  { id:  300, r: 'segundo', m: 'zweite / Sekunde' },
  { id:  301, r: 'inglés', m: 'Englisch / Engländer' },
  { id:  302, r: 'negro', m: 'schwarz' },
  { id:  303, r: 'miedo', m: 'Angst / Furcht' },
  { id:  304, r: 'entrar', m: 'eintreten / hineingehen' },
  { id:  305, r: 'dedicar', m: 'widmen' },
  { id:  306, r: 'paso', m: 'Schritt / Gang' },
  { id:  307, r: 'usted', m: 'Sie (formell)' },
  { id:  308, r: 'río', m: 'Fluss' },
  { id:  309, r: 'dirección', m: 'Richtung / Adresse' },
  { id:  310, r: 'cuestión', m: 'Frage / Angelegenheit' },
  { id:  311, r: 'derecho', m: 'Recht / Gerechtigkeit' },
  { id:  312, r: 'malo', m: 'schlecht / böse' },
  { id:  313, r: 'principio', m: 'Anfang / Prinzip' },
  { id:  314, r: 'guerra', m: 'Krieg' },
  { id:  315, r: 'único', m: 'einzigartig / einzig' },
  { id:  316, r: 'avanzar', m: 'voranschreiten / vorrücken' },
  { id:  317, r: 'entender', m: 'verstehen' },
  { id:  318, r: 'lanzar', m: 'werfen / starten' },
  { id:  319, r: 'diferencia', m: 'Unterschied' },
  { id:  320, r: 'bueno', m: 'also... / nun...' },
  { id:  321, r: 'propiedad', m: 'Eigentum / Eigenschaft' },
  { id:  322, r: 'repetir', m: 'wiederholen' },
  { id:  323, r: 'viaje', m: 'Reise' },
  { id:  324, r: 'nosotros', m: 'wir' },
  { id:  325, r: 'diez', m: 'zehn' },
  { id:  326, r: 'indicar', m: 'anzeigen / hinweisen' },
  { id:  327, r: 'capaz', m: 'fähig / in der Lage' },
  { id:  328, r: 'todavía', m: 'noch / immer noch' },
  { id:  329, r: 'servir', m: 'dienen / bedienen' },
  { id:  330, r: 'joven', m: 'junger Mensch / Jugendlicher' },
  { id:  331, r: 'comenzar', m: 'beginnen / anfangen' },
  { id:  332, r: 'idea', m: 'Idee' },
  { id:  333, r: 'peso', m: 'Gewicht / Peso' },
  { id:  334, r: 'ocho', m: 'acht' },
  { id:  335, r: 'estudio', m: 'Studie / Lernen' },
  { id:  336, r: 'grupo', m: 'Gruppe' },
  { id:  337, r: 'decidir', m: 'entscheiden' },
  { id:  338, r: 'considerar', m: 'überlegen / betrachten' },
  { id:  339, r: 'allá', m: 'dort drüben' },
  { id:  340, r: 'mal', m: 'schlecht / übel' },
  { id:  341, r: 'anunciar', m: 'ankündigen / bekanntmachen' },
  { id:  342, r: 'sociedad', m: 'Gesellschaft' },
  { id:  343, r: 'política', m: 'Politik' },
  { id:  344, r: 'detener', m: 'aufhalten / verhaften' },
  { id:  345, r: 'camino', m: 'Weg / Straße' },
  { id:  346, r: 'duda', m: 'Zweifel' },
  { id:  347, r: 'dinero', m: 'Geld' },
  { id:  348, r: 'millón', m: 'Million' },
  { id:  349, r: 'abandonar', m: 'verlassen / aufgeben' },
  { id:  350, r: 'pieza', m: 'Stück / Teil' },
  { id:  351, r: 'claro', m: 'natürlich / klar' },
  { id:  352, r: 'movimiento', m: 'Bewegung' },
  { id:  353, r: 'sitio', m: 'Ort / Platz' },
  { id:  354, r: 'arriba', m: 'oben / hinauf' },
  { id:  355, r: 'crecer', m: 'wachsen / zunehmen' },
  { id:  356, r: 'siglo', m: 'Jahrhundert' },
  { id:  357, r: 'necesidad', m: 'Notwendigkeit / Bedarf' },
  { id:  358, r: 'verdadero', m: 'wahr / echt' },
  { id:  359, r: 'doctor', m: 'Arzt / Doktor' },
  { id:  360, r: 'natural', m: 'natürlich' },
  { id:  361, r: 'contestar', m: 'antworten / erwidern' },
  { id:  362, r: 'mercado', m: 'Markt' },
  { id:  363, r: 'reconocer', m: 'erkennen / zugeben' },
  { id:  364, r: 'importante', m: 'wichtig' },
  { id:  365, r: 'recurso', m: 'Ressource / Mittel' },
  { id:  366, r: 'intentar', m: 'versuchen' },
  { id:  367, r: 'realizar', m: 'verwirklichen / ausführen' },
  { id:  368, r: 'mes', m: 'Monat' },
  { id:  369, r: 'golpe', m: 'Schlag / Stoß' },
  { id:  370, r: 'grado', m: 'Grad / Stufe' },
  { id:  371, r: 'morir', m: 'sterben' },
  { id:  372, r: 'ojo', m: 'Auge' },
  { id:  373, r: 'permitir', m: 'erlauben / gestatten' },
  { id:  374, r: 'humano', m: 'menschlich / Mensch' },
  { id:  375, r: 'físico', m: 'physisch / körperlich' },
  { id:  376, r: 'convertir', m: 'verwandeln / umwandeln' },
  { id:  377, r: 'voz', m: 'Stimme' },
  { id:  378, r: 'incluso', m: 'sogar / einschließlich' },
  { id:  379, r: 'responsabilidad', m: 'Verantwortung' },
  { id:  380, r: 'bastante', m: 'ziemlich / genug' },
  { id:  381, r: 'profundo', m: 'tief / tiefgründig' },
  { id:  382, r: 'minuto', m: 'Minute' },
  { id:  383, r: 'suelo', m: 'Boden / Fußboden' },
  { id:  384, r: 'traer', m: 'bringen / mitbringen' },
  { id:  385, r: 'asegurar', m: 'sichern / versichern' },
  { id:  386, r: 'brazo', m: 'Arm' },
  { id:  387, r: 'uso', m: 'Verwendung / Gebrauch' },
  { id:  388, r: 'parecido', m: 'ähnlich' },
  { id:  389, r: 'imagen', m: 'Bild / Abbild' },
  { id:  390, r: 'origen', m: 'Herkunft / Ursprung' },
  { id:  391, r: 'caer', m: 'fallen' },
  { id:  392, r: 'relación', m: 'Beziehung / Verhältnis' },
  { id:  393, r: 'apoyar', m: 'unterstützen / sich stützen' },
  { id:  394, r: 'sangre', m: 'Blut' },
  { id:  395, r: 'demás', m: 'die anderen / der Rest' },
  { id:  396, r: 'igual', m: 'gleich / gleichwertig' },
  { id:  397, r: 'edad', m: 'Alter' },
  { id:  398, r: 'cantidad', m: 'Menge / Anzahl' },
  { id:  399, r: 'actuar', m: 'handeln / auftreten' },
  { id:  400, r: 'comprobar', m: 'überprüfen / beweisen' },
  { id:  401, r: 'comprar', m: 'kaufen' },
  { id:  402, r: 'según', m: 'laut / gemäß' },
  { id:  403, r: 'observar', m: 'beobachten' },
  { id:  404, r: 'frente', m: 'gegenüber / Stirn' },
  { id:  405, r: 'lograr', m: 'erreichen / schaffen' },
  { id:  406, r: 'puerta', m: 'Tür' },
  { id:  407, r: 'completo', m: 'vollständig / komplett' },
  { id:  408, r: 'moderno', m: 'modern' },
  { id:  409, r: 'atravesar', m: 'durchqueren / überqueren' },
  { id:  410, r: 'maestro', m: 'Meister / Lehrer' },
  { id:  411, r: 'oír', m: 'hören' },
  { id:  412, r: 'adelante', m: 'vorwärts / weiter' },
  { id:  413, r: 'diferente', m: 'verschieden / anders' },
  { id:  414, r: 'delante', m: 'vorne / vor' },
  { id:  415, r: 'sentido', m: 'Sinn / Gefühl' },
  { id:  416, r: 'imposible', m: 'unmöglich' },
  { id:  417, r: 'solamente', m: 'nur / ausschließlich' },
  { id:  418, r: 'libro', m: 'Buch' },
  { id:  419, r: 'directamente', m: 'direkt / geradewegs' },
  { id:  420, r: 'lenguaje', m: 'Sprache / Ausdrucksweise' },
  { id:  421, r: 'ello', m: 'es (sächlich)' },
  { id:  422, r: 'difícil', m: 'schwierig / schwer' },
  { id:  423, r: 'ofrecer', m: 'anbieten / anbieten' },
  { id:  424, r: 'sistema', m: 'System' },
  { id:  425, r: 'enorme', m: 'enorm / riesig' },
  { id:  426, r: 'realmente', m: 'wirklich / tatsächlich' },
  { id:  427, r: 'social', m: 'sozial' },
  { id:  428, r: 'abierto', m: 'offen / geöffnet' },
  { id:  429, r: 'subir', m: 'hochgehen / steigen' },
  { id:  430, r: 'evitar', m: 'vermeiden / verhindern' },
  { id:  431, r: 'superar', m: 'überwinden / überbieten' },
  { id:  432, r: 'papel', m: 'Papier / Rolle' },
  { id:  433, r: 'surgir', m: 'auftauchen / entstehen' },
  { id:  434, r: 'rojo', m: 'rot' },
  { id:  435, r: 'pasado', m: 'vergangen / letzte' },
  { id:  436, r: 'favor', m: 'Gefallen / Gunst' },
  { id:  437, r: 'siguiente', m: 'nächste / folgend' },
  { id:  438, r: 'semana', m: 'Woche' },
  { id:  439, r: 'miembro', m: 'Mitglied / Gliedmaße' },
  { id:  440, r: 'suponer', m: 'annehmen / voraussetzen' },
  { id:  441, r: 'puro', m: 'rein / pur' },
  { id:  442, r: 'carga', m: 'Last / Fracht' },
  { id:  443, r: 'calor', m: 'Wärme / Hitze' },
  { id:  444, r: 'enemigo', m: 'Feind' },
  { id:  445, r: 'tender', m: 'neigen / auslegen' },
  { id:  446, r: 'serio', m: 'ernst / seriös' },
  { id:  447, r: 'madre', m: 'Mutter' },
  { id:  448, r: 'mover', m: 'bewegen / anspornen' },
  { id:  449, r: 'demasiado', m: 'zu viel / zu sehr' },
  { id:  450, r: 'ganar', m: 'gewinnen / verdienen' },
  { id:  451, r: 'lleno', m: 'voll / gefüllt' },
  { id:  452, r: 'altura', m: 'Höhe' },
  { id:  453, r: 'civil', m: 'zivil / bürgerlich' },
  { id:  454, r: 'niña', m: 'Mädchen / Kind' },
  { id:  455, r: 'cara', m: 'Gesicht / Ausdruck' },
  { id:  456, r: 'metro', m: 'Meter / U-Bahn' },
  { id:  457, r: 'cuidado', m: 'Vorsicht / Sorgfalt' },
  { id:  458, r: 'levantar', m: 'heben / aufheben' },
  { id:  459, r: 'dios', m: 'Gott' },
  { id:  460, r: 'hermano', m: 'Bruder / (pl.) Geschwister' },
  { id:  461, r: 'participar', m: 'teilnehmen' },
  { id:  462, r: 'dónde', m: 'wo?' },
  { id:  463, r: 'explicar', m: 'erklären' },
  { id:  464, r: 'libertad', m: 'Freiheit' },
  { id:  465, r: 'naturaleza', m: 'Natur / Charakter' },
  { id:  466, r: 'sol', m: 'Sonne' },
  { id:  467, r: 'popular', m: 'beliebt / populär' },
  { id:  468, r: 'utilizar', m: 'nutzen / verwenden' },
  { id:  469, r: 'voluntad', m: 'Wille / Absicht' },
  { id:  470, r: 'verde', m: 'grün' },
  { id:  471, r: 'extraño', m: 'seltsam / fremd' },
  { id:  472, r: 'accidente', m: 'Unfall' },
  { id:  473, r: 'económico', m: 'wirtschaftlich' },
  { id:  474, r: 'desaparecer', m: 'verschwinden' },
  { id:  475, r: 'rico', m: 'reich / lecker' },
  { id:  476, r: 'olvidar', m: 'vergessen' },
  { id:  477, r: 'zona', m: 'Zone / Gebiet' },
  { id:  478, r: 'fuera', m: 'außen / draußen' },
  { id:  479, r: 'número', m: 'Nummer / Zahl' },
  { id:  480, r: 'estado', m: 'Zustand / Staat' },
  { id:  481, r: 'través', m: 'durch / a través: quer durch' },
  { id:  482, r: 'especie', m: 'Art / Spezies' },
  { id:  483, r: 'empresa', m: 'Unternehmen / Firma' },
  { id:  484, r: 'cincuenta', m: 'fünfzig' },
  { id:  485, r: 'nacer', m: 'geboren werden' },
  { id:  486, r: 'lengua', m: 'Sprache / Zunge' },
  { id:  487, r: 'usar', m: 'benutzen / verwenden' },
  { id:  488, r: 'pagar', m: 'bezahlen' },
  { id:  489, r: 'tamaño', m: 'Größe / Ausmaß' },
  { id:  490, r: 'revista', m: 'Zeitschrift / Magazin' },
  { id:  491, r: 'cerrado', m: 'geschlossen' },
  { id:  492, r: 'frontera', m: 'Grenze' },
  { id:  493, r: 'faltar', m: 'fehlen / mangeln' },
  { id:  494, r: 'animal', m: 'Tier' },
  { id:  495, r: 'acción', m: 'Handlung / Tat' },
  { id:  496, r: 'correr', m: 'laufen / rennen' },
  { id:  497, r: 'corazón', m: 'Herz' },
  { id:  498, r: 'aprender', m: 'lernen' },
  { id:  499, r: 'enseñar', m: 'lehren / zeigen' },
  { id:  500, r: 'quitar', m: 'wegnehmen / entfernen' },
  { id:  501, r: 'mensaje', m: 'Nachricht' },
  { id:  502, r: 'analizar', m: 'analysieren' },
  { id:  503, r: 'bien', m: 'Gut / Vorteil' },
  { id:  504, r: 'público', m: 'öffentlich / Publikum' },
  { id:  505, r: 'elegir', m: 'wählen / aussuchen' },
  { id:  506, r: 'región', m: 'Region' },
  { id:  507, r: 'policía', m: 'Polizei / Polizist' },
  { id:  508, r: 'comienzo', m: 'Anfang / Beginn' },
  { id:  509, r: 'suceder', m: 'passieren / geschehen' },
  { id:  510, r: 'fondo', m: 'Boden / Hintergrund' },
  { id:  511, r: 'amor', m: 'Liebe' },
  { id:  512, r: 'resolver', m: 'lösen / klären' },
  { id:  513, r: 'vecino', m: 'Nachbar' },
  { id:  514, r: 'actividad', m: 'Aktivität / Tätigkeit' },
  { id:  515, r: 'corto', m: 'kurz / knapp' },
  { id:  516, r: 'oportunidad', m: 'Gelegenheit / Chance' },
  { id:  517, r: 'derecha', m: 'rechte Seite / Recht' },
  { id:  518, r: 'dirigir', m: 'leiten / führen' },
  { id:  519, r: 'unir', m: 'verbinden / vereinen' },
  { id:  520, r: 'muerte', m: 'Tod' },
  { id:  521, r: 'plantear', m: 'aufwerfen / vorschlagen' },
  { id:  522, r: 'gobierno', m: 'Regierung' },
  { id:  523, r: 'compartir', m: 'teilen / mitteilen' },
  { id:  524, r: 'sentar', m: 'setzen / sitzen' },
  { id:  525, r: 'pensamiento', m: 'Gedanke / Denken' },
  { id:  526, r: 'ley', m: 'Gesetz' },
  { id:  527, r: 'plano', m: 'Karte / Ebene' },
  { id:  528, r: 'tocar', m: 'berühren / spielen (Instrument)' },
  { id:  529, r: 'importancia', m: 'Bedeutung / Wichtigkeit' },
  { id:  530, r: 'terrible', m: 'schrecklich / furchtbar' },
  { id:  531, r: 'línea', m: 'Linie / Zeile' },
  { id:  532, r: 'temprano', m: 'früh' },
  { id:  533, r: 'andar', m: 'gehen / laufen' },
  { id:  534, r: 'resultado', m: 'Ergebnis / Resultat' },
  { id:  535, r: 'espacio', m: 'Raum / Platz' },
  { id:  536, r: 'constituir', m: 'bilden / darstellen' },
  { id:  537, r: 'carrera', m: 'Karriere / Rennen' },
  { id:  538, r: 'mañana', m: 'Morgen / morgen' },
  { id:  539, r: 'frase', m: 'Satz / Phrase' },
  { id:  540, r: 'reunión', m: 'Treffen / Versammlung' },
  { id:  541, r: 'cultura', m: 'Kultur' },
  { id:  542, r: 'enfermedad', m: 'Krankheit' },
  { id:  543, r: 'resto', m: 'Rest / Überrest' },
  { id:  544, r: 'literatura', m: 'Literatur' },
  { id:  545, r: 'fe', m: 'Glaube / Vertrauen' },
  { id:  546, r: 'sueño', m: 'Traum / Schlaf' },
  { id:  547, r: 'importar', m: 'wichtig sein / importieren' },
  { id:  548, r: 'dispuesto', m: 'bereit / willig' },
  { id:  549, r: 'compañero', m: 'Kamerad / Mitschüler' },
  { id:  550, r: 'depender', m: 'abhängen von' },
  { id:  551, r: 'poder', m: 'Macht / Kraft' },
  { id:  552, r: 'verano', m: 'Sommer' },
  { id:  553, r: 'acontecimiento', m: 'Ereignis / Begebenheit' },
  { id:  554, r: 'cumplir', m: 'erfüllen / einhalten' },
  { id:  555, r: 'jamás', m: 'niemals' },
  { id:  556, r: 'tercero', m: 'dritte' },
  { id:  557, r: 'continuar', m: 'fortsetzen / weitermachen' },
  { id:  558, r: 'arma', m: 'Waffe' },
  { id:  559, r: 'pie', m: 'Fuß / Basis' },
  { id:  560, r: 'esfuerzo', m: 'Anstrengung / Bemühung' },
  { id:  561, r: 'condición', m: 'Bedingung / Zustand' },
  { id:  562, r: 'contribuir', m: 'beitragen' },
  { id:  563, r: 'cortar', m: 'schneiden' },
  { id:  564, r: 'atender', m: 'bedienen / sich kümmern' },
  { id:  565, r: 'ayudar', m: 'helfen' },
  { id:  566, r: 'color', m: 'Farbe' },
  { id:  567, r: 'pasado', m: 'Vergangenheit' },
  { id:  568, r: 'lista', m: 'Liste / Namensliste' },
  { id:  569, r: 'famoso', m: 'berühmt' },
  { id:  570, r: 'falta', m: 'Fehler / Mangel' },
  { id:  571, r: 'ocasión', m: 'Gelegenheit' },
  { id:  572, r: 'visitar', m: 'besuchen' },
  { id:  573, r: 'premio', m: 'Preis / Auszeichnung' },
  { id:  574, r: 'visita', m: 'Besuch / Besucher' },
  { id:  575, r: 'tu', m: 'dein (possessiv)' },
  { id:  576, r: 'dedo', m: 'Finger / Zeh' },
  { id:  577, r: 'quince', m: 'fünfzehn' },
  { id:  578, r: 'demostrar', m: 'demonstrieren / beweisen' },
  { id:  579, r: 'despertar', m: 'aufwecken / erwachen' },
  { id:  580, r: 'existencia', m: 'Existenz / Leben' },
  { id:  581, r: 'mente', m: 'Geist / Verstand' },
  { id:  582, r: 'mayoría', m: 'Mehrheit' },
  { id:  583, r: 'conocimiento', m: 'Wissen / Kenntnis' },
  { id:  584, r: 'examen', m: 'Prüfung / Untersuchung' },
  { id:  585, r: 'teléfono', m: 'Telefon' },
  { id:  586, r: 'juego', m: 'Spiel' },
  { id:  587, r: 'mío', m: 'meins' },
  { id:  588, r: 'acto', m: 'Akt / Handlung' },
  { id:  589, r: 'rama', m: 'Ast / Zweig' },
  { id:  590, r: 'libre', m: 'frei / unbesetzt' },
  { id:  591, r: 'recoger', m: 'aufheben / einsammeln' },
  { id:  592, r: 'inmediato', m: 'sofortig / unmittelbar' },
  { id:  593, r: 'nivel', m: 'Niveau / Ebene' },
  { id:  594, r: 'ciencia', m: 'Wissenschaft' },
  { id:  595, r: 'ayuda', m: 'Hilfe / Unterstützung' },
  { id:  596, r: 'ambiente', m: 'Atmosphäre / Umgebung' },
  { id:  597, r: 'imponer', m: 'auferlegen / durchsetzen' },
  { id:  598, r: 'alemán', m: 'Deutsch / Deutscher' },
  { id:  599, r: 'casar', m: 'heiraten' },
  { id:  600, r: 'masa', m: 'Masse / Teig' },
  { id:  601, r: 'clásico', m: 'klassisch' },
  { id:  602, r: 'futuro', m: 'Zukunft' },
  { id:  603, r: 'loco', m: 'verrückt / wahnsinnig' },
  { id:  604, r: 'atención', m: 'Aufmerksamkeit' },
  { id:  605, r: 'pegar', m: 'kleben / schlagen' },
  { id:  606, r: 'comida', m: 'Essen / Mahlzeit' },
  { id:  607, r: 'capacidad', m: 'Kapazität / Fähigkeit' },
  { id:  608, r: 'ambos', m: 'beide' },
  { id:  609, r: 'concreto', m: 'konkret / real' },
  { id:  610, r: 'ocupar', m: 'besetzen / belegen' },
  { id:  611, r: 'entrada', m: 'Eingang / Eintrittskarte' },
  { id:  612, r: 'tú', m: 'du' },
  { id:  613, r: 'objetivo', m: 'Ziel / objektiv' },
  { id:  614, r: 'disposición', m: 'Verfügung / Bereitschaft' },
  { id:  615, r: 'entregar', m: 'übergeben / liefern' },
  { id:  616, r: 'teatro', m: 'Theater' },
  { id:  617, r: 'cuál', m: 'welche/r/s?' },
  { id:  618, r: 'volumen', m: 'Volumen / Band' },
  { id:  619, r: 'francés', m: 'Französisch / Franzose' },
  { id:  620, r: 'cerca', m: 'nah / in der Nähe' },
  { id:  621, r: 'nueve', m: 'neun' },
  { id:  622, r: 'experiencia', m: 'Erfahrung' },
  { id:  623, r: 'descubrir', m: 'entdecken' },
  { id:  624, r: 'pintura', m: 'Malerei / Farbe' },
  { id:  625, r: 'precisamente', m: 'genau / eben' },
  { id:  626, r: 'determinar', m: 'bestimmen / entscheiden' },
  { id:  627, r: 'materia', m: 'Stoff / Fach' },
  { id:  628, r: 'televisión', m: 'Fernsehen / TV' },
  { id:  629, r: 'autoridad', m: 'Behörde / Autorität' },
  { id:  630, r: 'hogar', m: 'Zuhause / Heim' },
  { id:  631, r: 'norteamericano', m: 'nordamerikanisch' },
  { id:  632, r: 'material', m: 'Material / Stoff' },
  { id:  633, r: 'cuándo', m: 'wann?' },
  { id:  634, r: 'pintar', m: 'malen / anstreichen' },
  { id:  635, r: 'energía', m: 'Energie' },
  { id:  636, r: 'recuerdo', m: 'Erinnerung / Andenken' },
  { id:  637, r: 'conservar', m: 'bewahren / erhalten' },
  { id:  638, r: 'meter', m: 'hineinstecken / stecken' },
  { id:  639, r: 'santa', m: 'Heilige (weibl.)' },
  { id:  640, r: 'común', m: 'gemeinsam / üblich' },
  { id:  641, r: 'viajar', m: 'reisen' },
  { id:  642, r: 'discutir', m: 'diskutieren / streiten' },
  { id:  643, r: 'pasión', m: 'Leidenschaft' },
  { id:  644, r: 'vino', m: 'Wein' },
  { id:  645, r: 'alma', m: 'Seele' },
  { id:  646, r: 'teoría', m: 'Theorie' },
  { id:  647, r: 'temer', m: 'fürchten' },
  { id:  648, r: 'artista', m: 'Künstler' },
  { id:  649, r: 'junto', m: 'zusammen' },
  { id:  650, r: 'fecha', m: 'Datum / Tag' },
  { id:  651, r: 'sufrir', m: 'leiden / erleiden' },
  { id:  652, r: 'cielo', m: 'Himmel / Decke' },
  { id:  653, r: 'temor', m: 'Furcht / Angst' },
  { id:  654, r: 'jefe', m: 'Chef / Anführer' },
  { id:  655, r: 'capítulo', m: 'Kapitel' },
  { id:  656, r: 'profesional', m: 'professionell / Fachmann' },
  { id:  657, r: 'techo', m: 'Dach' },
  { id:  658, r: 'presencia', m: 'Anwesenheit' },
  { id:  659, r: 'separar', m: 'trennen' },
  { id:  660, r: 'decisión', m: 'Entscheidung' },
  { id:  661, r: 'absolutamente', m: 'absolut / vollkommen' },
  { id:  662, r: 'echar', m: 'werfen / ausgießen' },
  { id:  663, r: 'nacional', m: 'national' },
  { id:  664, r: 'objeto', m: 'Gegenstand / Objekt' },
  { id:  665, r: 'autor', m: 'Autor / Verfasser' },
  { id:  666, r: 'aspecto', m: 'Aspekt / Aussehen' },
  { id:  667, r: 'seguramente', m: 'sicherlich / bestimmt' },
  { id:  668, r: 'resistir', m: 'widerstehen / aushalten' },
  { id:  669, r: 'responder', m: 'antworten / reagieren' },
  { id:  670, r: 'encima', m: 'oben / darüber' },
  { id:  671, r: 'acercar', m: 'näherkommen / heranführen' },
  { id:  672, r: 'preparar', m: 'vorbereiten' },
  { id:  673, r: 'citar', m: 'zitieren' },
  { id:  674, r: 'extender', m: 'ausdehnen / verbreiten' },
  { id:  675, r: 'descansar', m: 'ausruhen' },
  { id:  676, r: 'asunto', m: 'Angelegenheit / Sache' },
  { id:  677, r: 'fundamental', m: 'grundlegend / fundamental' },
  { id:  678, r: 'facilidad', m: 'Leichtigkeit' },
  { id:  679, r: 'preocupar', m: 'sich sorgen / beunruhigen' },
  { id:  680, r: 'atrás', m: 'hinten / zurück' },
  { id:  681, r: 'empleado', m: 'Angestellter' },
  { id:  682, r: 'pronto', m: 'bald / schnell' },
  { id:  683, r: 'concepto', m: 'Konzept / Begriff' },
  { id:  684, r: 'grave', m: 'ernst / schwerwiegend' },
  { id:  685, r: 'retirar', m: 'zurückziehen / wegnehmen' },
  { id:  686, r: 'establecer', m: 'einrichten / festlegen' },
  { id:  687, r: 'adquirir', m: 'erwerben / bekommen' },
  { id:  688, r: 'costar', m: 'kosten / schwerfallen' },
  { id:  689, r: 'mencionar', m: 'erwähnen' },
  { id:  690, r: 'práctica', m: 'Praxis / Übung' },
  { id:  691, r: 'publicar', m: 'veröffentlichen' },
  { id:  692, r: 'idioma', m: 'Sprache (spezifisch)' },
  { id:  693, r: 'aprovechar', m: 'nutzen / ausnutzen' },
  { id:  694, r: 'futuro', m: 'Zukunft / zukünftig' },
  { id:  695, r: 'conclusión', m: 'Schluss / Fazit' },
  { id:  696, r: 'vehículo', m: 'Fahrzeug' },
  { id:  697, r: 'militar', m: 'militärisch / Militär' },
  { id:  698, r: 'compañía', m: 'Gesellschaft / Unternehmen' },
  { id:  699, r: 'curso', m: 'Kurs / Verlauf' },
  { id:  700, r: 'cine', m: 'Kino' },
  { id:  701, r: 'marcar', m: 'markieren / wählen' },
  { id:  702, r: 'comentario', m: 'Kommentar / Bemerkung' },
  { id:  703, r: 'vivo', m: 'lebendig / lebhaft' },
  { id:  704, r: 'lucha', m: 'Kampf / Ringen' },
  { id:  705, r: 'daño', m: 'Schaden / Verletzung' },
  { id:  706, r: 'intento', m: 'Versuch' },
  { id:  707, r: 'enfermo', m: 'krank' },
  { id:  708, r: 'piso', m: 'Stockwerk / Boden' },
  { id:  709, r: 'gesto', m: 'Geste' },
  { id:  710, r: 'derecho', m: 'gerade / direkt' },
  { id:  711, r: 'actual', m: 'aktuell / derzeitig' },
  { id:  712, r: 'diciembre', m: 'Dezember' },
  { id:  713, r: 'economía', m: 'Wirtschaft / Ökonomie' },
  { id:  714, r: 'introducir', m: 'einführen / einbringen' },
  { id:  715, r: 'totalmente', m: 'vollständig / total' },
  { id:  716, r: 'cuánto', m: 'wie viel?' },
  { id:  717, r: 'posición', m: 'Position / Lage' },
  { id:  718, r: 'lejos', m: 'weit / fern' },
  { id:  719, r: 'leche', m: 'Milch' },
  { id:  720, r: 'conciencia', m: 'Bewusstsein / Gewissen' },
  { id:  721, r: 'aplicar', m: 'anwenden / aufragen' },
  { id:  722, r: 'bajar', m: 'herunterkommen / senken' },
  { id:  723, r: 'consejo', m: 'Rat / Ratschlag' },
  { id:  724, r: 'próximo', m: 'nächste' },
  { id:  725, r: 'piedra', m: 'Stein' },
  { id:  726, r: 'médico', m: 'Arzt' },
  { id:  727, r: 'director', m: 'Direktor / Leiter' },
  { id:  728, r: 'recuperar', m: 'erholen / zurückgewinnen' },
  { id:  729, r: 'principal', m: 'hauptsächlich / Haupt-' },
  { id:  730, r: 'cuento', m: 'Geschichte / Erzählung' },
  { id:  731, r: 'mirada', m: 'Blick / Blickkontakt' },
  { id:  732, r: 'siete', m: 'sieben' },
  { id:  733, r: 'duro', m: 'hart / schwer' },
  { id:  734, r: 'información', m: 'Information' },
  { id:  735, r: 'espíritu', m: 'Geist / Seele' },
  { id:  736, r: 'artículo', m: 'Artikel / Produkt' },
  { id:  737, r: 'trasladar', m: 'verschieben / übertragen' },
  { id:  738, r: 'hábito', m: 'Gewohnheit' },
  { id:  739, r: 'positivo', m: 'positiv' },
  { id:  740, r: 'expresión', m: 'Ausdruck' },
  { id:  741, r: 'exponer', m: 'aussetzen / darlegen' },
  { id:  742, r: 'letra', m: 'Buchstabe / Liedtext' },
  { id:  743, r: 'partida', m: 'Abfahrt / Spiel' },
  { id:  744, r: 'sencillo', m: 'einfach / schlicht' },
  { id:  745, r: 'apenas', m: 'kaum / gerade eben' },
  { id:  746, r: 'estilo', m: 'Stil' },
  { id:  747, r: 'perfecto', m: 'perfekt' },
  { id:  748, r: 'vuelta', m: 'Rückkehr / Runde' },
  { id:  749, r: 'excepción', m: 'Ausnahme' },
  { id:  750, r: 'control', m: 'Kontrolle' },
  { id:  751, r: 'esperanza', m: 'Hoffnung' },
  { id:  752, r: 'superior', m: 'überlegen / höher' },
  { id:  753, r: 'habitación', m: 'Zimmer / Schlafzimmer' },
  { id:  754, r: 'manejar', m: 'handhaben / fahren' },
  { id:  755, r: 'representar', m: 'vertreten / darstellen' },
  { id:  756, r: 'causa', m: 'Ursache / Grund' },
  { id:  757, r: 'semejante', m: 'ähnlich / solch' },
  { id:  758, r: 'alrededor', m: 'um … herum / etwa' },
  { id:  759, r: 'profesor', m: 'Lehrer / Professor' },
  { id:  760, r: 'siquiera', m: 'wenigstens / sogar' },
  { id:  761, r: 'acompañar', m: 'begleiten' },
  { id:  762, r: 'labor', m: 'Arbeit / Aufgabe' },
  { id:  763, r: 'trabajador', m: 'Arbeiter / fleißig' },
  { id:  764, r: 'carácter', m: 'Charakter / Persönlichkeit' },
  { id:  765, r: 'cantar', m: 'singen' },
  { id:  766, r: 'operar', m: 'operieren / arbeiten' },
  { id:  767, r: 'obstante', m: 'no obstante: dennoch' },
  { id:  768, r: 'joven', m: 'jung' },
  { id:  769, r: 'sexo', m: 'Geschlecht / Sex' },
  { id:  770, r: 'documento', m: 'Dokument / Urkunde' },
  { id:  771, r: 'motivo', m: 'Motiv / Grund' },
  { id:  772, r: 'construir', m: 'bauen / errichten' },
  { id:  773, r: 'opinión', m: 'Meinung / Ansicht' },
  { id:  774, r: 'dominar', m: 'beherrschen / dominieren' },
  { id:  775, r: 'oscuro', m: 'dunkel / unklar' },
  { id:  776, r: 'acordar', m: 'beschließen / erinnern' },
  { id:  777, r: 'generalmente', m: 'im Allgemeinen' },
  { id:  778, r: 'cerrar', m: 'schließen / zumachen' },
  { id:  779, r: 'cadena', m: 'Kette' },
  { id:  780, r: 'tras', m: 'nach / hinter' },
  { id:  781, r: 'repartir', m: 'verteilen / aufteilen' },
  { id:  782, r: 'fenómeno', m: 'Phänomen' },
  { id:  783, r: 'proceso', m: 'Prozess / Verfahren' },
  { id:  784, r: 'desarrollo', m: 'Entwicklung' },
  { id:  785, r: 'contacto', m: 'Kontakt' },
  { id:  786, r: 'dudar', m: 'zweifeln' },
  { id:  787, r: 'prestar', m: 'leihen' },
  { id:  788, r: 'guardar', m: 'aufbewahren / bewachen' },
  { id:  789, r: 'llorar', m: 'weinen' },
  { id:  790, r: 'margen', m: 'Rand / Spielraum' },
  { id:  791, r: 'hallar', m: 'finden / herausfinden' },
  { id:  792, r: 'inmediatamente', m: 'sofort / unverzüglich' },
  { id:  793, r: 'dolor', m: 'Schmerz / Kummer' },
  { id:  794, r: 'bomba', m: 'Bombe / Pumpe' },
  { id:  795, r: 'impresión', m: 'Eindruck / Druck' },
  { id:  796, r: 'respuesta', m: 'Antwort' },
  { id:  797, r: 'culpa', m: 'Schuld / Fehler' },
  { id:  798, r: 'interesante', m: 'interessant' },
  { id:  799, r: 'añadir', m: 'hinzufügen' },
  { id:  800, r: 'argentino', m: 'argentinisch / Argentinier' },
  { id:  801, r: 'departamento', m: 'Abteilung / Wohnung' },
  { id:  802, r: 'durar', m: 'dauern / andauern' },
  { id:  803, r: 'tirar', m: 'werfen / ziehen' },
  { id:  804, r: 'colegio', m: 'Schule / College' },
  { id:  805, r: 'invitar', m: 'einladen' },
  { id:  806, r: 'marido', m: 'Ehemann' },
  { id:  807, r: 'diario', m: 'täglich / Tagebuch' },
  { id:  808, r: 'naturalmente', m: 'natürlich' },
  { id:  809, r: 'tarea', m: 'Aufgabe / Hausaufgabe' },
  { id:  810, r: 'acceso', m: 'Zugang / Zugriff' },
  { id:  811, r: 'impedir', m: 'verhindern / hindern' },
  { id:  812, r: 'crisis', m: 'Krise' },
  { id:  813, r: 'sala', m: 'Saal / Zimmer' },
  { id:  814, r: 'actitud', m: 'Einstellung / Haltung' },
  { id:  815, r: 'raro', m: 'seltsam / selten' },
  { id:  816, r: 'muerto', m: 'tot / Toter' },
  { id:  817, r: 'suerte', m: 'Glück / Schicksal' },
  { id:  818, r: 'religioso', m: 'religiös' },
  { id:  819, r: 'instalar', m: 'installieren / einrichten' },
  { id:  820, r: 'serie', m: 'Serie / Reihe' },
  { id:  821, r: 'cubrir', m: 'bedecken / abdecken' },
  { id:  822, r: 'cercano', m: 'nah / in der Nähe' },
  { id:  823, r: 'argumento', m: 'Argument / Handlung' },
  { id:  824, r: 'prueba', m: 'Beweis / Probe / Test' },
  { id:  825, r: 'hundir', m: 'versenken / sinken' },
  { id:  826, r: 'éxito', m: 'Erfolg' },
  { id:  827, r: 'absoluto', m: 'absolut' },
  { id:  828, r: 'interpretar', m: 'interpretieren / spielen' },
  { id:  829, r: 'pleno', m: 'voll / vollständig' },
  { id:  830, r: 'normal', m: 'normal / gewöhnlich' },
  { id:  831, r: 'funcionar', m: 'funktionieren' },
  { id:  832, r: 'señalar', m: 'zeigen / hinweisen' },
  { id:  833, r: 'cuarto', m: 'vierte / Viertel' },
  { id:  834, r: 'experimentar', m: 'erfahren / erleben' },
  { id:  835, r: 'conocido', m: 'bekannt / Bekannter' },
  { id:  836, r: 'mezclar', m: 'mischen' },
  { id:  837, r: 'paz', m: 'Frieden' },
  { id:  838, r: 'proyecto', m: 'Projekt / Plan' },
  { id:  839, r: 'caja', m: 'Schachtel / Kasse' },
  { id:  840, r: 'rápido', m: 'schnell' },
  { id:  841, r: 'honor', m: 'Ehre' },
  { id:  842, r: 'capital', m: 'Kapital / Hauptstadt' },
  { id:  843, r: 'liberar', m: 'befreien' },
  { id:  844, r: 'completar', m: 'vervollständigen' },
  { id:  845, r: 'interior', m: 'Inneres / innen' },
  { id:  846, r: 'ajeno', m: 'fremd / nicht dazugehörig' },
  { id:  847, r: 'despedir', m: 'entlassen / verabschieden' },
  { id:  848, r: 'chico', m: 'Junge' },
  { id:  849, r: 'nacimiento', m: 'Geburt / Ursprung' },
  { id:  850, r: 'seco', m: 'trocken' },
  { id:  851, r: 'apoyo', m: 'Unterstützung / Rückhalt' },
  { id:  852, r: 'dividir', m: 'teilen / aufteilen' },
  { id:  853, r: 'pesado', m: 'schwer / langweilig' },
  { id:  854, r: 'texto', m: 'Text' },
  { id:  855, r: 'reserva', m: 'Reserve / Reservierung' },
  { id:  856, r: 'defender', m: 'verteidigen / schützen' },
  { id:  857, r: 'pertenecer', m: 'gehören' },
  { id:  858, r: 'formación', m: 'Ausbildung / Bildung' },
  { id:  859, r: 'boca', m: 'Mund / Öffnung' },
  { id:  860, r: 'distancia', m: 'Distanz / Entfernung' },
  { id:  861, r: 'azul', m: 'blau' },
  { id:  862, r: 'opinar', m: 'meinen / der Meinung sein' },
  { id:  863, r: 'máquina', m: 'Maschine' },
  { id:  864, r: 'título', m: 'Titel / Überschrift' },
  { id:  865, r: 'habitual', m: 'gewöhnlich / üblich' },
  { id:  866, r: 'negar', m: 'verneinen / ablehnen' },
  { id:  867, r: 'llamada', m: 'Anruf / Ruf' },
  { id:  868, r: 'ideal', m: 'Ideal / ideal' },
  { id:  869, r: 'suyo', m: 'sein / ihr / Ihr (betont)' },
  { id:  870, r: 'directo', m: 'direkt / gerade' },
  { id:  871, r: 'método', m: 'Methode' },
  { id:  872, r: 'preciso', m: 'präzise / notwendig' },
  { id:  873, r: 'debajo', m: 'unten / darunter' },
  { id:  874, r: 'averiguar', m: 'herausfinden / ermitteln' },
  { id:  875, r: 'presión', m: 'Druck' },
  { id:  876, r: 'ignorar', m: 'nicht wissen / ignorieren' },
  { id:  877, r: 'automóvil', m: 'Auto / Automobil' },
  { id:  878, r: 'detrás', m: 'hinter / dahinter' },
  { id:  879, r: 'contenido', m: 'Inhalt' },
  { id:  880, r: 'hija', m: 'Tochter' },
  { id:  881, r: 'agosto', m: 'August' },
  { id:  882, r: 'cobrar', m: 'kassieren / verdienen' },
  { id:  883, r: 'barco', m: 'Schiff / Boot' },
  { id:  884, r: 'americano', m: 'amerikanisch' },
  { id:  885, r: 'vender', m: 'verkaufen' },
  { id:  886, r: 'sesenta', m: 'sechzig' },
  { id:  887, r: 'animar', m: 'ermutigen / aufheitern' },
  { id:  888, r: 'página', m: 'Seite' },
  { id:  889, r: 'notar', m: 'bemerken' },
  { id:  890, r: 'árbol', m: 'Baum' },
  { id:  891, r: 'plan', m: 'Plan' },
  { id:  892, r: 'alcance', m: 'Reichweite / Umfang' },
  { id:  893, r: 'regresar', m: 'zurückkehren' },
  { id:  894, r: 'mandar', m: 'schicken / befehlen' },
  { id:  895, r: 'moda', m: 'Mode / Trend' },
  { id:  896, r: 'satisfacer', m: 'befriedigen / erfüllen' },
  { id:  897, r: 'curiosidad', m: 'Neugier' },
  { id:  898, r: 'escuela', m: 'Schule' },
  { id:  899, r: 'memoria', m: 'Gedächtnis / Speicher' },
  { id:  900, r: 'espejo', m: 'Spiegel' },
  { id:  901, r: 'elemento', m: 'Element / Bestandteil' },
  { id:  902, r: 'romper', m: 'zerbrechen / unterbrechen' },
  { id:  903, r: 'matar', m: 'töten' },
  { id:  904, r: 'cola', m: 'Schlange / Schwanz' },
  { id:  905, r: 'juventud', m: 'Jugend' },
  { id:  906, r: 'trato', m: 'Abkommen / Umgang' },
  { id:  907, r: 'coche', m: 'Auto' },
  { id:  908, r: 'veinte', m: 'zwanzig' },
  { id:  909, r: 'acudir', m: 'hingehen / kommen' },
  { id:  910, r: 'examinar', m: 'untersuchen / prüfen' },
  { id:  911, r: 'frío', m: 'kalt / Kälte' },
  { id:  912, r: 'simplemente', m: 'einfach / schlicht' },
  { id:  913, r: 'tensión', m: 'Spannung / Stress' },
  { id:  914, r: 'expresar', m: 'ausdrücken' },
  { id:  915, r: 'generación', m: 'Generation' },
  { id:  916, r: 'manifestación', m: 'Demonstration / Kundgebung' },
  { id:  917, r: 'terreno', m: 'Gelände / Boden' },
  { id:  918, r: 'seguro', m: 'sicher / Versicherung' },
  { id:  919, r: 'raza', m: 'Rasse / Abstammung' },
  { id:  920, r: 'arrancar', m: 'starten / herausreißen' },
  { id:  921, r: 'sexual', m: 'sexuell' },
  { id:  922, r: 'puesto', m: 'Stelle / Posten' },
  { id:  923, r: 'familiar', m: 'familiär / vertraut' },
  { id:  924, r: 'aprobar', m: 'genehmigen / bestehen' },
  { id:  925, r: 'abajo', m: 'unten / nach unten' },
  { id:  926, r: 'quejar', m: 'beklagen / beschweren' },
  { id:  927, r: 'juicio', m: 'Urteil / Verstand' },
  { id:  928, r: 'técnico', m: 'technisch / Techniker' },
  { id:  929, r: 'jardín', m: 'Garten' },
  { id:  930, r: 'intervenir', m: 'eingreifen / intervenieren' },
  { id:  931, r: 'público', m: 'Publikum / öffentlich' },
  { id:  932, r: 'consecuencia', m: 'Konsequenz / Folge' },
  { id:  933, r: 'ritmo', m: 'Rhythmus' },
  { id:  934, r: 'perfectamente', m: 'perfekt / vollkommen' },
  { id:  935, r: 'feliz', m: 'glücklich' },
  { id:  936, r: 'exacto', m: 'genau / exakt' },
  { id:  937, r: 'esposa', m: 'Ehefrau' },
  { id:  938, r: 'personaje', m: 'Figur / Charakter' },
  { id:  939, r: 'patria', m: 'Vaterland / Heimat' },
  { id:  940, r: 'inteligente', m: 'intelligent / klug' },
  { id:  941, r: 'calidad', m: 'Qualität' },
  { id:  942, r: 'belleza', m: 'Schönheit' },
  { id:  943, r: 'continuo', m: 'kontinuierlich / ununterbrochen' },
  { id:  944, r: 'instrucción', m: 'Anweisung / Unterricht' },
  { id:  945, r: 'inclinación', m: 'Neigung / Hang' },
  { id:  946, r: 'temperatura', m: 'Temperatur' },
  { id:  947, r: 'huella', m: 'Spur / Abdruck' },
  { id:  948, r: 'mezcla', m: 'Mischung / Gemisch' },
  { id:  949, r: 'ciego', m: 'blind' },
  { id:  950, r: 'lejano', m: 'fern / weit entfernt' },
  { id:  951, r: 'gusto', m: 'Geschmack / Freude' },
  { id:  952, r: 'ejercicio', m: 'Übung / Sport' },
  { id:  953, r: 'hospital', m: 'Krankenhaus' },
  { id:  954, r: 'radio', m: 'Radio / Radius' },
  { id:  955, r: 'treinta', m: 'dreißig' },
  { id:  956, r: 'conveniente', m: 'bequem / passend' },
  { id:  957, r: 'salida', m: 'Ausgang / Ausweg' },
  { id:  958, r: 'sentimiento', m: 'Gefühl / Empfindung' },
  { id:  959, r: 'salvar', m: 'retten' },
  { id:  960, r: 'mar', m: 'Meer' },
  { id:  961, r: 'cuarto', m: 'Zimmer / Raum' },
  { id:  962, r: 'parar', m: 'anhalten / aufhören' },
  { id:  963, r: 'saber', m: 'Wissen' },
  { id:  964, r: 'cargo', m: 'Gebühr / Amt' },
  { id:  965, r: 'poesía', m: 'Gedicht / Poesie' },
  { id:  966, r: 'música', m: 'Musik' },
  { id:  967, r: 'estación', m: 'Bahnhof / Jahreszeit' },
  { id:  968, r: 'justicia', m: 'Gerechtigkeit' },
  { id:  969, r: 'brillante', m: 'glänzend / brillant' },
  { id:  970, r: 'destino', m: 'Schicksal / Ziel' },
  { id:  971, r: 'revolución', m: 'Revolution' },
  { id:  972, r: 'entrega', m: 'Lieferung / Übergabe' },
  { id:  973, r: 'sensación', m: 'Gefühl / Empfindung' },
  { id:  974, r: 'intelectual', m: 'intellektuell' },
  { id:  975, r: 'representante', m: 'Vertreter' },
  { id:  976, r: 'agudo', m: 'scharf / spitz' },
  { id:  977, r: 'rato', m: 'Weile / Moment' },
  { id:  978, r: 'doce', m: 'zwölf' },
  { id:  979, r: 'salto', m: 'Sprung' },
  { id:  980, r: 'alegría', m: 'Freude / Fröhlichkeit' },
  { id:  981, r: 'aun', m: 'noch / sogar' },
  { id:  982, r: 'operación', m: 'Operation' },
  { id:  983, r: 'delicado', m: 'zart / heikel' },
  { id:  984, r: 'nota', m: 'Note / Notiz' },
  { id:  985, r: 'convencido', m: 'überzeugt' },
  { id:  986, r: 'simple', m: 'einfach / schlicht' },
  { id:  987, r: 'construcción', m: 'Bau / Konstruktion' },
  { id:  988, r: 'secretario', m: 'Sekretär' },
  { id:  989, r: 'exposición', m: 'Ausstellung / Ausstellung' },
  { id:  990, r: 'internacional', m: 'international' },
  { id:  991, r: 'clave', m: 'Schlüssel' },
  { id:  992, r: 'cruzar', m: 'kreuzen / überqueren' },
  { id:  993, r: 'personal', m: 'persönlich / Personal' },
  { id:  994, r: 'pared', m: 'Wand' },
  { id:  995, r: 'griego', m: 'griechisch / Grieche' },
  { id:  996, r: 'poderoso', m: 'mächtig' },
  { id:  997, r: 'punta', m: 'Spitze / Tip' },
  { id:  998, r: 'mundial', m: 'weltweit' },
  { id:  999, r: 'especialmente', m: 'besonders' },
  { id: 1000, r: 'empleo', m: 'Beschäftigung / Arbeit' }
];

const SPANISH_PHRASES = {
  'Notfall-Basics': [
    { r: '¡Ayuda!',                           d: 'Hilfe!',                              gap: 'Ayuda',       distractors: ['Perdón', 'Hola', 'Gracias'] },
    { r: '¿Habla inglés?',                    d: 'Sprechen Sie Englisch?',              gap: 'inglés',      distractors: ['español', 'alemán', 'francés'] },
    { r: 'No entiendo.',                      d: 'Ich verstehe nicht.',                 gap: 'entiendo',    distractors: ['hablo', 'escucho', 'sé'] },
    { r: 'Hable más despacio, por favor.',    d: 'Bitte sprechen Sie langsamer.',       gap: 'despacio',    distractors: ['rápido', 'fuerte', 'tarde'] },
    { r: 'Me llamo ...',                      d: 'Ich heiße ...',                       gap: 'llamo',       distractors: ['vivo', 'trabajo', 'tengo'] },
    { r: 'Soy de Alemania.',                  d: 'Ich komme aus Deutschland.',          gap: 'Alemania',    distractors: ['España', 'Francia', 'México'] },
  ],
  'Im Restaurant': [
    { r: '¿Tiene la carta?',                  d: 'Haben Sie die Speisekarte?',          gap: 'carta',       distractors: ['cuenta', 'mesa', 'agua'] },
    { r: '¿Qué es esto?',                     d: 'Was ist das?',                        gap: 'esto',        distractors: ['eso', 'aquí', 'allí'] },
    { r: 'La cuenta, por favor.',             d: 'Die Rechnung bitte.',                 gap: 'cuenta',      distractors: ['carta', 'mesa', 'agua'] },
    { r: '¡Estaba delicioso!',                d: 'Es war köstlich!',                    gap: 'delicioso',   distractors: ['caro', 'frío', 'picante'] },
    { r: 'Sin carne, por favor.',             d: 'Ohne Fleisch bitte.',                 gap: 'carne',       distractors: ['sal', 'aceite', 'leche'] },
  ],
  'Unterwegs': [
    { r: 'Quiero ir a ...',                   d: 'Ich möchte nach ... fahren.',         gap: 'ir',          distractors: ['comer', 'dormir', 'ver'] },
    { r: '¿Dónde está esta dirección?',       d: 'Wo ist diese Adresse?',              gap: 'dirección',   distractors: ['hotel', 'metro', 'mercado'] },
    { r: '¿A qué hora abre?',                 d: 'Wann öffnet es?',                    gap: 'abre',        distractors: ['cierra', 'empieza', 'llega'] },
    { r: '¿Cuántos minutos a pie?',           d: 'Wie viele Minuten zu Fuß?',          gap: 'minutos',     distractors: ['kilómetros', 'horas', 'días'] },
    { r: 'Pare aquí, por favor.',             d: 'Bitte hier anhalten. (Taxi)',         gap: 'Pare',        distractors: ['Vaya', 'Gire', 'Siga'] },
  ],
  'Einkaufen': [
    { r: '¿Cuánto cuesta?',                   d: 'Wie viel kostet das?',               gap: 'cuesta',      distractors: ['vale', 'pesa', 'mide'] },
    { r: 'Es caro.',                          d: 'Das ist teuer.',                      gap: 'caro',        distractors: ['barato', 'bueno', 'nuevo'] },
    { r: '¿Tiene algo más barato?',           d: 'Haben Sie etwas Günstigeres?',       gap: 'barato',      distractors: ['grande', 'nuevo', 'pequeño'] },
    { r: 'Me lo llevo.',                      d: 'Ich nehme es.',                      gap: 'llevo',       distractors: ['dejo', 'veo', 'pago'] },
  ],
  'Zahlen & Zeit': [
    { r: '¿Qué hora es?',                     d: 'Wie viel Uhr ist es?',               gap: 'hora',        distractors: ['día', 'mes', 'año'] },
    { r: '¿Qué fecha es hoy?',                d: 'Welches Datum ist heute?',           gap: 'hoy',         distractors: ['mañana', 'ayer', 'ahora'] },
    { r: 'Mañana / Ayer',                     d: 'Morgen / Gestern',                   gap: 'Mañana',      distractors: ['Hoy', 'Ahora', 'Tarde'] },
    { r: 'Mañana / Tarde / Noche',            d: 'Morgen / Nachmittag / Nacht',        gap: 'Tarde',       distractors: ['Noche', 'Ahora', 'Pronto'] },
  ],
  'Begrüßung & Verabschiedung': [
    { r: '¡Hola! ¿Cómo estás?',              d: 'Hallo! Wie geht es dir?',            gap: 'Cómo',        distractors: ['Dónde', 'Cuándo', 'Qué'] },
    { r: 'Bien, gracias.',                    d: 'Gut, danke.',                         gap: 'gracias',     distractors: ['perdón', 'hola', 'adiós'] },
    { r: 'Hasta luego.',                      d: 'Auf Wiedersehen.',                    gap: 'luego',       distractors: ['mañana', 'pronto', 'siempre'] },
    { r: 'Mucho gusto.',                      d: 'Sehr erfreut. / Schön, Sie zu treffen.', gap: 'gusto',   distractors: ['tiempo', 'trabajo', 'dinero'] },
    { r: 'Por favor / Gracias / De nada.',    d: 'Bitte / Danke / Bitte sehr.',        gap: 'Gracias',     distractors: ['Perdón', 'Hola', 'Adiós'] },
  ],
};
